/*
 * ES.js -- WME Validator Localization for Spain and other countries
 * Copyright (C) 2014-2018 Fernando Anguita aka fernandoanguita
 * Copyright (C) 2014-2018 robindlc
 *
 * This file is part of WME Validator: https://github.com/WMEValidator/
 *
 * WME Validator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * WME Validator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with WME Validator. If not, see <http://www.gnu.org/licenses/>.
 */

/*************************************************************************
 * Be careful editing this file -- other localizations fall back here:
 * - Argentina (AR.js)
 * - Chile (CL.js)
 * - Mexico (MX.js)
 *************************************************************************/

".country": [
             "Spain",
             "Andorra",
             "Bolivia",
             "Costa Rica",
             "Colombia",
             "Cuba",
             "Dominican Republic",
             "Ecuador",
             "Equatorial Guinea",
             "Guatemala",
             "Honduras",
             "Nicaragua",
             "Panama",
             "Peru",
             "Paraguay",
             "El Salvador",
             "Uruguay",
             "Venezuela"
             ],
".author": "robindlc and fernandoanguita",
".updated": "2014-08-30",
".lng": [
         "ES",
         "ES-419",
         "GL"
         ],
"city.consider": "considerar este nombre de ciudad:",
"city.1": "nombre de ciudad demasiado corto",
"city.2": "expandir la abreviación",
"city.3": "completar nombre corto",
"city.4": "completar nombre de ciudad",
"city.5": "corregir mayúsculas",
"city.6": "comprobar orden de palabras",
"city.7": "comprobar abreviaciones",
"city.8a": "añadir nombre de país",
"city.8r": "eliminar nombre de país",
"city.9": "comprobar nombre de país",
"city.10a": "añadir palabra",
"city.10r": "eliminar palabra",
"city.11": "añadir código de país",
"city.12": "nombres idénticos, pero ciudades con diferentes IDs",
"city.13a": "añadir espacio",
"city.13r": "eliminar espacio",
"city.14": "revisar el número",
"props.skipped.title": "El segmento no está revisado",
"props.skipped.problem": "El    segmento se modificó después del 01-05-2014 Y está bloqueado por ti, por lo que Validator no lo revisó",
"err.regexp": "Error al analizar la opción de revisión #${n}:",
"props.disabled": "WME Validator deshabilitado",
"props.limit.title": "Demasiados problemas notificados",
"props.limit.problem": "Hay demasiados problemas notificados, puede que no se muestren todos",
"props.limit.solution": "Deselecciona el segmento y detiene el proceso de escaneo. Luego pincha el botón con la '✘' roja (Limpiar Reporte)",
"props.reports": "informes",
"props.noneditable": "No puedes editar este segmento",
"report.save": "Guardar este informe",
"report.list.andUp": "y subiendo",
"report.list.severity": "Severidad:",
"report.list.reportOnly": "sólo en el informe",
"report.list.forEditors": "Para editores nivel:",
"report.list.forCountries": "Para paises:",
"report.list.forStates": "Para estados:",
"report.list.forCities": "Para ciudades:",
"report.list.params": "Parámetros para configurar en el paquete de localización:",
"report.list.params.set": "Parámetros ajustados en el paquete de localización:",
"report.list.enabled": "${n} revisiones están habilitadas para",
"report.list.disabled": "${n} revisiones están deshabilitadas para",
"report.list.total": "Hay ${n} revisiones disponibles",
"report.list.title": "Lista Completa de Revisiones para",
"report.list.see": "Ver",
"report.list.checks": "Configuración>Acerca>Revisiones disponibles",
"report.list.fallback": "Reglas de Localización de respaldo:",
"report.and": "y",
"report.segments": "Número total de segmentos revisados:",
"report.customs": "Revisiones personalizadas combinadas (verde/azul):",
"report.reported": "Reportados",
"report.errors": "errores",
"report.warnings": "advertencias",
"report.notes": "notas",
"report.contents": "Contenidos:",
"report.summary": "Resumen",
"report.title": "Informe de WME Validator",
"report.share": "para Compartir",
"report.generated.by": "generado por",
"report.generated.on": "activo",
"report.source": "Fuente del informe:",
"report.filter.duplicate": "segmentos duplicados",
"report.filter.streets": "Calles y Calles de Servicio",
"report.filter.other": "Otros conducibles y no conducibles",
"report.filter.noneditable": "segmentos no-editables",
"report.filter.notes": "notas",
"report.filter.title": "Filtro:",
"report.filter.excluded": "están excluidos de este informe.",
"report.search.updated.by": "actualizado por",
"report.search.updated.since": "actualizado desde",
"report.search.city": "desde",
"report.search.reported": "reportado como",
"report.search.title": "Búsqueda:",
"report.search.only": "sólo segmentos",
"report.search.included": "están incluídos en el informe.",
"report.beta.warning": "¡Advertencia WME Beta!",
"report.beta.text": "Este informe se genera en WME Beta con permalinks beta.",
"report.beta.share": "Por favor no comparta estos permalinks!",
"report.size.warning": "<b>¡Advertencia!</b><br> El informe tiene ${n} caracteres, por lo que <b>no cabrá</b> en un mensaje de foro o privado.\n<br>Por favor agrega <b>más filtros</b> para reducir el tamaño del informe.",
"report.note.limit": "* Nota: había demasiados problemas reportados, por lo que algunos de ellos no se incluyen en el resumen.",
"report.forum": "Para motivar futuros desarrollos, por favor deje su mensaje en el",
"report.thanks": "Gracias por usar WME Validator!",
"msg.limit.segments": "Hay demasiados segmentos.\n\nPincha 'Mostrar informe' para revisar el informe, luego\n",
"msg.limit.segments.continue": "pincha '▶' para continuar.",
"msg.limit.segments.clear": "pulsa '✘' para borrar el informe.",
"msg.pan.text": "Desplaza el mapa para validarlo",
"msg.zoomout.text": "Aleja el zoom\tpara iniciar WME Validator",
"msg.click.text": "Pincha '▶' para validar el área visible del mapa",
"msg.autopaused": "autopausado",
"msg.autopaused.text": "¡Autopausado! Pincha '▶' para continuar.",
"msg.autopaused.tip": "WME Validator automáticamente pausó al arrastrar el mapa o cambiar el tamaño de la ventana",
"msg.finished.text": "Pincha <b>'Mostrar informe'</b> para ver los problemas del mapa",
"msg.finished.tip": "Pincha el botón '✉' (Compartir) para publicar el informe en un \nforo o en un mensaje privado",
"msg.noissues.text": "¡Terminado! ¡No se encontraron problemas!",
"msg.noissues.tip": "¡Trata de deseleccionar algunas opciones de filtro o inicia WME Validator sobre otra zona del mapa!",
"msg.scanning.text": "¡Escaneando! Finalizando en ~ ${n} minutos",
"msg.scanning.text.soon": "¡Escaneando! ¡Finalizando en un minuto!",
"msg.scanning.tip": "Pincha el botón 'Pausa' para pausar o '■' para detener",
"msg.starting.text": "¡Comenzando! ¡Las capas están desactivadas para escanear más rápido!",
"msg.starting.tip": "Usa el botón 'Pausa' para pausar o el botón '■' para detener",
"msg.paused.text": "¡En pausa! Pincha el botón '▶' para continuar.",
"msg.paused.tip": "Para ver el informe pincha el botón 'Mostrar informe' (si está disponible)",
"msg.continuing.text": "¡Continuando!",
"msg.continuing.tip": "WME Validator continuará desde la ubicación en que fue pausado",
"msg.settings.text": "Pincha <b>'Atrás'</b> para retornar a la vista principal",
"msg.settings.tip": "Pincha el botón 'Restaurar valores predeterminados' para resetear todos los parámetros en un clic!",
"msg.reset.text": "Todas las opciones de filtro y configuración han sido reseteadas a sus valores por defecto",
"msg.reset.tip": "Pincha el botón 'Atrás' para retornar a la vista principal",
"msg.textarea.pack": "Por favor copia el texto abajo y luego pégalo en el nuevo archivo <b>.user.js</b>",
"msg.textarea": "Por favor copia el texto abajo y luego pégalo en tu publicación del foro o mensaje privado",
"noaccess.text": "<b>Lo sentimos,</b><br> No puedes usar WME Validator\taquí.<br>Por favor revisa <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>el hilo del foro</a><br>para más información.",
"noaccess.tip": "Por favor revisa el hilo del foro para más información!",
"tab.switch.tip.on": "Pincha para activar el resaltado",
"tab.switch.tip.off": "Pincha para desactivar el resaltado",
"tab.filter.text": "filtro",
"tab.filter.tip": "Opciones para filtrar el informe y los segmentos resaltados",
"tab.search.text": "buscar",
"tab.search.tip": "Opciones de filtro avanzadas para incluir sólo segmentos específicos",
"tab.help.text": "ayuda",
"tab.help.tip": "¿Necesitas ayuda?",
"filter.noneditables.text": "Excluir segmentos <b>no-editables</b>",
"filter.noneditables.tip": "No reportar segmentos bloqueados o \nsegmentos fuera de su área de edición",
"filter.duplicates.text": "Excluir segmentos <b>duplicados</b>",
"filter.duplicates.tip": "No mostrar el mismo segmento en diferentes \npartes del reporte\n* Nota: esta opción NO AFECTA el resaltado",
"filter.streets.text": "Excluir <b>Calles y Vías de Servicio</b>",
"filter.streets.tip": "No reportar Calles y Vías de Servicio",
"filter.other.text": "Excluir <b>otros conducibles y no-conducibles</b>",
"filter.other.tip": "No reportar Caminos de Tierra, Vías de Estacionamiento y Caminos Privados\ny no-conducibles",
"filter.notes.text": "Excluir <b>notas</b>",
"filter.notes.tip": "Reportar sólo advertencias y errores",
"search.youredits.text": "Incluir <b>sólo tus ediciones</b>",
"search.youredits.tip": "Incluir sólo los segmentos editados por ti",
"search.updatedby.text": "<b>Actualizado por:</b>",
"search.updatedby.tip": "Incluir sólo segmentos actualizados por el editor especificado\nEste campo soporta:\n - listas: yo, OtrosEditores\n - comodines: palabra*\n - negación: !yo, *\n* Nota: puedes usar 'me' para indicarte a ti mismo",
"search.updatedby.example": "Ejemplo: me",
"search.updatedsince.text": "<b>Actualizado desde:</b>",
"search.updatedsince.tip": "Incluir sólo segmentos editados desde la fecha especificada formato de fecha\nFirefox: AAAA-MM-DD",
"search.updatedsince.example": "AAAA-MM-DD",
"search.city.text": "<b>Nombre de ciudad:</b>",
"search.city.tip": "Incluir sólo segmentos con el nombre de ciudad especificado\nEste campo soporta:\n - listas: Paris, Meudon\n - comodines: Área * Mayor\n - negación: !Paris, *",
"search.city.example": "Ejemplo: !Paris, *",
"search.checks.text": "<b>Reportado como:</b>",
"search.checks.tip": "Incluir sólo segmentos reportados como específicos\nEste campo empareja:\n - severidades: errores\n - revisar nombres: Calle nueva\n - revisar IDs: 40\nEste campo soporta:\n - listas: 36, 37\n - comodines: *rotonda*\n - negación: !giros suaves*, *",
"search.checks.example": "Ejemplo: inverso*",
"help.text": " <b>Hilos de Ayuda:</b><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=666476#p666476'>F.A.Q.</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>Consulta tu duda en el foro</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=661300#p661185'>Como ajustar Validator para tu país</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=663286#p663286'>Acerca de 'Puede ser un nombre de Ciudad incorrecto'</a>",
"help.tip": "Abrir en una nueva pestaña del explorador",
"button.scan.tip": "Comenzar escaneo del área del mapa actual \n* Nota: esto puede tomar unos minutos",
"button.scan.tip.NA": "Aleja el zoom para comenzar a escanear el área del mapa actual",
"button.pause.tip": "Pausar escaneo",
"button.continue.tip": "Continuar escaneando el área del mapa",
"button.stop.tip": "Detener el escaneo y volver a la posición de inicio",
"button.clear.tip": "Borrar informe y caché de segmentos",
"button.clear.tip.red": "Hay demasiados segmentos reportados:\n 1. Pincha 'Mostrar informe' para generar informe.\n 2. Pincha este botón para borrar el informe y comenzar de nuevo.",
"button.report.text": "Mostrar informe",
"button.report.tip": "Aplicar el filtro y generar informe HTML en una nueva pestaña",
"button.BBreport.tip": "Compartir el informe en el foro Waze o en un mensaje privado",
"button.settings.tip": "Configurar ajustes",
"tab.custom.text": "personalizado",
"tab.custom.tip": "Ajustes de revisión personalizados definidos por el usuario",
"tab.settings.text": "Ajustes",
"tab.scanner.text": "escanear",
"tab.scanner.tip": "Ajustes de escaneo de mapa",
"tab.about.text": "acerca de</span>",
"tab.about.tip": "Acerca de WME Validator",
"scanner.sounds.text": "Habilitar sonidos",
"scanner.sounds.tip": "Pitidos y sonidos mientras escanea",
"scanner.sounds.NA": "Su navegador no admite AudioContext",
"scanner.highlight.text": "Resalta problemas en el mapa",
"scanner.highlight.tip": "Resalta problemas reportados en el mapa",
"scanner.slow.text": "Activa 'slow' verificaciones",
"scanner.slow.tip": "Activa análisis profundo del mapa\n* Nota: esta opción puede ralentizar el proceso de escaneo",
"scanner.ext.text": "Informa de resaltados externos",
"scanner.ext.tip": "Informa de segmentos resaltados por WME Toolbox o WME Color Highlights",
"custom.template.text": "Plantilla personalizada",
"custom.template.tip": "Plantilla para comprobaciones definidas por el usuario.\n\nPuede usar las siguientes variables expandibles:\n${country}, ${state}, ${city}, ${street},\n${country}, ${state}, ${city}, ${street},\n${altCity[index or delimeter]} Example: ${altCity[0]},\n${altStreet[index or delimeter]} Example: ${altStreet[##]},\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}, ${roundabout}, ${hasHNs},\n${drivable}, ${softTurns}, ${Uturn}, ${deadEnd},\n${segmentsA}, ${inA}, ${outB}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.example": "Ejemplo: ${street}",
"custom.regexp.text": "Personalizado <a target='_blank' href='https://developer.mozilla.org/docs/JavaScript/Guide/Regular_Expressions'>RegExp</a>",
"custom.regexp.tip": "Expresión regular de comprobación personalizada definida por el usuario para que coincida con la plantilla.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
"custom.regexp.example": "Ejemplo: !/.+/",
"about.tip": "Pincha 'actualizar' para abrir el hilo del foro en una pestaña nueva",
"button.reset.text": "Restablecer predeterminados",
"button.reset.tip": "Revertir opciones de filtro y ajustes a sus valores predeterminados",
"button.list.text": "Comprobaciones disponibles...",
"button.list.tip": "Muestra una lista de las comprobaciones disponibles en WME Validator",
"button.wizard.tip": "Crear paquete de localización",
"button.back.text": "Atrás",
"button.back.tip": "Cerrar configuración y volver a la vista principal",
"1.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
"1.title": "WME Toolbox: Rotonda que puede causar problemas",
"1.problem": "Los números de identificación de los puntos de unión de los segmentos de la rotonda no son consecutivos",
"1.solution": "Rehacer la rotonda",
"2.title": "WME Toolbox: Segmento Simple",
"2.problem": "El segmento tiene nodos de geometría innecesarios",
"2.solution": "Simplifica la geometría del segmento pasando el puntero del ratón por encima y pulsando la tecla 'd'",
"3.title": "WME Toolbox: Bloqueo nivel 2",
"3.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"4.title": "WME Toolbox: Bloqueo nivel 3",
"4.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"5.title": "WME Toolbox: Bloqueo nivel 4",
"5.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"6.title": "WME Toolbox: Bloqueo nivel 5",
"6.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"7.title": "WME Toolbox: Bloqueo nivel 6",
"7.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"8.title": "WME Toolbox: Numeros de casas",
"8.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"9.title": "WME Toolbox: Segmento con restricciones de tiempo",
"9.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
"13.title": "WME Colour Highlights: Bloqueo de editor",
"13.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"14.title": "WME Colour Highlights: Peaje / Vía de sentido único",
"14.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"15.title": "WME Colour Highlights: Editado recientemente",
"15.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"16.title": "WME Colour Highlights: Rango de vías",
"16.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"17.title": "WME Colour Highlights: Sin ciudad",
"17.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"18.title": "WME Colour Highlights: Restricción horaria / Tipo de vía resaltado",
"18.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"19.title": "WME Colour Highlights: Sin nombre",
"19.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"20.title": "WME Colour Highlights: Filtro por ciudad",
"20.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"21.title": "WME Colour Highlights: Filtro por ciudad (alt. ciudad)",
"21.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"22.title": "WME Colour Highlights: Filtro por editor",
"22.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
"23.title": "Segmento no confirmado",
"23.problem": "Cada segmento debe tener al menos el nombre del país o estado",
"23.solution": "Confirma la vía actualizando sus detalles",
"24.problemLink": "W:Corrigiendo_ciudades_\"manchadas\"",
"24.title": "Puede haber nombre incorrecto de ciudad (sólo disponible en el informe)",
"24.problem": "El segmento puede tener un nombre de ciudad incorrecto",
"24.solution": "Considera el nombre de ciudad sugerido y use este formulario para renombrar la ciudad",
"25.title": "Dirección del segmento marcada como desconocida",
"25.problem": "La dirección del segmento 'Desconocida' no impedirá enrutar por la vía",
"25.solution": "Fijar la dirección de la vía",
"27.enabled": true,
"27.problemLink": "W:Corrigiendo_ciudades_\"manchadas\"",
"27.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"27.title": "Nombre de ciudad en vía férrea",
"27.problem": "Poner nombres de ciudad en la vía férrea puede generar ciudades manchadas",
"27.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
"28.problemLink": "W:Puntos_de_Unión._Guía_de_estilo#Bifurcaciones_de_rampas",
"28.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"28.title": "Nombre de calle en una rampa bidireccional",
"28.problem": "Si la rampa no tiene nombre, el nombre del segmento siguiente se propagará hacia atrás",
"28.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar'",
"29.problemLink": "W:Crear_y_editar_rotondas#Creaci.C3.B3n_de_una_rotonda_a_partir_de_una_intersecci.C3.B3n",
"29.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"29.title": "Nombre de calle en rotonda",
"29.problem": "En Waze, no nombramos los segmentos de las rotondas",
"29.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar' y después crea un punto de interés tipo 'intersección / intercambio' para nombrar la rotonda",
"34.title": "Nombre de calle alternativo vacío",
"34.problem": "El nombre de calle alternativo está vacío",
"34.solution": "Borrar el nombre alternativo de calle vacío",
"35.title": "Segmento de vía sin terminar",
"35.problem": "Waze no enrutará desde un segmento sin terminar",
"35.solution": "Mover un poco el segmento para que el extremo sin terminar sea añadido automáticamente al punto de unión",
"36.title": "Punto de unión A innecesario (slow)",
"36.problem": "Los segmentos adyacentes al punto de unión A son idénticos",
"36.solution": "Selecciona el punto de unión A y pulsa la tecla borrar para unir los dos segmentos",
"37.title": "Punto de unión B innecesario (slow)",
"37.problem": "Los segmentos adyacentes al punto de unión B son idénticos",
"37.solution": "Selecciona el punto de unión B y pulsa la tecla borrar para unir los dos segmentos",
"38.problemLink": "W:Restricciones_horarias#En_segmentos",
"38.title": "Restricción de segmento caducada (slow)",
"38.problem": "El segmento tiene una restricción caducada",
"38.solution": "Hacer clic en 'Editar restricciones' y borrar la restricción caducada",
"39.problemLink": "W:Restricciones_horarias#En_giros",
"39.title": "Restricción de giro caducada (slow)",
"39.problem": "El segmento tiene un giro con una restricción caducada",
"39.solution": "Hacer clic en el icono de reloj cerca de la flecha amarilla y borrar la restricción caducada",
"41.title": "Conectividad inversa en punto de unión A del segmento",
"41.problem": "Hay un giro que va contra la dirección del segmento en el punto de unión A del segmento",
"41.solution": "Hacer el segmento 'bidireccional', restringir todos los giros en el punto de unión A y luego hacer el segmento 'Unidireccional (A→B)' nuevamente",
"42.title": "Conectividad inversa en punto de unión B del segmento",
"42.problem": "Hay un giro que va contra la dirección del segmento en el punto de unión B del segmento",
"42.solution": "Hacer el segmento 'bidireccional', restringir todos los giros en el punto de unión B y luego hacer el segmento 'Unidireccional (B→A)' nuevamente",
"43.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Dividir_un_segmento",
"43.title": "Auto conectividad",
"43.problem": "El segmento está conectado a si mismo",
"43.solution": "Divide el segmento en TRES partes",
"44.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"44.title": "Sin conexión de salida",
"44.problem": "El segmento no tiene ningún giro de salida permitido",
"44.solution": "Activa al menos un giro de salida desde el segmento",
"45.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"45.title": "Sin conexión de entrada",
"45.problem": "El segmento no privado no tiene ningún giro de entrada permitido",
"45.solution": "Selecciona un segmento adyacente y activa por lo menos un giro hacia el segmento",
"46.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"46.title": "Sin entrada en A (slow)",
"46.problem": "El segmento no-privado no tiene ningún giro de entrada habilitado en el punto de unión A",
"46.solution": "Selecciona un segmento adyacente y habilita al menos un giro hacia el segmento en el punto de unión A",
"47.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"47.title": "Sin entrada en B (slow)",
"47.problem": "El segmento no-privado no tiene ningún giro de entrada habilitado en el punto de unión B",
"47.solution": "Selecciona un segmento adyacente y habilita al menos un giro hacia el segmento en el punto de unión B",
"48.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
"48.title": "Segmento de rotonda bidireccional",
"48.problem": "El segmento de rotonda es bidireccional",
"48.solution": "Rehacer la rotonda",
"50.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
"50.title": "No hay conectividad en la rotonda (slow)",
"50.problem": "El segmento de la rotonda no tiene conectividad con el segmento de rotonda siguiente",
"50.solution": "Permitir un giro al segmento adyacente o rehacer la rotonda",
"57.enabled": true,
"57.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"57.title": "Nombre de ciudad en rampa con nombre",
"57.problem": "Poner el nombre de ciudad en las rampas puede afectar a los resultados de búsqueda",
"57.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
"59.enabled": true,
"59.problemLink": "W:Corrigiendo_ciudades_'manchadas'",
"59.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"59.title": "Nombre de Ciudad en Autopista",
"59.problem": "Poner nombres de ciudad en la Autopista puede generar ciudades manchadas",
"59.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
"73.enabled": true,
"73.title": "Menos de 3 caracteres de longitud en el nombre de la calle",
"73.problem": "El nombre de la calle tiene una longitud de menos de 3 caracteres",
"73.solution": "Corrige el nombre de la calle",
"74.problemLink": "W:Crear_y_editar_rotondas",
"74.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
"74.title": "Varios segmentos en el punto de unión A de la rotonda",
"74.problem": "La rotonda tiene en el punto de unión A más de un segmento conectado",
"74.solution": "Rehacer la rotonda",
"77.title": "Calle sin salida con giro en U",
"77.problem": "La calle sin salida tiene un giro en U habilitado",
"77.solution": "Deshabilitar el giro en U",
"78.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Dividir_un_segmento",
"78.title": "Segmentos con los mismos puntos de inicio y final (slow)",
"78.problem": "Dos segmentos comparten los puntos de inicio y final",
"78.solution": "Divide el segmento. También puedes borrar uno de los segmentos si son idénticos",
"79.title": "Conector para giros en U demasiado corto (slow)",
"79.problem": "La longitud del segmento es menor de 15 metros por lo que el giro en U no es posible",
"79.solution": "Aumente la longitud del segmento",
"87.problemLink": "W:Crear_y_editar_rotondas",
"87.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
"87.title": "Más de un segmento de salida en el punto de unión A de la rotonda",
"87.problem": "La rotonda tiene en el punto de unión A más de un segmento de salida conectado",
"87.solution": "Rehacer la rotonda",
"90.enabled": true,
"90.title": "Segmento de Autopista bidireccional",
"90.problem": "La mayoría de las Autopistas están separadas en dos vías de un sentido, por lo que este segmento bidireccional puede ser un error",
"90.solution": "Revisar dirección de Autopista",
"99.title": "Giro en U en la entrada de rotonda (slow)",
"99.problem": "El segmento de entrada a la rotonda tiene un giro en U habilitado",
"99.solution": "Deshabilitar el giro en U",
"101.enabled": false,
"101.title": "Zona en construcción (sólo disponible en el informe)",
"101.problem": "El segmento está marcado como zona de construcción",
"101.solution": "Si la construcción está terminada, volver a conectar el segmento y borrar el sufijo",
"102.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"102.title": "Sin salida en A (slow)",
"102.problem": "El segmento no tiene ningún giro de salida habilitado en el punto de unión A",
"102.solution": "Habilita al menos un giro de salida desde el segmento en el punto de unión A",
"103.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
"103.title": "Sin salida en B (slow)",
"103.problem": "El segmento no tiene ningún giro de salida habilitado en el punto de unión B",
"103.solution": "Habilita al menos un giro de salida desde el segmento en el punto de unión B",
"104.title": "Vía férrea usada para comentarios",
"104.problem": "El segmento de vía férrea es probablemente usado como comentario de mapa",
"104.solution": "Borrar el comentario ya que las vías férreas serán añadidas al mapa del cliente",
"107.title": "Sin conexión en punto de unión A (slow)",
"107.problem": "El punto de unión A del segmento está a menos de 5 metros de otro segmento pero no está conectado",
"107.solution": "Conectar el punto de unión A a un segmento cercano o separarlos un poco más",
"108.title": "Sin conexión en punto de unión B (slow)",
"108.problem": "El punto de unión B del segmento está a menos de 5 metros de otro segmento pero no está conectado",
"108.solution": "Conectar el punto de unión B a un segmento cercano o separarlos un poco más",
"109.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Eliminar_un_punto_de_uni.C3.B3n",
"109.title": "Segmento muy corto",
"109.problem": "El segmento tiene menos de 2 metros de longitud, así que es difícil de ver en el mapa",
"109.solution": "Aumentar la longitud, borrar el segmento, o unirlo a un segmento adyacente",
"112.title": "Más de 55 caracteres en el nombre de la Rampa",
"112.problem": "El nombre de la Rampa tiene más de 55 caracteres",
"112.solution": "Acorta el nombre de la Rampa",
"114.enabled": false,
"114.title": "No transitable conectada a transitable en el punto de unión A (slow)",
"114.problem": "El segmento no transitable tiene un punto de unión con un segmento transitable en el extremo A",
"114.solution": "Desconecta el extremo A de todos los segmentos transitables",
"115.enabled": false,
"115.title": "No transitable conectada a transitable en el punto de unión B (slow)",
"115.problem": "El segmento no transitable tiene un punto de unión con un segmento transitable en el extremo B",
"115.solution": "Desconecta el extremo B de todos los segmentos transitables",
"116.title": "Elevación fuera de rango",
"116.problem": "La elevación del segmento está fuera de rango",
"116.solution": "Corrige la elevación",
"117.enabled": false,
"117.title": "Marcado obsoleto: CONST ZN",
"117.problem": "El segmento está marcado con el sufijo obsoleto CONST ZN",
"117.solution": "Cambiar CONST ZN a (closed)",
"118.title": "Segmentos superpuestos en A (slow)",
"118.problem": "El segmento se solapa con el segmento adyacente en el punto de unión A",
"118.solution": "Separa los dos segmentos al menos 2º o elimina el nodo de geometría innecesario o borra el segmento duplicado en el punto de unión A",
"119.title": "Segmentos superpuestos en B (slow)",
"119.problem": "El segmento se solapa con el segmento adyacente en el punto de unión B",
"119.solution": "Separa los dos segmentos al menos 2º o elimina el nodo de geometría innecesario o borra el segmento duplicado en el punto de unión B",
"120.title": "Giro demasiado cerrado en A (slow)",
"120.problem": "El segmento tiene un giro demasiado cerrado en el punto de unión A",
"120.solution": "Desactiva el giro cerrado en el punto de unión A o considera separar los segmentos hasta un ángulo de 30°",
"121.title": "Giro demasiado cerrado en B (slow)",
"121.problem": "El segmento tiene un giro demasiado cerrado en el punto de unión B",
"121.solution": "Desactiva el giro cerrado en el punto de unión B o considera separar los segmentos hasta un ángulo de 30°",
"128.title": "Comprobación personalizada por el usuario 1",
"128.problem": "Alguna de las propiedades del segmento coinciden con la expresión regular definida por el usuario (ver Ajustes→Personalización)",
"128.solution": "Resolver el problema",
"129.title": "Comprobación personalizada por el usuario 2",
"129.problem": "Alguna de las propiedades del segmento coinciden con la expresión regular definida por el usuario (ver Ajustes→Personalización)",
"129.solution": "Resolver el problema",
"130.enabled": true,
"130.severity": 'N',
"130.title": "Nivel de bloqueo de Autopista incorrecto",
"130.problem": "El segmento de Autopista no está bloqueado a nivel 4",
"130.problemLink": "W:Dudas_frecuentes_editando_mapas#.C2.BFDebo_.22bloquear.22_mis_ediciones.3F",
"130.solution": "Bloquear el segmento de Autopista a nivel 4",
"130.params": {
    "titleEN": "No lock on Freeway",
    "problemEN": "The Freeway segment should be locked to Lvl 4",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}",
    "regexp": "/^3:[^4]/",
},
"131.enabled": true,
"131.severity": 'N',
"131.title": "No lock on Major Highway",
"131.problem": "The Major Highway segment should be locked to Lvl 3",
"131.problemLink": "W:Dudas_frecuentes_editando_mapas#.C2.BFDebo_.22bloquear.22_mis_ediciones.3F",
"131.solution": "Lock the segment",
"131.params": {
    "titleEN": "No lock on Major Highway",
    "problemEN": "The Major Highway segment should be locked to Lvl 3",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}:${street}",
    "regexp": "/^6:[^3]:N\-/",
},
"133.enabled": true,
"133.severity": 'N',
"133.title": "No lock on Ramp",
"133.problem": "The Ramp segment should be locked to Lvl 3",
"133.problemLink": "W:Dudas_frecuentes_editando_mapas#.C2.BFDebo_.22bloquear.22_mis_ediciones.3F",
"133.solution": "Lock the segment",
"133.params": {
    "titleEN": "No lock on Ramp",
    "problemEN": "The Ramp segment should be locked to Lvl 3",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}",
    "regexp": "/^4:[^3]/",
},
//      "150.enabled": true,
"150.title": "Nivel de bloqueo de Autopista incorrecto",
"150.problem": "El segmento de Autopista no está bloqueado a nivel ${n}",
"150.solution": "Bloquear el segmento de Autopista a nivel ${n}",
"169.title": "Calle nombrada incorrectamente",
"169.problem": "La calle tiene el nombre incorrecto, usando caracteres o palabras ilegales",
"169.solution": "Renombre la calle de acuerdo a los criterios establecidos",
"170.enabled": true,
"170.title": "Nombre de calle comienza con minúscula",
"170.problem": "El nombre de la calle comienza con minúscula",
"170.solution": "Escribir en mayúscula la primera letra del nombre",
"172.title": "Nombre de calle con espacios innecesarios",
"172.problem": "Espacio en blanco inicial/final o doble en el nombre de la calle",
"172.solution": "Borrar los espacios innecesarios del nombre de Calle",
"173.enabled": false,
"173.title": "Nombre de segmento sin espacio antes o después de una abreviación",
"173.problem": "Sin espacio antes ('1943r.') o después ('St.Jan') de una abreviación en el nombre del segmento",
"173.solution": "Agregar un espacio antes/después de la abreviación",
"175.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
"175.title": "Nombre del segmento sólo con espacios",
"175.problem": "El nombre del segmento sólo tiene espacios en blanco en el nombre",
"175.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar' o escribe un nombre de calle correcto",
"190.title": "Nombre de ciudad con minúscula",
"190.problem": "El nombre de la ciudad comienza con minúscula",
"190.solution": "Utiliza este formulario para renombrar la ciudad",
"192.title": "Nombre de Ciudad con espacios innecesarios",
"192.problem": "Espacio en blanco inicial/final o doble en el nombre de la ciudad",
"192.solution": "Use este formulario para renombrar la Ciudad",
"193.enabled": false,
"193.title": "Nombre de Ciudad sin espacio delante o atrás de una abreviación",
"193.problem": "Sin espacio antes ('1943r.') o después ('St.Jean') de una abreviación en el nombre de la ciudad",
"193.solution": "Use este formulario para renombrar la Ciudad",
"200.problemLink": "W:Giros_implícitos_y_explícitos",
"200.solutionLink": "W:Giros_implícitos_y_explícitos#Mejores_pr.C3.A1cticas",
"200.title": "Unión A: Giro suave (implícito) en segmento",
"200.problem": "El segmento tiene un giro no confirmado",
"200.solution": "Haz clic en el giro indicado con un signo de interrogación color púrpura para confirmarlo. Nota: es posible que debas hacer el segmento bidireccional para ver todos los giros",
"201.problemLink": "W:Giros_implícitos_y_explícitos",
"201.solutionLink": "W:Giros_implícitos_y_explícitos#Mejores_pr.C3.A1cticas",
"201.title": "Unión A: Giro suave (implícito) en segmento principal",
"201.problem": "El segmento principal tiene un giro no confirmado",
"201.solution": "Haz clic en el giro indicado con un signo de interrogación color púrpura para confirmarlo. Nota: es posible que debas hacer el segmento bidireccional para ver todos los giros"
