".country": [
             "France",
             "French Guiana",
             "New Caledonia",
             "Reunion"
             ],
".author": "arbaot and ClementH44",
".updated": "2014-03-27",
".lng": "FR",

"err.regexp": "Erreur d'interprétation pour la vérification #${n}:",
"props.disabled": "WME Validator est désactivé",
"props.limit.title": "Trop de problèmes signalés",
"props.limit.problem": "Il y a trop de problèmes signalés, de sorte que certains d'entre eux pourraient ne pas être affichés",
"props.limit.solution": "Désélectionnez le segment et arrêtez le scan. Ensuite, cliquez sur le bouton rouge «✘» (Effacer le rapport)",
"props.reports": "Rapports",
"props.noneditable": "Vous ne pouvez éditer ce segment",
"report.list.andUp": "et jusqu'à",
"report.list.severity": "Gravité :",
"report.list.reportOnly": "seulement dans le rapport",
"report.list.forEditors": "Pour le niveau d'édition :",
"report.list.forCountries": "Pour les pays :",
"report.list.forStates": "Pour les états :",
"report.list.forCities": "Pour les villes :",
"report.list.params": "Paramètres à configurer dans le pack de localisation :",
"report.list.enabled": "${n} vérifications sont activés pour",
"report.list.disabled": "${n} vérifications sont désactivés pour",
"report.list.total": "Il y a ${n} points de contôles activés",
"report.list.title": "Liste complète des vérifications pour",
"report.list.see": "Voir",
"report.list.checks": "Paramètres->À propos->Les vérifications",
"report.list.fallback": "Règles de regroupement géographique :",
"report.and": "et",
"report.segments": "Nombre total de segments vérifiés :",
"report.customs": "Les vérifications personnalisés adaptés (vert/bleu):",
"report.reported": "Signalement",
"report.errors": "d'erreurs",
"report.warnings": "d'avertissements",
"report.notes": "de remarques",
"report.contents": "Contenus :",
"report.summary": "Récapitulatif",
"report.title": "Rapport de WME Validator",
"report.share": "à partager",
"report.generated.by": "généré par",
"report.generated.on": "le",
"report.source": "Source du rapport :",
"report.filter.duplicate": "les segments doublons",
"report.filter.streets": "Rue et Routes de service",
"report.filter.other": "Autres",
"report.filter.noneditable": "segments non modifiables",
"report.filter.notes": "notes",
"report.filter.title": "Filtre :",
"report.filter.excluded": "sont exclues de ce rapport.",
"report.search.updated.by": "mis à jour par",
"report.search.updated.since": "mis à jour depuis",
"report.search.city": "à partir de",
"report.search.reported": "signalé comme",
"report.search.title": "Rechercher:",
"report.search.only": "seulement les segments",
"report.search.included": "sont inclus dans le rapport.",
"report.beta.warning": "avertissement WME Beta !",
"report.beta.text": "Ce rapport est généré pour WME beta avec des permaliens en beta.",
"report.beta.share": "Ne pas partager ces permaliens !",
"report.size.warning": "<b>Avertissement !</b><br>Le rapport est trop long de ${n} charactères de sorte qu'<b>il ne passe pas</b> dans un seul forum ou message privé.\n<br>Ajoutez <b>des filtres</b> pour réduire la taille du rapport.",
"report.note.limit": "* Remarque: il y avait trop de problèmes signalés, de sorte que certains d'entre eux ne sont pas pris en compte dans le récapitulatif.",
"report.forum": "Pour soutenir le développement, merci de laisser un commentaire sur",
"report.thanks": "Merci d'utiliser WME Validator !",
"msg.limit.segments": "Il y a trop de segments.\n\nCliquez sur 'Le rapport' pour examiner le rapport, ensuite\n",
"msg.limit.segments.continue": "cliquez sur '▶' pour continuer.",
"msg.pan.text": "Déplacez-vous sur pour valider la carte",
"msg.zoomout.text": "Effectuer un zoom arrière pour démarrer WME Validator",
"msg.click.text": "Cliquez sur '▶' pour valider la zone visible de la carte",
"msg.autopaused": "Pause automatique",
"msg.autopaused.text": "Pause automatique ! Cliquez sur '▶' pour continuer.",
"msg.autopaused.tip": "WME Validator est automatiquement suspendu si la carte est déplacée ou si la taille de la fenêtre change",
"msg.finished.text": "Cliquez sur <b>'Le rapport'</b> pour examiner les problèmes de carte",
"msg.finished.tip": "Cliquez sur '✉' (Partager) pour poster un rapport sur un\nforum ou par message privé",
"msg.noissues.text": "Terminé ! Aucun problème trouvé !",
"msg.noissues.tip": "Essayez de désactiver quelques filtres ou démarrez WME Validator sur une autre zone de la carte !",
"msg.scanning.text": "Scan en cours ! Terminé dans ~ ${n} min",
"msg.scanning.text.soon": "Scan en cours ! Terminé dans une minute !",
"msg.scanning.tip": "Cliquez sur 'Pause' pour suspendre ou '■' pour stopper",
"msg.starting.text": "Lancement ! Les calques ne peuvent scanner plus vite !",
"msg.starting.tip": "Utilisez le bouton 'Pause' pour suspendre ou le bouton '■' pour stopper",
"msg.paused.text": "En pause ! Cliquez sur '▶' pour continuer.",
"msg.paused.tip": "Pour voirla raport, cliquez sur 'Le rapport' (si disponible)",
"msg.continuing.text": "En cours !",
"msg.continuing.tip": "WME Validator continuera à l'endroit où il a été suspendu",
"msg.settings.text": "Cliquez sur <b>'Retour'</b> pour retourner sur la vue principale",
"msg.settings.tip": "Cliquez sur 'Par défaut' pour réinitialiser tous les réglages en un clic !",
"msg.reset.text": "Toutes les options de filtrage et les paramètres ont été remis à leurs valeurs par défaut",
"msg.reset.tip": "Cliquez sur 'Retour' pour retourner sur la vue principale",
"msg.textarea.pack": "Merci de copier le texte ci-dessous et de le coller dans un nouveau fichier <b>.user.js</b>",
"msg.textarea": "Merci de copier le texte ci-dessous et de le coller dans votre forum pour par message privé",
"noaccess.text": "<b>Désolé,</b><br>Vous ne pouvez utiliser WME Validator ici.<br>Merci de visiter (en anglais) <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>ce forum</a><br>pour plus d'informations.",
"noaccess.tip": "Merci de visiter le forum du programme pour plus d'informations !",
"tab.switch.tip.on": "Cliquez pour activer la surbrillance",
"tab.switch.tip.off": "Cliquez pour désactiver la surbrillance",
"tab.filter.text": "filtre",
"tab.filter.tip": "Options pour filtrer le rapport et les segments à mettre en évidence",
"tab.search.text": "cherche",
"tab.search.tip": "Options avancées de filtrage pour inclure uniquement des segments spécifiques",
"tab.help.text": "aide",
"tab.help.tip": "Besoins d'aide ?",
"filter.noneditables.text": "Exclure les segments <b>non modifiables</b>",
"filter.noneditables.tip": "Ne pas éxaminer les segments verrouillés ou en dehors de vos zones modifiables",
"filter.duplicates.text": "Exclure les segments <b>doublons</b>",
"filter.duplicates.tip": "Ne pas éxaminer le même segment dans différentes\nparties du rapport\n* Remarque: cette option n'affecte pas la surbrillance",
"filter.streets.text": "Exclure les <b>Rues et Routes de service</b>",
"filter.streets.tip": "Ne pas éxaminer les rues et routes/chemins de service",
"filter.other.text": "Exclure les <b>autres rues carrossables</b>",
"filter.other.tip": "Ne pas éxaminer les chemins de terres, les parkings, les routes privées\net les segments non carrossables",
"filter.notes.text": "Exclure les <b>remarques</b>",
"filter.notes.tip": "Rapporte uniquement les avertissements et les erreurs",
"search.youredits.text": "Inclure <b>uniquement vos modifications</b>",
"search.youredits.tip": "Inclure uniquement les segments modifiés par vous",
"search.updatedby.text": "<b>Mis à jour par:</b>",
"search.updatedby.tip": "Inclure uniquement les segments mis à jour par un éditeur déterminé\nCe champ prend en charge:\n - les listes: me, otherEditor\n - les métacaractères: world*\n - la négation: !me, *\n* Remarque: vous pouvez utiliser 'me' pour vous désigner",
"search.updatedby.example": "Example: me",
"search.updatedsince.text": "<b>Mis à jour depuis:</b>",
"search.updatedsince.tip": "Inclure uniquement les segments modifiés depuis la date spécifiée\nFormat de date Firefox: AAAA-MM-JJ",
"search.updatedsince.example": "AAAA-MM-JJ",
"search.city.text": "<b>Nom de Ville:</b>",
"search.city.tip": "Inclure uniquement les segments d'une ville spécifiée\nCe champ prend en charge:\n - les listes: Paris, Meudon\n - les métacaractères (wildcards): Greater * Area\n - la négaction: !Paris, *",
"search.city.example": "Example: !Paris, *",
"search.checks.text": "<b>Signalé comme:</b>",
"search.checks.tip": "Inclure uniquement les segments \nCe champ correspond:\n - aux gravités: erreur\n - aux noms: Nouvelle route\n - aux identifiants (IDs): 40\nCe champ prend en charge:\n - les listes: 36, 37\n - les métacaractères (wildcards): *roundabout*\n - la négation: !unconfirmed*, *",
"search.checks.example": "Example: reverse*",
"help.text": "<b>Rubriques d'aide (en anglais):</b><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476'>F.A.Q.</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>Posez votre question sur le forum</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185'>Comment ajuster Validator à votre pays</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=663286#p663286'>À propos de 'Might be Incorrect City Name'</a>",
"help.tip": "S'ouvre dans un nouvel onglet du navigateur",
"button.scan.tip": "Commencer à scanner la zone actuelle de la carte\n* Remarque: cela peut prendre quelques minutes",
"button.scan.tip.NA": "Dézoomez pour commencer à scanner la zone actuelle de la carte",
"button.pause.tip": "Scan en pause",
"button.continue.tip": "Continuer à scanner la zone de la carte",
"button.stop.tip": "Arrêter le scan et retourner à la position de départ",
"button.clear.tip": "Effacer la mémoire cache des rapports et segments",
"button.clear.tip.red": "Il y a trop de segments signalés:\n 1. Cliquez sur 'Le rapport' pour générer le rapport.\n 2. Cliquez sur ce bouton pour effacer le rapport et recommencer.",
"button.report.text": "Le rapport",
"button.report.tip": "Appliquer le filtre et générer un rapport HTML dans un nouvel onglet.",
"button.BBreport.tip": "Partagez le rapport sur le forum Waze ou dans un message privé.",
"button.settings.tip": "Configurer les paramètres",
"tab.custom.text": "perso",
"tab.custom.tip": "Paramètres de vérification personnalisés définis par l'utilisateur",
"tab.settings.text": "Params",
"tab.scanner.text": "scan",
"tab.scanner.tip": "Paramètres du scan de la carte",
"tab.about.text": "à propos</span>",
"tab.about.tip": "À propos de WME Validator",
"scanner.sounds.text": "Activer les sons",
"scanner.sounds.tip": "Joue un \'bip\' pendant le scan",
"scanner.sounds.NA": "Votre navigateur ne supporte pas AudioContext",
"scanner.highlight.text": "Mettre en surbrillance sur la carte",
"scanner.highlight.tip": "Mettre en surbrillance les problèmes repérés sur la carte",
"scanner.slow.text": "Activer le mode 'lent'",
"scanner.slow.tip": "Permet un scan plus poussé et précis de la carte\n* Remarque: cette option peut ralentir le processus de scan",
"scanner.ext.text": "Signaler des surbrillances externes",
"scanner.ext.tip": "Signaler des segments mis en évidence par WME Toolbox ou WME Color Highlights",
"custom.template.text": "Modèle perso",
"custom.template.tip": "Modèle de contrôle personnalisé définis par l'utilisateur.\n\nVous pouvez utiliser les variables suivantes:\n${country}, ${state}, ${city}, ${street},"
+ "\n${altCity[index or delimeter]} Example: ${altCity[0]},"
+ "\n${altStreet[index or delimeter]} Example: ${altStreet[##]},"
+ "\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}, ${roundabout}, ${hasHNs},\n${drivable}, ${softTurns}, ${Uturn}, ${deadEnd},\n${segmentsA}, ${inA}, ${outB}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.example": "Example: ${street}",
"custom.regexp.text": "<a target='_blank' href='https://developer.mozilla.org/docs/JavaScript/Guide/Regular_Expressions'>RegExp</a> perso",
"custom.regexp.tip": "Modèle de contrôle personnalisé définis par l'utilisateur (en utilisant le Regular Expressions).\n\nInsensible à la casse: /regexp/i\nNegation (ne fonctionne pas): !/regexp/\nInformation en mode debug des log sur la console: D/regexp/",
"custom.regexp.example": "Example: !/.+/",
"about.tip": "Ouvre le lien dans un nouvel onglet",
"button.reset.text": "Par défaut",
"button.reset.tip": "Rétablir les options de filtrage et les paramètres par défaut",
"button.list.text": "Les vérifications...",
"button.list.tip": "Montre une liste des vérifications possibles dans WME Validator",
"button.wizard.tip": "Créer un pack géographique",
"button.back.text": "Ret.",
"button.back.tip": "Fermer les paramètres et revenir à l'ecran principal",
"1.solutionLink": "W:Tout_sur_les_ronds-points",
"1.title": "WME Toolbox: Rond-point pouvant causer des problèmes",
"1.problem": "Les ID des segments du rond-point ne sont pas consécutif",
"1.solution": "Refaire le rond-point",
"2.title": "WME Toolbox: Simple segment (une voie)",
"2.problem": "Ce segments a des nœuds de géométrie inutile",
"2.solution": "Simplifier le tracé du segment sélectionné en survolant les nœuds en trop en appuyant sur le 'd' du clavier",
"3.title": "WME Toolbox: Verrouillage de niveau 2",
"3.problem": "Segment surligné par WME Toolbox. Pas un problème",
"4.title": "WME Toolbox: Verrouillage de niveau 3",
"4.problem": "Segment surligné par WME Toolbox. Pas un problème",
"5.title": "WME Toolbox: Verrouillage de niveau 4",
"5.problem": "Segment surligné par WME Toolbox. Pas un problème",
"6.title": "WME Toolbox: Verrouillage de niveau 5",
"6.problem": "Segment surligné par WME Toolbox. Pas un problème",
"7.title": "WME Toolbox: Verrouillage de niveau 6",
"7.problem": "Segment surligné par WME Toolbox. Pas un problème",
"8.title": "WME Toolbox: Numéros de maison",
"8.problem": "Segment surligné par WME Toolbox. Pas un problème",
"9.title": "WME Toolbox: Segment avec une restriction programmée",
"9.problem": "Segment surligné par WME Toolbox. Pas un problème",
"13.title": "WME Color Highlights: Verrouillage de l'éditeur",
"13.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"14.title": "WME Color Highlights: Péage / Route à sens unique",
"14.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"15.title": "WME Color Highlights: Récemment modifié",
"15.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"16.title": "WME Color Highlights: Rang de la route",
"16.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"17.title": "WME Color Highlights: Pas de ville",
"17.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"18.title": "WME Color Highlights: Restriction programmée / Type de route mis en évidence",
"18.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"19.title": "WME Color Highlights: Pas de nom",
"19.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"20.title": "WME Color Highlights: Filtrer par ville",
"20.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"21.title": "WME Color Highlights: Filtrer par ville (ville alt.)",
"21.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"22.title": "WME Color Highlights: Filtrer par éditeur",
"22.problem": "Segment surligné par WME Color Highlights. Pas un problème",
"23.problemLink": "W:Nommage_France#R.C3.A8gles_de_nommage",
"23.solutionLink": "W:Nommage_France",
"23.title": "Route non confirmée",
"23.problem": "Création de segment incomplète ville et nom de rue non renseigné",
"23.solution": "Terminer la création en complétant les propriétés",
"24.problemLink": "W:Comment_nommer_les_routes_et_les_villes#Nommage_des_villes_et_villages",
"24.solutionLink": "F:t=29403",
"24.title": "Nom de ville peut-être erroné (uniquement disponible dans le rapport)",
"24.problem": "Le nom de la ville est peut-être incorrecte",
"24.solution": "Comparer le nom avec celui proposé et éventuellement signaler le problème sur le forum",
"25.title": "Direction inconnue de la route carrossable",
"25.problem": "Un sens de circulation 'Inconnu' n'empêchera Waze de faire emprunter le segment",
"25.solution": "Régler le sens de circulation du segment",
"27.enabled": true,
"27.title": "Nom de ville sur une voie ferrée",
"27.problem": "Un nom de ville sur les segment voie ferré provoque des incohérence des polygones Ville",
"27.solution": "Régler le nom de ville à 'Sans' ou signaler le problème sur le Forum ",
"28.problemLink": "W:Guide_des_intersections#Noms_3",
"28.title": "Nom de rue sur une rampe",
"28.problem": "Une rampe sans nom 'hérite' du nom du segment suivant",
"28.solution": "Régler le nom du segment à 'Sans'",
"29.problemLink": "W:Tout_sur_les_ronds-points#A_retenir",
"29.solutionLink": "W:Tout_sur_les_ronds-points",
"29.title": "Nom de rue sur rond-point",
"29.problem": "Dans Waze pas de nom de rue sur les rond-point",
"29.solution": "Régler le nom des segment du RP à 'Sans' et créer un POI Jonction/ échangeur avec le nom du RP",
"34.title": "Nom de rue alternatif vide",
"34.problem": "Le nom de rue alternatif vide",
"34.solution": "Supprimer le nom alternatif",
"35.title": "Route carrossable non terminé",
"35.problem": "Waze ne propose pas de guidage vers/dans les segment non terminés",
"35.solution": "Déplacer légèrement l'extrémité libre du segment pour afin que le nœuds de terminaison soit ajouté",
"36.title": "Noeud A: inutil (mode lent)",
"36.problem": "Les segments de part et d'autres du nœud A ont les mêmes propriétés",
"36.solution": "Sélectionner le nœud A et appuyer sur Suppr pour fusionner les 2 segments",
"37.title": "Noeud B: inutil (mode lent)",
"37.problem": "Les segments de part et d'autres du nœud B ont les mêmes propriétés",
"37.solution": "Sélectionner le nœud B et appuyer sur Suppr pour fusionner les 2 segments",
"38.problemLink": "W:Les_fermetures_programmées#Segments",
"38.title": "Fermetures programmées périmées (mode lent)",
"38.problem": "Il y a des fermetures programmées périmées sur ce segment",
"38.solution": "Cliquer 'Modifier les restrictions' et supprimer les restrictions périmées",
"39.problemLink": "W:Les_fermetures_programmées#Restriction_de_tourner",
"39.title": "Restrictions de tourner périmés (mode lent)",
"39.problem": "Il y a des restrictions de tourner périmées sur ce nœud de jonction",
"39.solution": "Cliquer l'icône horloge accolée à la flèche jaune et supprimer les restrictions périmées",
"41.title": "Noeud A: Autorisation en sens interdit",
"41.problem": "Au nœud A il y a une autorisation de tourner qui va à l'encontre du sens unique",
"41.solution": "Passer le segment à double sens, corriger la flèche au nœud A puis repasser en sens unique",
"42.title": "Noeud B: Autorisation en sens interdit",
"42.problem": "Au nœud B il y a une autorisation de tourner qui va à l'encontre du sens unique",
"42.solution": "Passer le segment à double sens, corriger la flèche au nœud B puis repasser en sens unique",
"43.title": "Connecté à lui-même",
"43.problem": "Le segment est connecté à lui même",
"43.solution": "Couper le segment en deux",
"44.title": "Pas ne connexion sortante",
"44.problem": "Le segment carrossable n'a pas de connexion sortante",
"44.solution": "Activer au moins une connexion sortante = une flèche verte",
"45.title": "Pas de connexion entrante",
"45.problem": "Le segment carrossable (non privé) n'a pas de connexion entrante",
"45.solution": "Sélectionner un segment adjacent et autoriser au moins un accès (flèche rouge → verte)",
"46.title": "Noeud A: Pas de connexion entrante pour le segment (mode lent)",
"46.problem": "Le segment carrossable (non privé) n'a pas de connexion entrante au nœud A",
"46.solution": "Sélectionner un segment adjacent et autoriser au moins un accès (flèche rouge → verte) au nœud A",
"47.title": "Noeud B: Pas de connexion entrante pour le segment (mode lent)",
"47.problem": "Le segment carrossable (non privé) n'a pas de connexion entrante au nœud B",
"47.solution": "Sélectionner un segment adjacent et autoriser au moins un accès (flèche rouge → verte) au nœud B",
"48.solutionLink": "W:Tout_sur_les_ronds-points#Remplacer_.2F_Editer_un_rond-point",
"48.title": "Segment de rond-point à double sens",
"48.problem": "Segment de rond-point à double sens de circulation",
"48.solution": "Refaire le rond-point",
"50.solutionLink": "W:Tout_sur_les_ronds-points#A_retenir",
"50.title": "Pas de connectivité sur le rond-point (mode lent)",
"50.problem": "Le segment du rond-point n'a pas de connectivité avec le segment adjacent",
"50.solution": "Autoriser un virage vers le segment adjacent = Corriger la flèche rouge",
"57.enabled": true,
"57.title": "Nom de ville sur une rampe",
"57.problem": "Un Nom de ville sur une rampe peu affecter la recherche dans Waze",
"57.solution": "Cocher la case 'Sans' pour ville",
"59.enabled": true,
"59.title": "Nom de ville sur Freeway",
"59.problem": "Un nom de ville sur les segment Freeway provoque des incohérence des polygones Ville",
"59.solution": "Régler le nom de ville à 'Sans' ou signaler le problème sur le Forum",
"74.problemLink": "W:Tout_sur_les_ronds-points#A_retenir",
"74.solutionLink": "W:Tout_sur_les_ronds-points#Remplacer_.2F_Editer_un_rond-point",
"74.title": "Noeud A: Plusieurs segments connectés",
"74.problem": "La jonction A du rond-point est connectée à plusieurs segments",
"74.solution": "Refaire le rond-point",
"77.title": "Demi-tour autorisé",
"77.problem": "L'impasse carrossable à un demi-tour autorisé à son extrémité",
"77.solution": "Éventuellement Interdire le demi-tour",
"78.title": "Mêmes extrémités des segments carrossables (mode lent)",
"78.problem": "Deux segments carrossables partagent les deux mêmes extrémités",
"78.solution": "Diviser le segment. Vous pouvez également supprimer l'un des segments si ils sont identiques",
"79.title": "Demi-tour trop court (mode lent)",
"79.problem": "Le segment fait moins de 15m si nécessaire Waze ne proposera pas de demi-tour",
"79.solution": "Agrandisseur le segment à 15m mini (si le demi-tour est autorisé)",
"87.problemLink": "W:Tout_sur_les_ronds-points#A_retenir",
"87.solutionLink": "W:Tout_sur_les_ronds-points#Remplacer_.2F_Editer_un_rond-point",
"87.title": "Noeud A: Plusieurs sorties au rond-point",
"87.problem": "La jonction A du rond-point est connectée à plusieurs segments sortant",
"87.solution": "Refaire le rond-point",
"99.title": "Demi-tour à l'entrée du rond-point (mode lent)",
"99.problem": "Le segment d'entrée du rond-point à un demi-tour autorisé",
"99.solution": "Désactiver le demi-tour",
"101.title": "Route fermée (seulement disponible dans le rapport)",
"101.problem": "Le segment est marqué comme étant fermé",
"101.solution": "Si la construction est terminée, restaurez la connectivité du segment et supprimez le suffixe",
"101.params": {
    "regexp": "/(^|\\b)travaux(\\b|$)/i",
},
"102.title": "Noeud A: Pas de connexion sortante (mode lent)",
"102.problem": "Le segment carrossable n'a pas de connexion sortante au nœud A",
"102.solution": "Activer au moins une connexion sortante = une flèche verte au nœud A",
"103.title": "Noeud B: Pas de connexion sortante (mode lent)",
"103.problem": "Le segment carrossable n'a pas de connexion sortante au nœud B",
"103.solution": "Activer au moins une connexion sortante = une flèche verte au nœud B",
"104.title": "Voie ferré utilisée pour des commentaires",
"104.problem": "Le segment de voie ferré est probablement utilisé pour mettre un commentaire",
"104.solution": "Supprimez le commentaire car les voies ferrée sont affichées pour le client",
"107.title": "Noeud A: Pas de connexion (mode lent)",
"107.problem": "Le noeud A du segment carrossable est à moins de 5m d'un autre secteur carrossable mais n'y est pas connecté",
"107.solution": "Connectez le noeud A à un segment à proximité ou le déplacer un peu plus loin",
"108.title": "Noeud B: pas de connexion (mode lent)",
"108.problem": "Le noeud B du segment carrossable est à moins de 5m d'un autre secteur carrossable mais n'y est pas connecté",
"108.solution": "Connectez le noeud B à un segment à proximité ou le déplacer un peu plus loin",
"109.title": "Segment trop court",
"109.problem": "Le segment carrossables non-terminal est de moins de 2m de long, il est difficile de le voir sur la carte",
"109.solution": "Augmentez sa taille, supprimez le ou connectez le à un segment adjacent",
"112.title": "Plus de ${n} lettres en trop pour le nom de la rampe",
"112.problem": "Le nom de la rampe est trop long",
"112.solution": "Renommez de façon plus courte le nom de la rampe",
"114.title": "Noeud A: non carrossable connecté à un carrossable (mode lent)",
"114.problem": "Le segment non carrossable a une jonction avec un segment carrossable au noeud A",
"114.solution": "Déconnectez le noeud A de tous les segments carrossables",
"115.title": "Noeud B: non carrossable connecté à un carrossable (mode lent)",
"115.problem": "Le segment non carrossable a une jonction avec un segment carrossable au noeud B",
"115.solution": "Déconnectez le noeud B de tous les segments carrossables",
"116.title": "Élévation hors de portée",
"116.problem": "L'élévation est en dehors des limites habituelle",
"116.solution": "Corrigez l'élévation",
"117.title": "Obsolete CONST ZN marker",
"117.problem": "The segment is marked with obsolete CONST ZN suffix",
"117.solution": "Change CONST ZN to (closed)",
"118.title": "Noeud A: Chevauchement des segments (mode lent)",
"118.problem": "Le segment se chevauche avec le segment adjacent au noeud A",
"118.solution": "Divisez les segments à 2° ou supprimez le point de la géométrie inutile ou supprimez le segment double au noeud A",
"119.title": "Noeud B: Chevauchement des segments (mode lent)",
"119.problem": "Le segment se chevauche avec le segment adjacent au noeud B",
"119.solution": "Divisez les segments à 2° ou supprimez le point de la géométrie inutile ou supprimez le segment double au noeud B",
"120.title": "Noeud A: Virage trop fort (mode lent)",
"120.problem": "Le segment carrossable a un virage très fort au noeud A",
"120.solution": "Désactiver le virage au noeud A ou écarter les segments à 30°",
"121.title": "Noeud B: Virage trop fort (mode lent)",
"121.problem": "Le segment carrossable a un virage très fort au noeud B",
"121.solution": "Désactiver le virage au noeud A ou écarter les segments à 30°",
"128.title": "Vérification personnalisée définie par l'utilisateur (vert)",
"128.problem": "Certaines des propriétés du segment sont à l'encontre de la Regular Expression définie par l'utilisateur (voir Paramètres→Personnaliser)",
"128.solution": "Résoudre le problème",
"129.title": "Vérification personnalisée définie par l'utilisateur (bleu)",
"129.problem": "Certaines des propriétés du segment sont à l'encontre de la Regular Expression définie par l'utilisateur (voir Paramètres→Personnaliser)",
"129.solution": "Résoudre le problème",
"163.enabled": true,
"163.title": "'Vers' dans le nom de la rue",
"163.problem": "Nom de rue contenant 'vers'",
"163.solution": "Renommer le segment selon les règles du wiki ou signaler sur le forum",
"163.solutionLink": "W:Nommage_France#Nommage_des_entr.C3.A9es.2C_sorties_et_des_embranchements_d.27autoroutes",
"163.params": {
    "titleEN": "'Vers' in Ramp name",
    "problemEN": "The Ramp name contains word 'vers'",
    "solutionEN": "Rename the Ramp in accordance with the guidelines",
    "regexp": "/(^|\\b)vers\\b/i",
},
"170.enabled": true,
"170.solutionLink": "W:Nommage_France#R.C3.A8gles_de_nommage",
"170.title": "Majuscule dans le nom de rue",
"170.problem": "Le nom de la rue commence par une miniscule",
"170.solution": "Passer la première lettre en majuscule",

"171.enabled": true,
"171.title": "Abréviation dans le nom de rue",
"171.problem": "Abréviation indésirable dans le nom de rue",
"171.solution": "Écrire le mot abréger en toute lettre",
"171.params": {
    "regexp": "/((^| )([Ss]t-|[Ss]te-))|((^| )([Ss]t|[Ss]te|[Mm]al(?! Assis)|[Gg]al|[Aa]v|[Bb]lvd|[Ii]mp|[Pp]l|[Ss]q|[Aa]ll|[Bb][Dd])($| ))|((^| )(?!(Z\\.I|Z\\.A|Z\\.A\\.C|C\\.C|S\\.N\\.C\\.F|R\\.E\\.R)\\.)[^ ]+\\.)/",
},
"172.title": "Nom de rue avec des espaces inutiles",
"172.problem": "Double espace dans le nom de rue",
"172.problemLink": "W:Comment_nommer_les_routes_et_les_villes",
"172.solution": "Supprimer les espaces inutiles",
"173.enabled": false,
"173.title": "Nom de rue sans espace avant ou après une abrévation",
"173.problem": "Pas d'espace avant ('1943r.') ou après ('st.Jan') une abrévation dans le nom de rue",
"173.solution": "Ajouter un espace avant/après l'abrévation",

"174.enabled": true,
"174.title": "Mauvais orthographe",
"174.problem": "Mauvais orthographe qui provoque une mauvaise prononciation",
"174.solution": "Corriger l'orthographe (É = Alt-144 etc)",
"174.solutionLink": "W:Nommage_France#R.C3.A8gles_de_nommage",
"174.params": {
    "regexp": "/(^|\\b)(allee|acces|chateau|ecole|egalit[eé]|[eé]galite|eglise|etang|gen[eé]ral|g[eé]neral|hotel|hopital|marechal|president|republique|ocean|ev[eê]ch[eé]|[eé]vech[eé]|[eé]v[eê]che|periphérique|elodie|etienne|eric|emile|emilie|edouard|elisabeth)/i",
},
"175.title": "Nom de rue avec uniquement des espaces",
"175.problem": "Le nom de la rue n'a que des espaces",
"175.solution": "Dans les propriétés de l'adresse, cocher 'Sans' pour le nom de la rue et cliquer sur 'Appliquer' OU entrer un nom de rue approprié",

"190.title": "Minuscule dans le nom de ville",
"190.problem": "Le nom de ville commence avec une lettre en majuscule",
"190.solution": "Utilisé ce formulaire pour renommer la ville",
"192.problemLink": "W:Comment_nommer_les_routes_et_les_villes#Nommage_des_villes_et_villages",
"192.solutionLink": "F:t=29403",
"192.title": "Nom de ville avec des espaces inutiles",
"192.problem": "Double espace dans le nom de ville",
"192.solution": "Utiliser le formulaire suivant pour faire une demande de modification",
"193.enabled": false,
"193.title": "Nom de bille sans espace avant ou après une abrévation",
"193.problem": "Pas d'espace avant ('1943r.') ou après ('st.Jana') une abrévation dans le nom de rue",
"193.solution": "Utiliser ce formulaire pour renommer la ville",

"200.problemLink": "W:Soft_et_hard_turns",
"200.solutionLink": "W:Soft_et_hard_turns#Bonnes_pratiques",
"200.title": "Noeud A: Autorisation de tourner non confirmée",
"200.problem": "Le segment carrossable à une autorisation de tourner non confirmée au noeud A",
"200.solution": "Cliquer l'autorisation de tourner avec un ? violet pour la confirmer. Il peut être nécessaire de passer les sens unique à double sens pour afficher des flèches cachées",
