".country": "Italy",

"57.enabled": true,
"59.enabled": true,
"90.enabled": true,
"95.enabled": true,
"150.enabled": true,
"151.enabled": true,
"151.params": {"n": 5},
"152.enabled": true,
"152.params": {"n": 4},
"163.enabled": true,
"163.params": {
    "titleEN": "Ramp name starts with an 'A'",
    "problemEN": "The Ramp name starts with an 'A'",
    "solutionEN": "Replace 'A' with 'Dir.'",
    "regexp": "/^A /i",
},
"170.enabled": true,
