/*
 * MX.js -- WME Validator Localization for Mexico
 * Copyright (C) 2014-2018 Carlos Laso aka carloslaso
 *
 * This file is part of WME Validator: https://github.com/WMEValidator/
 *
 * WME Validator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * WME Validator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with WME Validator. If not, see <http://www.gnu.org/licenses/>.
 */

 /*************************************************************************
  * This file falls back to ES (spainish) localization
  *************************************************************************/

".country": "Mexico",
".updated": "2018-09-19",
".author": "carloslaso",
".fallbackCode": "ES",
".lng": ["ES-419"],
"city.consider": "Considera el siguiente nombre de ciudad:",
"city.1": "El nombre de la ciudad es muy corto",
"city.2": "Poner la Abreviación con palabra completa",
"city.3": "Escribir el nombre corto",
"city.4": "Escribir el Nombre de Ciudad",
"city.5": "Corregir Mayúsculas / Minúsculas",
"city.6": "Checar el orden de las palabras",
"city.7": "Checar Abreviación",
"city.8r": "Quitar nombre de País",
"city.9": "Verificar nombre de País",
"city.10r": "Quitar palabra",
"city.12": "Existen nombres iguales con distinto número de Identificador de Ciudad",
"city.13a": "Añadir un espacio",
"city.13r": "Quitar un espacio",
"city.14": "Verificar el número",
"props.skipped.problem": "El segmento ha sido modificado después del 01-05-2014 y bloqueado por Ud., por lo que el Validator no lo verificó",
"err.regexp": "Error analizando la opción #${n}:",
"props.disabled": "WME Validator está desactivado",
"props.limit.title": "Demasiados problemas reportados",
"props.limit.problem": "Hay demasiados problemas reportados por lo que algunos de ellos pueden no mostrarse",
"props.limit.solution": "Deje de seleccionar el segmento y pare el proceso de análisis. Luego presione el botón con la '✘' de color rojo (Borrar Reporte)",
"props.reports": "Reportes",
"report.save": "Almacena el reporte",
"report.list.andUp": "y más",
"report.list.reportOnly": "Sólo en el reporte",
"report.list.forCountries": "Para Países:",
"report.list.params": "Parámetros pare configurar en el Paquete de localización:",
"report.list.params.set": "Configuración Actual para ${country}:",
"report.list.enabled": "Hay ${n} parámetros activados para",
"report.list.disabled": "Hay ${n} parámetros desactivados para",
"report.list.total": "Hay ${n} parámetros disponibles",
"report.list.title": "Complete la lista de parámetros para",
"report.list.checks": "Ajustes->Acerca de->Parámetros disponibles",
"report.segments": "Segmentos totales revisados:",
"report.reported": "Reportado(s)",
"report.warnings": "avisos",
"report.link.forum": "foro",
"report.link.other": "enlace",
"report.title": "Reporte del WME Validator",
"report.source": "Fuente del reporte:",
"report.filter.streets": "Calles y vías de Servicio",
"report.filter.other": "Otras vías transitables y no transitables",
"report.filter.noneditable": "segmentos no editables",
"report.filter.excluded": "están excluidas de este reporte",
"report.search.updated.since": "actualizado desde el",
"report.search.title": "Buscar:",
"report.search.included": "están incluidos en el reporte.",
"report.beta.warning": "Advertencia del WME Beta!",
"report.beta.text": "Este reporte está generado en el WME Beta con permalinks beta.",
"report.beta.share": "Por favor, no comparta estos permalinks!",
"report.size.warning": "<b>Advertencia!</b><br>Este reporte tiene ${n} caracteres por lo que <b>no cabrá</b> en un solo mensaje privado o del foro.\n<br>Por favor añada<b>más filtros</b> para reducir el tamaño del reporte.",
"report.note.limit": "* Nota: Existieron muchas irregularidades en el reporte, por lo que algunas no están tomadas en cuenta en el resumen.",
"report.forum": "Para motivar mayor desarrollo, por favor deje su comentario en el",
"report.forum.link": "Hilo del foro de Waze.",
"report.thanks": "Gracias por usar el WME Validator!",
"msg.limit.segments": "Existen demasiados segmentos.\n\nPulse'Show report'para revisar el reporte, luego\n",
"msg.limit.segments.continue": "pulse '▶' (Play) para continuar.",
"msg.limit.segments.clear": "pulse '✘' (Clear) para borrar el reporte.",
"msg.pan.text": "Mueva el mapa para validarlo",
"msg.zoomout.text": "Aleje el zoom para comenzar el WME Validator",
"msg.click.text": "Pulse '▶' (Play) para validar el área visible del mapa",
"msg.autopaused": "paro automático",
"msg.autopaused.text": "¡Paro automático! Pulse '▶' (Play) para continuar.",
"msg.finished.text": "Pulse <b>'Show report'</b> para revisar los problemas en el mapa",
"msg.finished.tip": "Pulse '✉' (Share) button para hacer un reporte en el\nforo o en un mensaje privado",
"msg.noissues.tip": "Trata de quitar algunas opciones de filtrado o inicia el WME Validator sobre otra área del mapa",
"msg.scanning.text": "¡Analizando! Terminando en ~ ${n} min",
"msg.scanning.text.soon": "¡Analizando! Terminando en un minuto!",
"msg.scanning.tip": "Pulse el botón de 'Pause' para pausar o '■' (Stop) para detener el análisis",
"msg.starting.text": "¡Comenzando! Las capas se han deshabilitado para analizar más rápido!",
"msg.starting.tip": "Utilice el botón'Pause' para pausar o el botón '■' para parar",
"msg.paused.text": "¡En Pausa! pulse el botón de '▶' (Play) para continuar.",
"msg.paused.tip": "Para ver el reporte pulse el botón de 'Show report' (si está disponible) ",
"msg.continuing.tip": "El WME Validator continuará desde la localización donde fue pausado",
"msg.settings.text": "Pulse <b>'Back'</b> para regresar a la vista principal",
"msg.settings.tip": "¡Pulse el botón de 'Reset defaults' para resetear todos los ajustes en un click!",
"msg.reset.text": "Todas las opciones y ajustes han sido devueltos a su estado original",
"msg.reset.tip": "Pulse el botón de 'Back' para regresar a la vista principal",
"msg.textarea.pack": "Este es un Script alojado enGreasemonkey/Tampermonkey. Puedes copiar y pegar el texto en un <b>nuevo archivo .user.js</b><br>o <b>pegarlo directamente</b> en Greasemonkey/Tampermonkey",
"msg.textarea": "Por favor copia el texto de abajo y pegalo en el foro o en un mensaje privado",
"noaccess.text": "<b>Lo sentimos,</b><br>No puedes usar el WME Validator aquí.<br>Por favor revisa <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>este hilo en el foro</a><br>para mayor información.",
"noaccess.tip": "¡Por favor revisa el hilo del foro para mayor información",
"tab.switch.tip.on": "Para encender el resaltado pulsa (Alt+V)",
"tab.switch.tip.off": "Para apagar el resaltado pulsa (Alt+V)",
"tab.filter.tip": "Opciones para filtrar el reporte y los segmentos resaltados",
"tab.search.text": "búsqueda",
"tab.search.tip": "Opciones avanzadas de filtrado para inculír segmentos específicos solamente",
"tab.help.tip": "¿Necesita ayuda?",
"filter.noneditables.text": "Excluir los segmentos <b>no editables</b>",
"filter.noneditables.tip": "No reportar los segmentos bloqueados o\nsegmentos fuera de mis áreas de edción",
"filter.duplicates.text": "No incluir segmentos <b>duplicados</b>",
"filter.duplicates.tip": "No mostrar el mismo segmento en distintas\npartes del reporte\n* Nota: Esta opción NO afecta el resaltado",
"filter.streets.text": "No incluir <b>Calles y Vías de Servicio</b>",
"filter.other.text": "No incluir <b>Otras vías conducibles y no conducibles</b>",
"filter.other.tip": "No reportar Vías de Tierra, Vías de estacionamiento, Vías privadas ni \nsegmentos no conducibles",
"filter.notes.text": "No incluir <b>notas</b>",
"filter.notes.tip": "Reportar solamente advertencias y errores",
"search.youredits.text": "Incluir <b>sólo mis ediciones</b>",
"search.youredits.tip": "Incluir sólo los segmentos editados por mí",
"search.updatedby.text": "<b>Actualizados por*:</b>",
"search.updatedby.tip": "Incluir solamente los segmentos actualizados por el editor especificado\n* Nota: Esta opción está disponible sólo para Country Managers\nEste campo soporta:\n - Lists: Mías, de otro editor\n - wildcards: pal*bra\n - negation: !me *\n* Nota: puedes usar 'me' para encontrar coincidencias de ti mismo",
"search.updatedsince.tip": "Incluir segmentos editados desde el día epecificado\nFormato de fecha de Firefox: AAAA-MM-DD",
"search.city.tip": "Incluir sólo segmentos con el Nombre de ciudad especificado\nEste campo soporta:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
"search.checks.tip": "Incluir sólo segmentos reportados como se especifica\nEste campo puede buscar:\n - severities: errores\n - check names: Nuevo Camino\n - check IDs: 200\nEste campo soporta:\n - listas: 36, 37\n - comodines: *rotonda*\n - negación: !unconfirmed*, *",
"search.checks.example": "Ejempo: revertir*",
"help.text": "<b>Tópicos de Ayuda:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Haz tu pregunta en el foro</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Cómo ajustar Validator para tu País</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Acerca de\"Puede estar incorrecto el Nombre de Ciudad\"</a>",
"help.tip": "Abrir en una nueva pestaña en el navegador",
"button.scan.tip": "Comenzar escaneando el área actual del mapa\n* Nota: Esto puede tomar algunos minutos",
"button.scan.tip.NA": "Aleje para comenzar a escanear el área actual del mapa",
"button.stop.tip": "Parar escaneo y regresar a la posición de inicio",
"button.clear.tip": "Borrar reporte y caché de segmento",
"button.clear.tip.red": "Existen demasiados segmentos reportados:\n 1. Pulse 'Muestre reporte' para generar el reporte.\n 2. Pulse este boton para borrar el reporte y comenzar de nuevo.",
"button.report.text": "Muestra reporte",
"button.report.tip": "Aplicar el filtro y generar un reporte en HTML en una nueva pestaña",
"button.BBreport.tip": "Compartir el reporte en el Foro de Waze o en un Mensaje Privado",
"tab.custom.text": "Ajustes predefinidos",
"tab.custom.tip": "Ajustes predefinidos por el usuario",
"tab.scanner.tip": "Ajustes de escaneado del mapa",
"tab.about.tip": "Acerca del WME Validator",
"scanner.sounds.NA": "Su navegador no soporta AudioContext",
"scanner.highlight.text": "Resaltar problemas en el mapa",
"scanner.highlight.tip": "Resaltar problemas reportados en el mapa",
"scanner.slow.text": "Habilitar\"chequeos\" lentos",
"scanner.slow.tip": "Habilita análisis profundo del mapa\n* Nota: esta opción puede hacer lento el proceso de escaneo",
"scanner.ext.text": "Reportar resaltados externos",
"scanner.ext.tip": "Reportar segmentos resaltados por WME Toolbox o WME Color Highlights",
"advanced.atbottom.text": "Hasta abajo",
"advanced.atbottom.tip": "Poner WME Validator en la parte de abajo de la página",
"custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Planilla Propia</a>",
"custom.template.tip": "Checar con planilla expandible definida por el usuario.\n\nPuedes usar las siguientes variables de expansión:\nDirección:\n${country}, ${state}, ${city}, ${street},\n${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nPropiedades de segmentos:\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}\nAyudantes:\n${drivable}, ${roundabout}, ${hasHNs},\n${Uturn}, ${deadEnd}, ${softTurns},\n${deadEndA}, ${partialA},\n${deadEndB}, ${partialB}\nConnectivity:\n${segmentsA}, ${inA}, ${outA}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"about.tip": "Abrir liga en una pestaña nueva",
"button.reset.text": "Regresar a los ajustes originales",
"button.reset.tip": "Revertir las opciones de filtrado y ajustes a los originales",
"button.list.text": "Revisiones disponibles...",
"button.list.tip": "Mostrar una lista de revisiones disponibles en WME Validator",
"button.wizard.tip": "Crear un paquete de localización",
"button.back.text": "Regresar",
"button.back.tip": "Cerrar ajustes y regresar a la vista principal",
"1.problem": "Los números de salida de los segmentos de la rotonda no son consecutivos",
"2.problem": "El segmento tiene nodos geométricos innecesarios",
"2.solution": "Simplificar la geometría del segmento pasando el puntero encima del segmento y presionando la letra \"d\"",
"3.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"4.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"5.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"6.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"7.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"8.title": "WME Toolbox: Numeración de Casas",
"8.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"9.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"13.title": "WME Color Highlights: Bloqueo de un editor",
"13.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"14.title": "WME Color Highlights: Vía de peaje / Vía de un sólo sentido",
"14.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"15.title": "WME Color Highlights: Recientemente editado",
"15.problem": "El segmento está resaltado por elWME Color Highlights. No representa un problema",
"16.title": "WME Color Highlights: Rango de v",
"16.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"17.title": "WME Color Highlights: Sin Ciudad",
"17.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"18.title": "WME Color Highlights: Restricción de tiempo / Tipo de camino resaltado",
"18.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"19.title": "WME Color Highlights: Sin nombre",
"19.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"20.title": "WME Color Highlights: Filtrar por Ciudad",
"20.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"21.title": "WME Color Highlights: Filtrar por nombre alterno de Ciudad (alt. city)",
"21.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"22.title": "WME Color Highlights: Filtrar por editor",
"22.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"23.title": "Camino sin confirmar",
"23.problem": "Cada segmento debe contener como mínimo Información de Estado y País",
"23.solution": "Actualice el camino actualizando sus datos",
"24.enabled": false,
"24.title": "Puede contener un nombre de ciudad incorrecto (sólo disponible en el reporte)",
"24.problem": "El segmento puede contener el nombre de ciudad incorrecto",
"24.solution": "Considere el nombre de ciudad Sugerido y use esta forma para renombrar la ciudad",
"25.title": "Sentido desconocido en un camino conducible",
"25.problem": "El sentido desconocido del segmento no prevendrá el ruteo por el mismo",
"25.solution": "Coloque la dirección del segmento",
"28.title": "Nombre de calle en una Rampa de doble sentido",
"28.problem": "Si una rampa no tiene nombre, se aplicará el nombre del siguiente camino que lo tenga",
"28.solution": "En las propiedades de dirección, active la casilla de 'Ninguno' seguida del nombre de calle y entonces pulse 'Aplicar'",
"29.problem": "En Waze no se nombran los segmentos de las rotondas",
"29.solution": "En las propiedades de dirección, seleccione la opción 'Ninguno' en seguida del nombre de calle, pulse 'Aplicar' y entonces añada un 'lugar' de tipo 'distribuidor vial' y escriba el nombre de la glorieta",
"34.title": "Vaciar el nombre alterno de calle",
"34.problem": "El nombre alterno de calle está vacío",
"34.solution": "Quitar los nombres alternos de calle vacíos",
"35.title": "Camino conducible no terminado",
"35.problem": "Waze no otorgará rutas por segmentos sin terminar",
"35.solution": "Mueva un poco el segmento para que el nodo se añada de manera automática",
"38.title": "Restricción de segmento vencida (no grave)",
"38.problem": "El segmento tiene una restricción que ya venció",
"38.solution": "Pulsar 'Editar restricciones' y borrar las restricciones vencidas",
"39.title": "Restricción de giro vencida (no grave)",
"39.problem": "El segmento tiene un giro con restricció vencida",
"39.solution": "Pulsar la figura del reloj en seguida de la flecha amarilla y borre las restricciones vencidas",
"41.enabled": false,
"41.title": "Conectividad reversible en un segmento conducible",
"41.problem": "Existe un giro que va contra la dirección del segmento en el nodo A",
"41.solution": "Haga el segmento de 'doble sentido', restrinja todos los giros en el nodo A y luego haga el segmento de 'Un sólo sentido (A-B) de nuevo",
"42.enabled": false,
"42.title": "Nodo B: Conectividad reversible en segmento conducible",
"42.problem": "Existe un giro que va en contra de la dirección del segmento en el nodo B",
"42.solution": "Haga el segmento de 'doble sentido', restrinja todos los giros en el nodo A y luego haga el segmento de 'Un sólo sentido (A-B) de nuevo",
"43.problem": "El segmento está conectado en sí mismo",
"43.solution": "Divida el segmento en tres",
"46.title": "Nodo A: No existe conectividad hacia adentro del camino conducible",
"46.problem": "El segmento conducible no privado no tiene ningún giro permitido en el nodo A",
"46.solution": "Seleccione un segmento adyacente y active por lo menos un giro al segmento en el nodo A",
"47.title": "Nodo B: No existe conectividad hacia adentro del camino conducible (no grave) ",
"47.problem": "El segmento conducible no privado no tiene ningún giro permitido en el nodo B",
"47.solution": "Seleccione un segmento adyacente y active por lo menos un giro al segmento en el nodo B",
"48.title": "Segmento de glorieta de doble sentido",
"48.problem": "El segmento de la glorieta es bidireccional",
"48.solution": "Rehacer la glorieta",
"78.title": "El segmento que creó comienza y termina en un mismo segmento",
"78.problem": "Los dos segmentos comparten los mismos puntos finales",
"78.solution": "Parta el segmento. Puede también remover uno de ellos si son idénticos",
"87.title": "Múltiples segmentos de salida de la glorieta en el nodo A",
"87.problem": "El nodo A en la glorieta tiene más de un segmento de salida conectado",
"87.solution": "Re hacer la glorieta",
"99.title": "Vuelta en U habilitada en segmento de entrada a la glorieta (no grave)",
"99.problem": "El segmento de entrada a la glorieta tiene una vuelta en U habilitada",
"99.solution": "Deshabilite la vuelta en U",
"101.title": "Camino Cerrado (Sólo disponible en el reporte)",
"101.problem": "El segmento está marcado como Cerrado",
"101.solution": "Si la construcción ya terminó, reactive la conectividad del segmento y remueva el sufijo",
"102.title": "No existe conectividad hacia afuera del segmento en el nodo A (no grave)",
"102.problem": "El segmento no tiene habilitado ningún giro hacia afuera en el nodo A",
"102.solution": "Permita por lo menos un giro hacia el segmento en el nodo A",
"103.title": "No existe conectividad hacia afuera en el nodo B (no grave))",
"103.problem": "El segmento no tiene habilitado ningún giro hacia afuera en el nodo B",
"103.solution": "Permita por lo menos un giro desde el segmento en el nodo B",
"104.enabled": false,
"104.title": "Segmento tipo ferrocarril usado para comentarios",
"104.problem": "El segmentotipo ferrocarril etá siendo usado probablemente para comentarios del mapa",
"104.solution": "Remover los comentarios ya que las vías férreas se verán en la aplicación",
"107.title": "No hay conexion del Nodo A (no grave)",
"107.problem": "El Nodo A del segmento está a dentro del rango de 5m de otro segmento pero no está conectado por una intersección",
"107.solution": "Arrastre el nodo A al segmento más cercano de modo que se junten, o muévalo un poco más lejos.",
"108.title": "No hay conexión en el nodo B (no grave)",
"108.problem": "El nodo B del segmento está dentro del rango de 5m de otro segmento pero no está conectado por una intersección",
"108.solution": "Arrastre el nodo B al segmento más cercano de modo que lo toque o muévalo un poco más lejos",
"109.problem": "El segmento es de menos de ${n}m de largo, por lo que es difícil verlo en el mapa y puede causar problemas de ruteo",
"109.solution": "Aumente el largo del segmento, remuévalo o llévelo al nodo del segmento adyacente",
"112.title": "Nombre de rampa demasiado largo",
"112.problem": "El nombre de la rampa tiene más de ${n} letras",
"112.solution": "Acorte el nombre de la rampa",
"116.solution": "Corrija la elevación",
"117.title": "Marcador de Zona de Construcción obsoleto",
"117.problem": "El segmento está marcado con un sufijo de Zona de Construcción obsoleto",
"117.solution": "Cambie el CONST ZN a (cerrado)",
"118.title": "En el Nodo A: Segmentos encimados (no grave)",
"118.problem": "El segmento está encimado con el segmento adyacente en el nodo A",
"118.solution": "Abra los segmentos a 2°, borre el punto geométrico o el segmento duplicado en el nodo A",
"119.title": "Nodo B: Segmentos encimados",
"119.problem": "El segmento está encimado con el segmento adyacente en el nodoB",
"119.solution": "Abra los segmentos a 2°, borre el punto geométrico o el segmento duplicado en el nodo B",
"120.title": "Nodo A: Giro demasiado cerrado (no grave)",
"120.problem": "El segmento conducible tiene un ángulo de giro muy cerrado en el nodo A",
"120.solution": "Prohíba la vuelta cerrada en el nodo A o abra los segmentos a 30°",
"121.title": "Nodo B: Giro demasiado cerrado (no grave)",
"121.problem": "El segmento conducible tiene un ángulo de giro muy cerrado en el nodo B",
"121.solution": "Prohíba la vuelta cerrada en el nodo B o abra los segmentos a 30°",
"128.title": "Revisión definida por el usuario (verde)",
"128.problem": "Algunas propiedades del segmento van en contra de la expresión regular definida por el usuario (ver Settings→Custom)",
"128.solution": "Resuelva el problema",
"129.title": "Revisión definida por el usuario (azúl)",
"129.problem": "Algunas propiedades del segmento van en contra de la expresión regular definida por el usuario (ver Settings→Custom)",
"129.solution": "Resuelva el problema",
"150.enabled": false,
"151.enabled": false,
"152.enabled": false,
"172.title": "Espacios innecesarios en el nombre de calle",
"172.solution": "Eliminar espacios innecesarios del nombre de la calle",
"173.title": "No hay espacio antes/después de la abreviatura en el nombre de calle",
"173.problem": "No hay espacio antes de ('1943r.') o después ('Sn.Juan') de una abreviatura en el nombre de calle",
"173.solution": "Añadir un espacio antes/después de la abreviatura",
"175.title": "Nombre de calle vacío",
"175.problem": "El nombre de la calle tiene solamente espacios o un punto",
"175.solution": "En las propiedades de la dirección, elija la casilla 'Ninguno' enseguida de 'nombre' o escriba el nombre de la Calle. Presione 'Aplicar'",
"190.enabled": false,
"190.title": "Nombre de ciudad en minúsculas",
"190.solution": "Use esta forma para renombrar la ciudad",
"192.enabled": false,
"192.title": "Espacios innecesarios en el nombre de ciudad",
"192.solution": "Use esta forma para renombrar la ciudad",
"193.title": "No hay espacios antes/después de la abreviatura de la Ciudad",
"193.problem": "No hay espacio antes ('1943r.') o después ('Sn.Juan') de una abreviatura en el nombre de ciudad",
"193.solution": "Use esta forma para renombrar la ciudad",
"200.enabled": false,
"200.title": "En el nodo A: Giro no confirmado en un camino menor",
"200.problem": "El segmento del camino menor tiene un giro no confirmado (suave) en el nodo A",
"200.solution": "Pulse en la flecha de giro indicada con un signo de interrogación morado para confirmarla. Nota: Puede ser necesario hacer el segmento de doble sentido para poder ver dichos giros",
"201.enabled": false,
"201.title": "En el nodo A: Giro no confirmado en una vía primaria",
"201.problem": "El segmento de vía primaria tiene un giro no confirmado (suave) en el nodo A",
"201.solution": "Pulse en la flecha de giro indicada con un signo de interrogación morado para confirmarla. Nota: Puede ser necesario hacer el segmento de doble sentido para poder ver dichos giros",
"202.enabled": false,
