/*
 * MX.js -- WME Validator Localization for Mexico
 * Copyright (C) 2014-2018 Carlos Laso
 *
 * This file is part of WME Validator: https://github.com/WMEValidator/
 *
 * WME Validator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * WME Validator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with WME Validator. If not, see <http://www.gnu.org/licenses/>.
 */

 /*************************************************************************
  * This file falls back to ES (spainish) localization
  *************************************************************************/

".country": "Mexico",
".updated": "2018-09-19",
".author": "carloslaso",
".fallbackCode": "ES",
".lng": ["ES-419","EN-US","EN"],
"city.consider.en": "consider this city name:",
"city.consider": "Considera el siguiente nombre de ciudad:",
"city.1.en": "city name is too short",
"city.1": "El nombre de la ciudad es muy corto",
"city.2.en": "expand the abbreviation",
"city.2": "Poner la Abreviación con palabra completa",
"city.3.en": "complete short name",
"city.3": "Escribir el nombre corto",
"city.4.en": "complete city name",
"city.4": "Escribir el Nombre de Ciudad",
"city.5.en": "correct letter case",
"city.5": "Corregir Mayúsculas / Minúsculas",
"city.6.en": "check word order",
"city.6": "Checar el orden de las palabras",
"city.7.en": "check abbreviations",
"city.7": "Checar Abreviación",
"city.8a.en": "add county name",
"city.8a": "Añadir nombre de País",
"city.8r.en": "remove county name",
"city.8r": "Quitar nombre de País",
"city.9.en": "check county name",
"city.9": "Verificar nombre de País",
"city.10a.en": "add a word",
"city.10a": "Añadir palabra",
"city.10r.en": "remove a word",
"city.10r": "Quitar palabra",
"city.11.en": "add county code",
"city.11": "Añadir Código de País",
"city.12.en": "identical names, but different city IDs",
"city.12": "Existen nombres iguales con distinto número de Identificador de Ciudad",
"city.13a.en": "add a space",
"city.13a": "Añadir un espacio",
"city.13r.en": "remove a space",
"city.13r": "Quitar un espacio",
"city.14.en": "check the number",
"city.14": "Verificar el número",
"props.skipped.title.en": "The segment is not checked",
"props.skipped.title": "TODO: The segment is not checked",
"props.skipped.problem.en": "The segment is modified after 2014-05-01 AND locked for you, so Validator did not check it",
"props.skipped.problem": "El segmento ha sido modificado después del 01-05-2014 y bloqueado por Ud., por lo que el Validator no lo verificó",
"err.regexp.en": "Error parsing option for check #${n}:",
"err.regexp": "Error analizando la opción #${n}:",
"props.disabled.en": "WME Validator is disabled",
"props.disabled": "WME Validator está desactivado",
"props.limit.title.en": "Too many issues reported",
"props.limit.title": "Demasiados problemas reportados",
"props.limit.problem.en": "There are too many issues reported, so some of them might not be shown",
"props.limit.problem": "Hay demasiados problemas reportados por lo que algunos de ellos pueden no mostrarse",
"props.limit.solution.en": "Deselect the segment and stop scanning process. Then click red '✘' (Clear report) button",
"props.limit.solution": "Deje de seleccionar el segmento y pare el proceso de análisis. Luego presione el botón con la '✘' de color rojo (Borrar Reporte)",
"props.reports.en": "reports",
"props.reports": "Reportes",
"props.noneditable.en": "You cannot edit this segment",
"props.noneditable": "No puedes editar este segmento",
"report.save.en": "Save this report",
"report.save": "Almacena el reporte",
"report.list.andUp.en": "and up",
"report.list.andUp": "y más",
"report.list.severity.en": "Severity:",
"report.list.severity": "Severidad:",
"report.list.reportOnly.en": "only in report",
"report.list.reportOnly": "Sólo en el reporte",
"report.list.forEditors.en": "For editors level:",
"report.list.forEditors": "Para editores Nivel:",
"report.list.forCountries.en": "For countries:",
"report.list.forCountries": "Para Países:",
"report.list.forStates.en": "For states:",
"report.list.forStates": "Para Estados:",
"report.list.forCities.en": "For cities:",
"report.list.forCities": "Para ciudades:",
"report.list.params.en": "Params to configure in localization pack:",
"report.list.params": "Parámetros pare configurar en el Paquete de localización:",
"report.list.params.set.en": "Current configuration for ${country}:",
"report.list.params.set": "Configuración Actual para ${country}:",
"report.list.enabled.en": "${n} checks are enabled for",
"report.list.enabled": "Hay ${n} parámetros activados para",
"report.list.disabled.en": "${n} checks are disabled for",
"report.list.disabled": "Hay ${n} parámetros desactivados para",
"report.list.total.en": "There are ${n} checks available",
"report.list.total": "Hay ${n} parámetros disponibles",
"report.list.title.en": "Complete List of Checks for",
"report.list.title": "Complete la lista de parámetros para",
"report.list.see.en": "See",
"report.list.see": "Ver",
"report.list.checks.en": "Settings->About->Available checks",
"report.list.checks": "Ajustes->Acerca de->Parámetros disponibles",
"report.list.fallback.en": "Localization Fallback Rules:",
"report.list.fallback": "TODO: Localization Fallback Rules:",
"report.and.en": "and",
"report.and": "y",
"report.segments.en": "Total number of segments checked:",
"report.segments": "Segmentos totales revisados:",
"report.customs.en": "Custom checks matched (green/blue):",
"report.customs": "TODO: Custom checks matched (green/blue):",
"report.reported.en": "Reported",
"report.reported": "Reportado(s)",
"report.errors.en": "errors",
"report.errors": "errores",
"report.warnings.en": "warnings",
"report.warnings": "avisos",
"report.notes.en": "notes",
"report.notes": "notas",
"report.link.wiki.en": "wiki",
"report.link.wiki": "wiki",
"report.link.forum.en": "forum",
"report.link.forum": "foro",
"report.link.other.en": "link",
"report.link.other": "enlace",
"report.contents.en": "Contents:",
"report.contents": "Contenidos:",
"report.summary.en": "Summary",
"report.summary": "Resumen",
"report.title.en": "WME Validator Report",
"report.title": "Reporte del WME Validator",
"report.share.en": "to Share",
"report.share": "Para Compartir",
"report.generated.by.en": "generated by",
"report.generated.by": "Generado por",
"report.generated.on.en": "on",
"report.generated.on": "en",
"report.source.en": "Report source:",
"report.source": "Fuente del reporte:",
"report.filter.duplicate.en": "duplicate segments",
"report.filter.duplicate": "Segmentos duplicados",
"report.filter.streets.en": "Streets and Service Roads",
"report.filter.streets": "Calles y vías de Servicio",
"report.filter.other.en": "Other drivable and Non-drivable",
"report.filter.other": "Otras vías transitables y no transitables",
"report.filter.noneditable.en": "non-editable segments",
"report.filter.noneditable": "segmentos no editables",
"report.filter.notes.en": "notes",
"report.filter.notes": "notas",
"report.filter.title.en": "Filter:",
"report.filter.title": "Filtro:",
"report.filter.excluded.en": "are excluded from this report.",
"report.filter.excluded": "están excluidas de este reporte",
"report.search.updated.by.en": "updated by",
"report.search.updated.by": "actualizado por",
"report.search.updated.since.en": "updated since",
"report.search.updated.since": "actualizado desde el",
"report.search.city.en": "from",
"report.search.city": "desde",
"report.search.reported.en": "reported as",
"report.search.reported": "reportado como",
"report.search.title.en": "Search:",
"report.search.title": "Buscar:",
"report.search.only.en": "only segments",
"report.search.only": "Sólo segmentos",
"report.search.included.en": "are included into the report.",
"report.search.included": "están incluidos en el reporte.",
"report.beta.warning.en": "WME Beta Warning!",
"report.beta.warning": "Advertencia del WME Beta!",
"report.beta.text.en": "This report is generated in beta WME with beta permalinks.",
"report.beta.text": "Este reporte está generado en el WME Beta con permalinks beta.",
"report.beta.share.en": "Please do not share those permalinks!",
"report.beta.share": "Por favor, no comparta estos permalinks!",
"report.size.warning.en": "<b>Warning!</b><br>The report is ${n} characters long so <b>it will not fit</b> into a single forum or private message.\n<br>Please add <b>more filters</b> to reduce the size of the report.",
"report.size.warning": "<b>Advertencia!</b><br>Este reporte tiene ${n} caracteres por lo que <b>no cabrá</b> en un solo mensaje privado o del foro.\n<br>Por favor añada<b>más filtros</b> para reducir el tamaño del reporte.",
"report.note.limit.en": "* Note: there were too many issues reported, so some of them are not counted in the summary.",
"report.note.limit": "* Nota: Existieron muchas irregularidades en el reporte, por lo que algunas no están tomadas en cuenta en el resumen.",
"report.forum.en": "To motivate further development please leave your comment on the",
"report.forum": "Para motivar mayor desarrollo, por favor deje su comentario en el",
"report.forum.link.en": "Waze forum thread.",
"report.forum.link": "Hilo del foro de Waze.",
"report.thanks.en": "Thank you for using WME Validator!",
"report.thanks": "Gracias por usar el WME Validator!",
"msg.limit.segments.en": "There are too many segments.\n\nClick 'Show report' to review the report, then\n",
"msg.limit.segments": "Existen demasiados segmentos.\n\nPulse'Show report'para revisar el reporte, luego\n",
"msg.limit.segments.continue.en": "click '▶' (Play) to continue.",
"msg.limit.segments.continue": "pulse '▶' (Play) para continuar.",
"msg.limit.segments.clear.en": "click '✘' (Clear) to clear the report.",
"msg.limit.segments.clear": "pulse '✘' (Clear) para borrar el reporte.",
"msg.pan.text.en": "Pan around to validate the map",
"msg.pan.text": "Mueva el mapa para validarlo",
"msg.zoomout.text.en": "Zoom out to start WME Validator",
"msg.zoomout.text": "Aleje el zoom para comenzar el WME Validator",
"msg.click.text.en": "Click '▶' (Play) to validate visible map area",
"msg.click.text": "Pulse '▶' (Play) para validar el área visible del mapa",
"msg.autopaused.en": "autopaused",
"msg.autopaused": "paro automático",
"msg.autopaused.text.en": "Auto paused! Click '▶' (Play) to continue.",
"msg.autopaused.text": "¡Paro automático! Pulse '▶' (Play) para continuar.",
"msg.autopaused.tip.en": "WME Validator automatically paused on map drag or window size change",
"msg.autopaused.tip": "TODO: WME Validator paró automáticamente por arrastrado de mapa o cambio de tamaño",
"msg.finished.text.en": "Click <b>'Show report'</b> to review map issues",
"msg.finished.text": "Pulse <b>'Show report'</b> para revisar los problemas en el mapa",
"msg.finished.tip.en": "Click '✉' (Share) button to post report on a\nforum or in a private message",
"msg.finished.tip": "Pulse '✉' (Share) button para hacer un reporte en el\nforo o en un mensaje privado",
"msg.noissues.text.en": "Finished! No issues found!",
"msg.noissues.text": "¡Terminado! ¡No se encontraron problemas!",
"msg.noissues.tip.en": "Try to uncheck some filter options or start WME Validator over another map area!",
"msg.noissues.tip": "Trata de quitar algunas opciones de filtrado o inicia el WME Validator sobre otra área del mapa",
"msg.scanning.text.en": "Scanning! Finishing in ~ ${n} min",
"msg.scanning.text": "¡Analizando! Terminando en ~ ${n} min",
"msg.scanning.text.soon.en": "Scanning! Finishing in a minute!",
"msg.scanning.text.soon": "¡Analizando! Terminando en un minuto!",
"msg.scanning.tip.en": "Click 'Pause' button to pause or '■' (Stop) to stop",
"msg.scanning.tip": "Pulse el botón de 'Pause' para pausar o '■' (Stop) para detener el análisis",
"msg.starting.text.en": "Starting! Layers are off to scan faster!",
"msg.starting.text": "¡Comenzando! Las capas se han deshabilitado para analizar más rápido!",
"msg.starting.tip.en": "Use 'Pause' button to pause or '■' button to stop",
"msg.starting.tip": "Utilice el botón'Pause' para pausar o el botón '■' para parar",
"msg.paused.text.en": "On pause! Click '▶' (Play) button to continue.",
"msg.paused.text": "¡En Pausa! pulse el botón de '▶' (Play) para continuar.",
"msg.paused.tip.en": "To view the report click 'Show report' button (if available)",
"msg.paused.tip": "Para ver el reporte pulse el botón de 'Show report' (si está disponible) ",
"msg.continuing.text.en": "Continuing!",
"msg.continuing.text": "¡Continuando!",
"msg.continuing.tip.en": "WME Validator will continue from the location it was paused",
"msg.continuing.tip": "El WME Validator continuará desde la localización donde fue pausado",
"msg.settings.text.en": "Click <b>'Back'</b> to return to main view",
"msg.settings.text": "Pulse <b>'Back'</b> para regresar a la vista principal",
"msg.settings.tip.en": "Click 'Reset defaults' button to reset all settings in one click!",
"msg.settings.tip": "¡Pulse el botón de 'Reset defaults' para resetear todos los ajustes en un click!",
"msg.reset.text.en": "All filter options and settings have been reset to their defaults",
"msg.reset.text": "Todas las opciones y ajustes han sido devueltos a su estado original",
"msg.reset.tip.en": "Click 'Back' button to return to main view",
"msg.reset.tip": "Pulse el botón de 'Back' para regresar a la vista principal",
"msg.textarea.pack.en": "This is a Greasemonkey/Tampermonkey script. You can copy and paste the text below into a <b>new .user.js file</b><br>or <b>paste it directly</b> into the Greasemonkey/Tampermonkey",
"msg.textarea.pack": "Este es un Script alojado enGreasemonkey/Tampermonkey. Puedes copiar y pegar el texto en un <b>nuevo archivo .user.js</b><br>o <b>pegarlo directamente</b> en Greasemonkey/Tampermonkey",
"msg.textarea.en": "Please copy the text below and then paste it into your forum post or private message",
"msg.textarea": "Por favor copia el texto de abajo y pegalo en el foro o en un mensaje privado",
"noaccess.text.en": "<b>Sorry,</b><br>You cannot use WME Validator over here.<br>Please check <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>the forum thread</a><br>for more information.",
"noaccess.text": "<b>Lo sentimos,</b><br>No puedes usar el WME Validator aquí.<br>Por favor revisa <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>este hilo en el foro</a><br>para mayor información.",
"noaccess.tip.en": "Please check the forum thread for more information!",
"noaccess.tip": "¡Por favor revisa el hilo del foro para mayor información",
"tab.switch.tip.on.en": "Click to switch highlighting on (Alt+V)",
"tab.switch.tip.on": "Para encender el resaltado pulsa (Alt+V)",
"tab.switch.tip.off.en": "Click to switch highlighting off (Alt+V)",
"tab.switch.tip.off": "Para apagar el resaltado pulsa (Alt+V)",
"tab.filter.text.en": "filter",
"tab.filter.text": "Filtro",
"tab.filter.tip.en": "Options to filter the report and highlighted segments",
"tab.filter.tip": "Opciones para filtrar el reporte y los segmentos resaltados",
"tab.search.text.en": "search",
"tab.search.text": "búsqueda",
"tab.search.tip.en": "Advanced filter options to include only specific segments",
"tab.search.tip": "Opciones avanzadas de filtrado para inculír segmentos específicos solamente",
"tab.help.text.en": "help",
"tab.help.text": "Ayuda",
"tab.help.tip.en": "Need help?",
"tab.help.tip": "¿Necesita ayuda?",
"filter.noneditables.text.en": "Exclude <b>non-editable</b> segments",
"filter.noneditables.text": "Excluir los segmentos <b>no editables</b>",
"filter.noneditables.tip.en": "Do not report locked segments or\nsegments outside of your editable areas",
"filter.noneditables.tip": "No reportar los segmentos bloqueados o\nsegmentos fuera de mis áreas de edción",
"filter.duplicates.text.en": "Exclude <b>duplicate</b> segments",
"filter.duplicates.text": "No incluir segmentos <b>duplicados</b>",
"filter.duplicates.tip.en": "Do not show the same segment in different\nparts of report\n* Note: this option DOES NOT affect highlighting",
"filter.duplicates.tip": "No mostrar el mismo segmento en distintas\npartes del reporte\n* Nota: Esta opción NO afecta el resaltado",
"filter.streets.text.en": "Exclude <b>Streets and Service Roads</b>",
"filter.streets.text": "No incluir <b>Calles y Vías de Servicio</b>",
"filter.streets.tip.en": "Do not report Streets and Service Roads",
"filter.streets.tip": "No reportar Calles y Vías de servicio",
"filter.other.text.en": "Exclude <b>Other drivable and Non-drivable</b>",
"filter.other.text": "No incluir <b>Otras vías conducibles y no conducibles</b>",
"filter.other.tip.en": "Do not report Dirt, Parking Lot, Private Roads\nand non-drivable segments",
"filter.other.tip": "No reportar Vías de Tierra, Vías de estacionamiento, Vías privadas ni \nsegmentos no conducibles",
"filter.notes.text.en": "Exclude <b>notes</b>",
"filter.notes.text": "No incluir <b>notas</b>",
"filter.notes.tip.en": "Report only warnings and errors",
"filter.notes.tip": "Reportar solamente advertencias y errores",
"search.youredits.text.en": "Include <b>only your edits</b>",
"search.youredits.text": "Incluir <b>sólo mis ediciones</b>",
"search.youredits.tip.en": "Include only segments edited by you",
"search.youredits.tip": "Incluir sólo los segmentos editados por mí",
"search.updatedby.text.en": "<b>Updated by*:</b>",
"search.updatedby.text": "<b>Actualizados por*:</b>",
"search.updatedby.tip.en": "Include only segments updated by the specified editor\n* Note: this option is available for country managers only\nThis field supports:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Note: you may use 'me' to match yourself",
"search.updatedby.tip": "Incluir solamente los segmentos actualizados por el editor especificado\n* Nota: Esta opción está disponible sólo para Country Managers\nEste campo soporta:\n - Lists: Mías, de otro editor\n - wildcards: pal*bra\n - negation: !me *\n* Nota: puedes usar 'me' para encontrar coincidencias de ti mismo",
"search.updatedby.example.en": "Example: me",
"search.updatedby.example": "Ejemplo:",
"search.updatedsince.text.en": "<b>Updated since:</b>",
"search.updatedsince.text": "Actualizado desde:</b>",
"search.updatedsince.tip.en": "Include only segments edited since the date specified\nFirefox date format: YYYY-MM-DD",
"search.updatedsince.tip": "Incluir segmentos editados desde el día epecificado\nFormato de fecha de Firefox: AAAA-MM-DD",
"search.updatedsince.example.en": "YYYY-MM-DD",
"search.updatedsince.example": "AAAA-MM-DD",
"search.city.text.en": "<b>City name:</b>",
"search.city.text": "<b>Nombre de Ciudad:</b>",
"search.city.tip.en": "Include only segments with specified city name\nThis field supports:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
"search.city.tip": "Incluir sólo segmentos con el Nombre de ciudad especificado\nEste campo soporta:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
"search.city.example.en": "Example: !Paris, *",
"search.city.example": "Ejemplo: !Paris, *",
"search.checks.text.en": "<b>Reported as:</b>",
"search.checks.text": "<b>Reportado como:</b>",
"search.checks.tip.en": "Include only segments reported as specified\nThis field matches:\n - severities: errors\n - check names: New road\n - check IDs: 200\nThis field supports:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
"search.checks.tip": "Incluir sólo segmentos reportados como se especifica\nEste campo puede buscar:\n - severities: errores\n - check names: Nuevo Camino\n - check IDs: 200\nEste campo soporta:\n - listas: 36, 37\n - comodines: *rotonda*\n - negación: !unconfirmed*, *",
"search.checks.example.en": "Example: reverse*",
"search.checks.example": "Ejempo: revertir*",
"help.text.en": "<b>Help Topics:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Ask your question on the forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">How to adjust Validator for your country</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">About the \"Might be Incorrect City Name\"</a>",
"help.text": "<b>Tópicos de Ayuda:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Haz tu pregunta en el foro</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Cómo ajustar Validator para tu País</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Acerca de\"Puede estar incorrecto el Nombre de Ciudad\"</a>",
"help.tip.en": "Open in a new browser tab",
"help.tip": "Abrir en una nueva pestaña en el navegador",
"button.scan.tip.en": "Start scanning current map area\n* Note: this might take few minutes",
"button.scan.tip": "Comenzar escaneando el área actual del mapa\n* Nota: Esto puede tomar algunos minutos",
"button.scan.tip.NA.en": "Zoom out to start scanning current map area",
"button.scan.tip.NA": "Aleje para comenzar a escanear el área actual del mapa",
"button.pause.tip.en": "Pause scanning",
"button.pause.tip": "Pausar escaneo",
"button.continue.tip.en": "Continue scanning the map area",
"button.continue.tip": "Continuar escaneando el área del mapa",
"button.stop.tip.en": "Stop scanning and return to the start position",
"button.stop.tip": "Parar escaneo y regresar a la posición de inicio",
"button.clear.tip.en": "Clear report and segment cache",
"button.clear.tip": "Borrar reporte y caché de segmento",
"button.clear.tip.red.en": "There are too many reported segments:\n 1. Click 'Show report' to generate the report.\n 2. Click this button to clear the report and start over.",
"button.clear.tip.red": "Existen demasiados segmentos reportados:\n 1. Pulse 'Muestre reporte' para generar el reporte.\n 2. Pulse este boton para borrar el reporte y comenzar de nuevo.",
"button.report.text.en": "Show report",
"button.report.text": "Muestra reporte",
"button.report.tip.en": "Apply the filter and generate HTML report in a new tab",
"button.report.tip": "Aplicar el filtro y generar un reporte en HTML en una nueva pestaña",
"button.BBreport.tip.en": "Share the report on Waze forum or in a private message",
"button.BBreport.tip": "Compartir el reporte en el Foro de Waze o en un Mensaje Privado",
"button.settings.tip.en": "Configure settings",
"button.settings.tip": "Configurar Ajustes",
"tab.custom.text.en": "custom",
"tab.custom.text": "Ajustes predefinidos",
"tab.custom.tip.en": "User-defined custom checks settings",
"tab.custom.tip": "Ajustes predefinidos por el usuario",
"tab.settings.text.en": "Settings",
"tab.settings.text": "Ajustes",
"tab.scanner.text.en": "scanner",
"tab.scanner.text": "scanner",
"tab.scanner.tip.en": "Map scanner settings",
"tab.scanner.tip": "Ajustes de escaneado del mapa",
"tab.about.text.en": "about</span>",
"tab.about.text": "Acerca de</span>",
"tab.about.tip.en": "About WME Validator",
"tab.about.tip": "Acerca del WME Validator",
"scanner.sounds.text.en": "Enable sounds",
"scanner.sounds.text": "Habilitar sonidos",
"scanner.sounds.tip.en": "Bleeps and the bloops while scanning",
"scanner.sounds.tip": "TODO: Sonidos mientras escanea",
"scanner.sounds.NA.en": "Your browser does not support AudioContext",
"scanner.sounds.NA": "Su navegador no soporta AudioContext",
"scanner.highlight.text.en": "Highlight issues on the map",
"scanner.highlight.text": "Resaltar problemas en el mapa",
"scanner.highlight.tip.en": "Highlight reported issues on the map",
"scanner.highlight.tip": "Resaltar problemas reportados en el mapa",
"scanner.slow.text.en": "Enable \"slow\" checks",
"scanner.slow.text": "Habilitar\"chequeos\" lentos",
"scanner.slow.tip.en": "Enables deep map analysis\n* Note: this option might slow down the scanning process",
"scanner.slow.tip": "Habilita análisis profundo del mapa\n* Nota: esta opción puede hacer lento el proceso de escaneo",
"scanner.ext.text.en": "Report external highlights",
"scanner.ext.text": "Reportar resaltados externos",
"scanner.ext.tip.en": "Report segments highlighted by WME Toolbox or WME Color Highlights",
"scanner.ext.tip": "Reportar segmentos resaltados por WME Toolbox o WME Color Highlights",
"advanced.atbottom.text.en": "At the bottom",
"advanced.atbottom.text": "Hasta abajo",
"advanced.atbottom.tip.en": "Put WME Validator at the bottom of the page",
"advanced.atbottom.tip": "Poner WME Validator en la parte de abajo de la página",
"custom.template.text.en": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Custom template</a>",
"custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Planilla Propia</a>",
"custom.template.tip.en": "User-defined custom check expandable template.\n\nYou may use the following expandable variables:\nAddress:\n${country}, ${state}, ${city}, ${street},\n${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nSegment properties:\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}\nHelpers:\n${drivable}, ${roundabout}, ${hasHNs},\n${Uturn}, ${deadEnd}, ${softTurns},\n${deadEndA}, ${partialA},\n${deadEndB}, ${partialB}\nConnectivity:\n${segmentsA}, ${inA}, ${outA}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.tip": "Checar con planilla expandible definida por el usuario.\n\nPuedes usar las siguientes variables de expansión:\nDirección:\n${country}, ${state}, ${city}, ${street},\n${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nPropiedades de segmentos:\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}\nAyudantes:\n${drivable}, ${roundabout}, ${hasHNs},\n${Uturn}, ${deadEnd}, ${softTurns},\n${deadEndA}, ${partialA},\n${deadEndB}, ${partialB}\nConnectivity:\n${segmentsA}, ${inA}, ${outA}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.example.en": "Example: ${street}",
"custom.template.example": "Ejemplo: ${street}",
"custom.regexp.text.en": "Custom <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
"custom.regexp.text": "TODO: Adaptar <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
"custom.regexp.tip.en": "User-defined custom check regular expression to match the template.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
"custom.regexp.tip": "TODO: Expresiones regulares definidas por el usuario para igualar a la planilla.\n\nCase-insensitive match: /regexp/i\nNegación (no igual a): !/regexp/\nInformación de debug en la consola: D/regexp/",
"custom.regexp.example.en": "Example: !/.+/",
"custom.regexp.example": "Ejemplo: !/.+/",
"about.tip.en": "Open link in a new tab",
"about.tip": "Abrir liga en una pestaña nueva",
"button.reset.text.en": "Reset defaults",
"button.reset.text": "Regresar a los ajustes originales",
"button.reset.tip.en": "Revert filter options and settings to their defaults",
"button.reset.tip": "Revertir las opciones de filtrado y ajustes a los originales",
"button.list.text.en": "Available checks...",
"button.list.text": "Revisiones disponibles...",
"button.list.tip.en": "Show a list of checks available in WME Validator",
"button.list.tip": "Mostrar una lista de revisiones disponibles en WME Validator",
"button.wizard.tip.en": "Create localization package",
"button.wizard.tip": "Crear un paquete de localización",
"button.back.text.en": "Back",
"button.back.text": "Regresar",
"button.back.tip.en": "Close settings and return to main view",
"button.back.tip": "Cerrar ajustes y regresar a la vista principal",
"1.title.en": "WME Toolbox: Roundabout which may cause issues",
"1.title": "WME Toolbox: Rotonda que puede causar problemas",
"1.problem.en": "Junction IDs of the roundabout segments are not consecutive",
"1.problem": "Los números de salida de los segmentos de la rotonda no son consecutivos",
"1.solution.en": "Redo the roundabout",
"1.solution": "Rehacer la rotonda",
"2.title.en": "WME Toolbox: Simple segment",
"2.title": "TODO: WME Toolbox: Simple segment",
"2.problem.en": "The segment has unneeded geometry nodes",
"2.problem": "El segmento tiene nodos geométricos innecesarios",
"2.solution.en": "Simplify segment geometry by hovering mouse pointer and pressing \"d\" key",
"2.solution": "Simplificar la geometría del segmento pasando el puntero encima del segmento y presionando la letra \"d\"",
"3.title.en": "WME Toolbox: Lvl 2 lock",
"3.title": "WME Toolbox: Bloqueo nivel 2",
"3.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"3.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"4.title.en": "WME Toolbox: Lvl 3 lock",
"4.title": "WME Toolbox: Bloqueo Nivel 3",
"4.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"4.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"5.title.en": "WME Toolbox: Lvl 4 lock",
"5.title": "WME Toolbox: Bloqueo nivel 4",
"5.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"5.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"6.title.en": "WME Toolbox: Lvl 5 lock",
"6.title": "WME Toolbox: Bloqueo nivel 5",
"6.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"6.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"7.title.en": "WME Toolbox: Lvl 6 lock",
"7.title": "WME Toolbox: Bloqueo nivel 6",
"7.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"7.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"8.title.en": "WME Toolbox: House numbers",
"8.title": "WME Toolbox: Numeración de Casas",
"8.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"8.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"9.title.en": "WME Toolbox: Segment with time restrictions",
"9.title": "WME Toolbox: Segmento con restricciones de tiempo",
"9.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"9.problem": "El segmento está resaltado por el WME Toolbox. No representa un problema",
"13.title.en": "WME Color Highlights: Editor lock",
"13.title": "WME Color Highlights: Bloqueo de un editor",
"13.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"13.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"14.title.en": "WME Color Highlights: Toll road / One way road",
"14.title": "WME Color Highlights: Vía de peaje / Vía de un sólo sentido",
"14.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"14.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"15.title.en": "WME Color Highlights: Recently edited",
"15.title": "WME Color Highlights: Recientemente editado",
"15.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"15.problem": "El segmento está resaltado por elWME Color Highlights. No representa un problema",
"16.title.en": "WME Color Highlights: Road rank",
"16.title": "WME Color Highlights: Rango de v",
"16.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"16.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"17.title.en": "WME Color Highlights: No city",
"17.title": "WME Color Highlights: Sin Ciudad",
"17.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"17.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"18.title.en": "WME Color Highlights: Time restriction / Highlighted road type",
"18.title": "WME Color Highlights: Restricción de tiempo / Tipo de camino resaltado",
"18.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"18.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"19.title.en": "WME Color Highlights: No name",
"19.title": "WME Color Highlights: Sin nombre",
"19.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"19.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"20.title.en": "WME Color Highlights: Filter by city",
"20.title": "WME Color Highlights: Filtrar por Ciudad",
"20.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"20.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"21.title.en": "WME Color Highlights: Filter by city (alt. city)",
"21.title": "WME Color Highlights: Filtrar por nombre alterno de Ciudad (alt. city)",
"21.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"21.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"22.title.en": "WME Color Highlights: Filter by editor",
"22.title": "WME Color Highlights: Filtrar por editor",
"22.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"22.problem": "El segmento está resaltado por el WME Color Highlights. No representa un problema",
"23.title.en": "Unconfirmed road",
"23.title": "Camino sin confirmar",
"23.problem.en": "Each segment must minimally have the Country and State information",
"23.problem": "Cada segmento debe contener como mínimo Información de Estado y País",
"23.solution.en": "Confirm the road by updating its details",
"23.solution": "Actualice el camino actualizando sus datos",
"24.enabled": false,
"24.title.en": "Might be incorrect city name (only available in the report)",
"24.title": "Puede contener un nombre de ciudad incorrecto (sólo disponible en el reporte)",
"24.problem.en": "The segment might have incorrect city name",
"24.problem": "El segmento puede contener el nombre de ciudad incorrecto",
"24.solution.en": "Consider suggested city name and use this form to rename the city",
"24.solution": "Considere el nombre de ciudad Sugerido y use esta forma para renombrar la ciudad",
"25.title.en": "Unknown direction of drivable road",
"25.title": "Sentido desconocido en un camino conducible",
"25.problem.en": "'Unknown' road direction will not prevent routing on the road",
"25.problem": "El sentido desconocido del segmento no prevendrá el ruteo por el mismo",
"25.solution.en": "Set the road direction",
"25.solution": "Coloque la dirección del segmento",
"28.title.en": "Street name on two-way Ramp",
"28.title": "Nombre de calle en una Rampa de doble sentido",
"28.problem.en": "If Ramp is unnamed, the name of a subsequent road will propagate backwards",
"28.problem": "Si una rampa no tiene nombre, se aplicará el nombre del siguiente camino que lo tenga",
"28.solution.en": "In the address properties check the 'None' box next to the street name and then click 'Apply'",
"28.solution": "En las propiedades de dirección, active la casilla de 'Ninguno' seguida del nombre de calle y entonces pulse 'Aplicar'",
"29.title.en": "Street name on roundabout",
"29.title": "Nombre de calle en rotonda",
"29.problem.en": "In Waze, we do not name roundabout segments",
"29.problem": "En Waze no se nombran los segmentos de las rotondas",
"29.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout",
"29.solution": "En las propiedades de dirección, seleccione la opción 'Ninguno' en seguida del nombre de calle, pulse 'Aplicar' y entonces añada un 'lugar' de tipo 'distribuidor vial' y escriba el nombre de la glorieta",
"34.title.en": "Empty alternate street",
"34.title": "Vaciar el nombre alterno de calle",
"34.problem.en": "Alternate street name is empty",
"34.problem": "El nombre alterno de calle está vacío",
"34.solution.en": "Remove empty alternate street name",
"34.solution": "Quitar los nombres alternos de calle vacíos",
"35.title.en": "Unterminated drivable road",
"35.title": "Camino conducible no terminado",
"35.problem.en": "Waze will not route from the unterminated segment",
"35.problem": "Waze no otorgará rutas por segmentos sin terminar",
"35.solution.en": "Move the segment a bit so the terminating node will be added automatically",
"35.solution": "Mueva un poco el segmento para que el nodo se añada de manera automática",
"38.title.en": "Expired segment restriction (slow)",
"38.title": "Restricción de segmento vencida (no grave)",
"38.problem.en": "The segment has an expired restriction",
"38.problem": "El segmento tiene una restricción que ya venció",
"38.solution.en": "Click 'Edit restrictions' and delete the expired restriction",
"38.solution": "Pulsar 'Editar restricciones' y borrar las restricciones vencidas",
"39.title.en": "Expired turn restriction (slow)",
"39.title": "Restricción de giro vencida (no grave)",
"39.problem.en": "The segment has a turn with an expired restriction",
"39.problem": "El segmento tiene un giro con restricció vencida",
"39.solution.en": "Click clock icon next to the yellow arrow and delete the expired restriction",
"39.solution": "Pulsar la figura del reloj en seguida de la flecha amarilla y borre las restricciones vencidas",
"41.enabled": false,
"41.title.en": "Node A: Reverse connectivity of drivable road",
"41.title": "Conectividad reversible en un segmento conducible",
"41.problem.en": "There is a turn which goes against the directionality of the segment at node A",
"41.problem": "Existe un giro que va contra la dirección del segmento en el nodo A",
"41.solution.en": "Make the segment 'Two-way', restrict all the turns at node A and then make the segment 'One way (A→B)' again",
"41.solution": "Haga el segmento de 'doble sentido', restrinja todos los giros en el nodo A y luego haga el segmento de 'Un sólo sentido (A-B) de nuevo",
"42.enabled": false,
"42.title.en": "Node B: Reverse connectivity of drivable road",
"42.title": "Nodo B: Conectividad reversible en segmento conducible",
"42.problem.en": "There is a turn which goes against the directionality of the segment at node B",
"42.problem": "Existe un giro que va en contra de la dirección del segmento en el nodo B",
"42.solution.en": "Make the segment 'Two-way', restrict all the turns at node B and then make the segment 'One way (B→A)' again",
"42.solution": "Haga el segmento de 'doble sentido', restrinja todos los giros en el nodo A y luego haga el segmento de 'Un sólo sentido (A-B) de nuevo",
"43.title.en": "Self connectivity",
"43.title": "Auto Conectividad",
"43.problem.en": "The segment is connected back to itself",
"43.problem": "El segmento está conectado en sí mismo",
"43.solution.en": "Split the segment into THREE pieces",
"43.solution": "Divida el segmento en tres",
"46.title.en": "Node A: No inward connectivity of drivable road (slow)",
"46.title": "Nodo A: No existe conectividad hacia adentro del camino conducible",
"46.problem.en": "The drivable non-private segment has no single inward turn enabled at node A",
"46.problem": "El segmento conducible no privado no tiene ningún giro permitido en el nodo A",
"46.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node A",
"46.solution": "Seleccione un segmento adyacente y active por lo menos un giro al segmento en el nodo A",
"47.title.en": "Node B: No inward connectivity of drivable road (slow)",
"47.title": "Nodo B: No existe conectividad hacia adentro del camino conducible (no grave) ",
"47.problem.en": "The drivable non-private segment has no single inward turn enabled at node B",
"47.problem": "El segmento conducible no privado no tiene ningún giro permitido en el nodo B",
"47.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node B",
"47.solution": "Seleccione un segmento adyacente y active por lo menos un giro al segmento en el nodo B",
"48.title.en": "Two-way drivable roundabout segment",
"48.title": "Segmento de glorieta de doble sentido",
"48.problem.en": "The drivable roundabout segment is bidirectional",
"48.problem": "El segmento de la glorieta es bidireccional",
"48.solution.en": "Redo the roundabout",
"48.solution": "Rehacer la glorieta",
"78.title.en": "Same endpoints drivable segments (slow)",
"78.title": "El segmento que creó comienza y termina en un mismo segmento",
"78.problem.en": "Two drivable segments share the same two endpoints",
"78.problem": "Los dos segmentos comparten los mismos puntos finales",
"78.solution.en": "Split the segment. You might also remove one of the segments if they are identical",
"78.solution": "Parta el segmento. Puede también remover uno de ellos si son idénticos",
"87.title.en": "Node A: Multiple outgoing segments at roundabout",
"87.title": "Múltiples segmentos de salida de la glorieta en el nodo A",
"87.problem.en": "The drivable roundabout node A has more than one outgoing segment connected",
"87.problem": "El nodo A en la glorieta tiene más de un segmento de salida conectado",
"87.solution.en": "Redo the roundabout",
"87.solution": "Re hacer la glorieta",
"99.title.en": "U-turn at roundabout entrance (slow)",
"99.title": "Vuelta en U habilitada en segmento de entrada a la glorieta (no grave)",
"99.problem.en": "The roundabout entrance segment has a U-turn enabled",
"99.problem": "El segmento de entrada a la glorieta tiene una vuelta en U habilitada",
"99.solution.en": "Disable U-turn",
"99.solution": "Deshabilite la vuelta en U",
"101.enabled": false,
"101.title.en": "Closed road (only available in the report)",
"101.title": "Camino Cerrado (Sólo disponible en el reporte)",
"101.problem.en": "The segment is marked as closed",
"101.problem": "El segmento está marcado como Cerrado",
"101.solution.en": "If the construction is done, restore the segment connectivity and remove the suffix",
"101.solution": "Si la construcción ya terminó, reactive la conectividad del segmento y remueva el sufijo",
"102.title.en": "Node A: No outward connectivity of drivable road (slow)",
"102.title": "No existe conectividad hacia afuera del segmento en el nodo A (no grave)",
"102.problem.en": "The drivable segment has no single outward turn enabled at node A",
"102.problem": "El segmento no tiene habilitado ningún giro hacia afuera en el nodo A",
"102.solution.en": "Enable at least one outward turn from the segment at node A",
"102.solution": "Permita por lo menos un giro hacia el segmento en el nodo A",
"103.title.en": "Node B: No outward connectivity of drivable road (slow)",
"103.title": "No existe conectividad hacia afuera en el nodo B (no grave))",
"103.problem.en": "The drivable segment has no single outward turn enabled at node B",
"103.problem": "El segmento no tiene habilitado ningún giro hacia afuera en el nodo B",
"103.solution.en": "Enable at least one outward turn from the segment at node B",
"103.solution": "Permita por lo menos un giro desde el segmento en el nodo B",
"104.enabled": false,
"104.title.en": "Railroad used for comments",
"104.title": "Segmento tipo ferrocarril usado para comentarios",
"104.problem.en": "The Railroad segment is probably used as a map comment",
"104.problem": "El segmentotipo ferrocarril etá siendo usado probablemente para comentarios del mapa",
"104.solution.en": "Remove the comment as Railroads will be added to the client display",
"104.solution": "Remover los comentarios ya que las vías férreas se verán en la aplicación",
"107.title.en": "Node A: No connection (slow)",
"107.title": "No hay conexion del Nodo A (no grave)",
"107.problem.en": "The node A of the drivable segment is within 5m from another drivable segment but not connected by a junction",
"107.problem": "El Nodo A del segmento está a dentro del rango de 5m de otro segmento pero no está conectado por una intersección",
"107.solution.en": "Drag the node A to the nearby segment so that it touches or move it a bit further away",
"107.solution": "Arrastre el nodo A al segmento más cercano de modo que se junten, o muévalo un poco más lejos.",
"108.title.en": "Node B: No connection (slow)",
"108.title": "No hay conexión en el nodo B (no grave)",
"108.problem.en": "The node B of the drivable segment is within 5m from another drivable segment but not connected by a junction",
"108.problem": "El nodo B del segmento está dentro del rango de 5m de otro segmento pero no está conectado por una intersección",
"108.solution.en": "Drag the node B to the nearby segment so that it touches or move it a bit further away",
"108.solution": "Arrastre el nodo B al segmento más cercano de modo que lo toque o muévalo un poco más lejos",
"109.title.en": "Too short segment",
"109.title": "Segmento muy corto",
"109.problem.en": "The drivable non-terminal segment is less than ${n}m long so it is hard to see it on the map and it can cause routing problems",
"109.problem": "El segmento es de menos de ${n}m de largo, por lo que es difícil verlo en el mapa y puede causar problemas de ruteo",
"109.solution.en": "Increase the length, or remove the segment, or join it with one of the adjacent segments",
"109.solution": "Aumente el largo del segmento, remuévalo o llévelo al nodo del segmento adyacente",
"112.title.en": "Too long Ramp name",
"112.title": "Nombre de rampa demasiado largo",
"112.problem.en": "The Ramp name is more than ${n} letters long",
"112.problem": "El nombre de la rampa tiene más de ${n} letras",
"112.solution.en": "Shorten the Ramp name",
"112.solution": "Acorte el nombre de la rampa",
"116.title.en": "Out of range elevation",
"116.title": "Elevación fuera de rango",
"116.problem.en": "The segment elevation is out of range",
"116.problem": "La elevación del segmento está fuera de rango",
"116.solution.en": "Correct the elevation",
"116.solution": "Corrija la elevación",
"117.enabled": false,
"117.title.en": "Obsolete CONST ZN marker",
"117.title": "Marcador de Zona de Construcción obsoleto",
"117.problem.en": "The segment is marked with obsolete CONST ZN suffix",
"117.problem": "El segmento está marcado con un sufijo de Zona de Construcción obsoleto",
"117.solution.en": "Change CONST ZN to (closed)",
"117.solution": "Cambie el CONST ZN a (cerrado)",
"118.title.en": "Node A: Overlapping segments (slow)",
"118.title": "En el Nodo A: Segmentos encimados (no grave)",
"118.problem.en": "The segment is overlapping with the adjacent segment at node A",
"118.problem": "El segmento está encimado con el segmento adyacente en el nodo A",
"118.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node A",
"118.solution": "Abra los segmentos a 2°, borre el punto geométrico o el segmento duplicado en el nodo A",
"119.title.en": "Node B: Overlapping segments (slow)",
"119.title": "Nodo B: Segmentos encimados",
"119.problem.en": "The segment is overlapping with the adjacent segment at node B",
"119.problem": "El segmento está encimado con el segmento adyacente en el nodoB",
"119.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node B",
"119.solution": "Abra los segmentos a 2°, borre el punto geométrico o el segmento duplicado en el nodo B",
"120.title.en": "Node A: Too sharp turn (slow)",
"120.title": "Nodo A: Giro demasiado cerrado (no grave)",
"120.problem.en": "The drivable segment has a very acute turn at node A",
"120.problem": "El segmento conducible tiene un ángulo de giro muy cerrado en el nodo A",
"120.solution.en": "Disable the sharp turn at node A or spread the segments at 30°",
"120.solution": "Prohíba la vuelta cerrada en el nodo A o abra los segmentos a 30°",
"121.title.en": "Node B: Too sharp turn (slow)",
"121.title": "Nodo B: Giro demasiado cerrado (no grave)",
"121.problem.en": "The drivable segment has a very acute turn at node B",
"121.problem": "El segmento conducible tiene un ángulo de giro muy cerrado en el nodo B",
"121.solution.en": "Disable the sharp turn at node B or spread the segments at 30°",
"121.solution": "Prohíba la vuelta cerrada en el nodo B o abra los segmentos a 30°",
"128.title.en": "User-defined custom check (green)",
"128.title": "Revisión definida por el usuario (verde)",
"128.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
"128.problem": "Algunas propiedades del segmento van en contra de la expresión regular definida por el usuario (ver Settings→Custom)",
"128.solution.en": "Solve the issue",
"128.solution": "Resuelva el problema",
"129.title.en": "User-defined custom check (blue)",
"129.title": "Revisión definida por el usuario (azúl)",
"129.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
"129.problem": "Algunas propiedades del segmento van en contra de la expresión regular definida por el usuario (ver Settings→Custom)",
"129.solution.en": "Solve the issue",
"129.solution": "Resuelva el problema",
"150.enabled": false,
"151.enabled": false,
"152.enabled": false,
"172.title.en": "Unneeded spaces in street name",
"172.title": "Espacios innecesarios en el nombre de calle",
"172.problem.en": "Leading/trailing/double space in the street name",
"172.problem": "TODO: Leading/trailing/el espacio doble en el nombre de la calle",
"172.solution.en": "Remove unneeded spaces from the street name",
"172.solution": "Eliminar espacios innecesarios del nombre de la calle",
"173.enabled": false,
"173.title.en": "No space before/after street abbreviation",
"173.title": "No hay espacio antes/después de la abreviatura en el nombre de calle",
"173.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the street name",
"173.problem": "No hay espacio antes de ('1943r.') o después ('Sn.Juan') de una abreviatura en el nombre de calle",
"173.solution.en": "Add a space before/after the abbreviation",
"173.solution": "Añadir un espacio antes/después de la abreviatura",
"175.title.en": "Empty street name",
"175.title": "Nombre de calle vacío",
"175.problem.en": "The street name has only space characters or a dot",
"175.problem": "El nombre de la calle tiene solamente espacios o un punto",
"175.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' OR set a proper street name",
"175.solution": "En las propiedades de la dirección, elija la casilla 'Ninguno' enseguida de 'nombre' o escriba el nombre de la Calle. Presione 'Aplicar'",
"190.enabled": false,
"190.title.en": "Lowercase city name",
"190.title": "Nombre de ciudad en minúsculas",
"190.problem.en": "The city name starts with a lowercase letter",
"190.problem": "El nombre de la ciudad comienza con minúscula",
"190.solution.en": "Use this form to rename the city",
"190.solution": "Use esta forma para renombrar la ciudad",
"192.enabled": false,
"192.title.en": "Unneeded spaces in city name",
"192.title": "Espacios innecesarios en el nombre de ciudad",
"192.problem.en": "Leading/trailing/double space in the city name",
"192.problem": "TODO: Leading/trailing/el espacio doble en el nombre de ciudad",
"192.solution.en": "Use this form to rename the city",
"192.solution": "Use esta forma para renombrar la ciudad",
"193.enabled": false,
"193.title.en": "No space before/after city abbreviation",
"193.title": "No hay espacios antes/después de la abreviatura de la Ciudad",
"193.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the city name",
"193.problem": "No hay espacio antes ('1943r.') o después ('Sn.Juan') de una abreviatura en el nombre de ciudad",
"193.solution.en": "Use this form to rename the city",
"193.solution": "Use esta forma para renombrar la ciudad",
"200.enabled": false,
"200.title.en": "Node A: Unconfirmed turn on minor road",
"200.title": "En el nodo A: Giro no confirmado en un camino menor",
"200.problem.en": "The minor drivable segment has an unconfirmed (soft) turn at node A",
"200.problem": "El segmento del camino menor tiene un giro no confirmado (suave) en el nodo A",
"200.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
"200.solution": "Pulse en la flecha de giro indicada con un signo de interrogación morado para confirmarla. Nota: Puede ser necesario hacer el segmento de doble sentido para poder ver dichos giros",
"201.enabled": false,
"201.title.en": "Node A: Unconfirmed turn on primary road",
"201.title": "En el nodo A: Giro no confirmado en una vía primaria",
"201.problem.en": "The primary segment has an unconfirmed (soft) turn at node A",
"201.problem": "El segmento de vía primaria tiene un giro no confirmado (suave) en el nodo A",
"201.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
"201.solution": "Pulse en la flecha de giro indicada con un signo de interrogación morado para confirmarla. Nota: Puede ser necesario hacer el segmento de doble sentido para poder ver dichos giros",
"202.title.en": "BETA: No public connection for public segment (slow)",
"202.title": "TODO: BETA: No public connection for public segment (slow)",
"202.problem.en": "The public segement is not connected to any other public segment",
"202.problem": "TODO: The public segement is not connected to any other public segment",
"202.solution.en": "Verify if the segment is meant to be a public accessible segment, or it should be changed to a private segment",
"202.solution": "TODO: Verify if the segment is meant to be a public accessible segment, or it should be changed to a private segment",
"202.enabled": false,
"210.title.en": "Segment has unverified speed limits from A to B",
"210.title": "TODO: Segment has unverified speed limits from A to B",
"210.problem.en": "Segment has speed limit set from A to B that is unverified",
"210.problem": "TODO: Segment has speed limit set from A to B that is unverified",
"210.solution.en": "Verify the speed limit on the segment and confirm or correct it",
"210.solution": "TODO: Verify the speed limit on the segment and confirm or correct it",
"211.title.en": "Segment has unverified speed limits from B to A",
"211.title": "TODO: Segment has unverified speed limits from B to A",
"211.problem.en": "Segment has speed limit set from B to A that is unverified",
"211.problem": "TODO: Segment has speed limit set from B to A that is unverified",
"211.solution.en": "Verify the speed limit on the segment and confirm or correct it",
"211.solution": "TODO: Verify the speed limit on the segment and confirm or correct it",
"212.title.en": "Segment has no speed limit set from A to B",
"212.title": "TODO: Segment has no speed limit set from A to B",
"212.problem.en": "Segment has no speed limit set from A to B",
"212.problem": "TODO: Segment has no speed limit set from A to B",
"212.solution.en": "Verify the speed limit on the segment and set it",
"212.solution": "TODO: Verify the speed limit on the segment and set it",
"213.title.en": "Segment has no speed limit set from B to A",
"213.title": "TODO: Segment has no speed limit set from B to A",
"213.problem.en": "Segment has no speed limit set from B to A",
"213.problem": "TODO: Segment has no speed limit set from B to A",
"213.solution.en": "Verify the speed limit on the segment and set it",
"213.solution": "TODO: Verify the speed limit on the segment and set it",
"214.title.en": "Segment has possibly wrong speed limit from A to B",
"214.title": "TODO: Segment has possibly wrong speed limit from A to B",
"214.problem.en": "Segment has a speed limit that seems to be incorrect",
"214.problem": "TODO: Segment has a speed limit that seems to be incorrect",
"214.solution.en": "Verify the speed limit on the segment and correct it if needed",
"214.solution": "TODO: Verify the speed limit on the segment and correct it if needed",
"215.title.en": "Segment has possibly wrong speed limit from B to A",
"215.title": "TODO: Segment has possibly wrong speed limit from B to A",
"215.problem.en": "Segment has a speed limit that seems to be incorrect",
"215.problem": "TODO: Segment has a speed limit that seems to be incorrect",
"215.solution.en": "Verify the speed limit on the segment and correct it if needed",
"215.solution": "TODO: Verify the speed limit on the segment and correct it if needed"
