".country": "Netherlands",
".author": "davidakachaos",
".updated": "2018-08-01",
".fallbackCode": "BE",
".lng": "NL",
"city.consider.en": "consider this city name:",
"city.consider": "overweeg deze plaatsnaam:",
"city.1.en": "city name is too short",
"city.1": "plaatsnaam te kort",
"city.2.en": "expand the abbreviation",
"city.2": "De afkorting uitbreiden",
"city.3.en": "complete short name",
"city.3": "maak de korte naam compleet",
"city.4.en": "complete city name",
"city.4": "plaatsnaam aanvullen",
"city.5.en": "correct letter case",
"city.5": "juist hoofdlettergebruik",
"city.6.en": "check word order",
"city.6": "controleer woord volgorde",
"city.7.en": "check abbreviations",
"city.7": "controleer afkortingen",
"city.8a.en": "add county name",
"city.8a": "land naam toevoegen",
"city.8r.en": "remove county name",
"city.8r": "land naam verwijderen",
"city.9.en": "check county name",
"city.9": "controleer land naam",
"city.10a.en": "add a word",
"city.10a": "woord toevoegen",
"city.10r.en": "remove a word",
"city.10r": "woord verwijderen",
"city.11.en": "add county code",
"city.11": "landcode toevoegen",
"city.12.en": "identical names, but different city IDs",
"city.12": "identieke namen, maar verschillende plaats IDs",
"city.13a.en": "add a space",
"city.13a": "spatie invoegen",
"city.13r.en": "remove a space",
"city.13r": "spatie verwijderen",
"city.14.en": "check the number",
"city.14": "controleer het nummer",
"props.skipped.title.en": "The segment is not checked",
"props.skipped.title": "Dit segment is niet gecontroleerd",
"props.skipped.problem.en": "The segment is modified after 2014-05-01 AND locked for you, so Validator did not check it",
"props.skipped.problem": "Dit segment is na 2014-05-01 aangepast EN voor jou gelockt, Validator heeft dit niet gecontroleerd",
"err.regexp.en": "Error parsing option for check #${n}:",
"err.regexp": "Fout bij het verwerken van de opties voor de controle #${n}:",
"props.disabled.en": "WME Validator is disabled",
"props.disabled": "WME Validator is uitgeschakeld",
"props.limit.title.en": "Too many issues reported",
"props.limit.title": "Te veel problemen gevonden",
"props.limit.problem.en": "There are too many issues reported, so some of them might not be shown",
"props.limit.problem": "Er zijn te veel problemen gemeld, daarom wordt een aantal van hen niet getoond",
"props.limit.solution.en": "Deselect the segment and stop scanning process. Then click red '✘' (Clear report) button",
"props.limit.solution": "Deselecteer het segment en stop het scanproces. Klik dan op de rode '✘' (Clear report) knop",
"props.reports.en": "reports",
"props.reports": "meldingen",
"props.noneditable.en": "You cannot edit this segment",
"props.noneditable": "Je kunt dit segment niet bewerken",
"report.save.en": "Save this report",
"report.save": "Sla dit rapport op",
"report.list.andUp.en": "and up",
"report.list.andUp": "en meer",
"report.list.severity.en": "Severity:",
"report.list.severity": "Hevigheid:",
"report.list.reportOnly.en": "only in report",
"report.list.reportOnly": "alleen in rapportage",
"report.list.forEditors.en": "For editors level:",
"report.list.forEditors": "Voor bewerkers niveau:",
"report.list.forCountries.en": "For countries:",
"report.list.forCountries": "Voor landen:",
"report.list.forStates.en": "For states:",
"report.list.forStates": "Voor provincies:",
"report.list.forCities.en": "For cities:",
"report.list.forCities": "Voor steden:",
"report.list.params.en": "Params to configure in localization pack:",
"report.list.params": "Parameters om te configureren in lokalisatie:",
"report.list.params.set.en": "Current configuration for ${country}:",
"report.list.params.set": "Huidige configuratie voor ${country}:",
"report.list.enabled.en": "${n} checks are enabled for",
"report.list.enabled": "${n} controles zijn actief voor",
"report.list.disabled.en": "${n} checks are disabled for",
"report.list.disabled": "${n} controles zijn uitgeschakeld voor",
"report.list.total.en": "There are ${n} checks available",
"report.list.total": "Er zijn ${n} controles beschikbaar",
"report.list.title.en": "Complete List of Checks for",
"report.list.title": "Complete lijst met controles voor",
"report.list.see.en": "See",
"report.list.see": "Zie",
"report.list.checks.en": "Settings->About->Available checks",
"report.list.checks": "Instellingen->Over->Beschikbare controles",
"report.list.fallback.en": "Localization Fallback Rules:",
"report.list.fallback": "Lokalisatie terugval regels:",
"report.and.en": "and",
"report.and": "en",
"report.segments.en": "Total number of segments checked:",
"report.segments": "Totaal aantal gecontroleerde segmenten:",
"report.customs.en": "Custom checks matched (green/blue):",
"report.customs": "Er is een match aangepaste controles (groen/blauw):",
"report.reported.en": "Reported",
"report.reported": "Gerapporteerd",
"report.errors.en": "errors",
"report.errors": "fouten",
"report.warnings.en": "warnings",
"report.warnings": "waarschuwingen",
"report.notes.en": "notes",
"report.notes": "notities",
"report.link.wiki.en": "wiki",
"report.link.wiki": "wiki",
"report.link.forum.en": "forum",
"report.link.forum": "forum",
"report.link.other.en": "link",
"report.link.other": "link",
"report.contents.en": "Contents:",
"report.contents": "Inhoud:",
"report.summary.en": "Summary",
"report.summary": "Samenvatting",
"report.title.en": "WME Validator Report",
"report.title": "WME Validator Rapport",
"report.share.en": "to Share",
"report.share": "om te delen",
"report.generated.by.en": "generated by",
"report.generated.by": "gegenereerd door",
"report.generated.on.en": "on",
"report.generated.on": "op",
"report.source.en": "Report source:",
"report.source": "Rapportbron:",
"report.filter.duplicate.en": "duplicate segments",
"report.filter.duplicate": "dubbele segmenten",
"report.filter.streets.en": "Streets and Service Roads",
"report.filter.streets": "Straten en dienstwegen",
"report.filter.other.en": "Other drivable and Non-drivable",
"report.filter.other": "Andere berijdbare en niet berijdbare",
"report.filter.noneditable.en": "non-editable segments",
"report.filter.noneditable": "niet-bewerkbare segmenten",
"report.filter.notes.en": "notes",
"report.filter.notes": "notities",
"report.filter.title.en": "Filter:",
"report.filter.title": "Filter:",
"report.filter.excluded.en": "are excluded from this report.",
"report.filter.excluded": "zijn uitgezonderd van dit rapport.",
"report.search.updated.by.en": "updated by",
"report.search.updated.by": "bijgewerkt door",
"report.search.updated.since.en": "updated since",
"report.search.updated.since": "bijgewerkt sinds",
"report.search.city.en": "from",
"report.search.city": "van",
"report.search.reported.en": "reported as",
"report.search.reported": "gemeld",
"report.search.title.en": "Search:",
"report.search.title": "Zoeken:",
"report.search.only.en": "only segments",
"report.search.only": "alleen segmenten",
"report.search.included.en": "are included into the report.",
"report.search.included": "zijn opgenomen in het rapport.",
"report.beta.warning.en": "WME Beta Warning!",
"report.beta.warning": "WME Beta Waarschuwing!",
"report.beta.text.en": "This report is generated in beta WME with beta permalinks.",
"report.beta.text": "Dit rapport is gegenereerd in beta WME met bèta permalinks.",
"report.beta.share.en": "Please do not share those permalinks!",
"report.beta.share": "Gelieve deze permalinks niet te delen!",
"report.size.warning.en": "<b>Warning!</b><br>The report is ${n} characters long so <b>it will not fit</b> into a single forum or private message.\n<br>Please add <b>more filters</b> to reduce the size of the report.",
"report.size.warning": "<b>Waarschuwing!</b><br>Het rapport is ${n} tekens lang dus <b>het zal niet passen</b> in één forum of privé bericht.\n<br>Voeg aub <b>meer filters</b> toe om de grootte van het rapport te beperken.",
"report.note.limit.en": "* Note: there were too many issues reported, so some of them are not counted in the summary.",
"report.note.limit": "* Let op: er waren te veel problemen gemeld, zodat een aantal van hen worden niet meegeteld in de samenvatting.",
"report.forum.en": "To motivate further development please leave your comment on the",
"report.forum": "Om verdere ontwikkeling te motiveren laat dan je commentaar achter op de",
"report.forum.link.en": "Waze forum thread.",
"report.forum.link": "Waze forum thread.",
"report.thanks.en": "Thank you for using WME Validator!",
"report.thanks": "Dank u voor het gebruik van de WME Validator!",
"msg.limit.segments.en": "There are too many segments.\n\nClick 'Show report' to review the report, then\n",
"msg.limit.segments": "Er zijn te veel segmenten.\n\nKlik op 'Toon rapport' om het rapport door te nemen, vervolgens\n",
"msg.limit.segments.continue.en": "click '▶' (Play) to continue.",
"msg.limit.segments.continue": "klik '▶' (Play) om verder te gaan.",
"msg.limit.segments.clear.en": "click '✘' (Clear) to clear the report.",
"msg.limit.segments.clear": "klik '✘' (Löschen) om het rapport te verwijderen.",
"msg.pan.text.en": "Pan around to validate the map",
"msg.pan.text": "Schuif de kaart rond om de kaart te valideren",
"msg.zoomout.text.en": "Zoom out to start WME Validator",
"msg.zoomout.text": "Uitzoomen om WME Validator te beginnen",
"msg.click.text.en": "Click '▶' (Play) to validate visible map area",
"msg.click.text": "Klik '▶' (Play), om het zichtbare gebied op de kaart te valideren",
"msg.autopaused.en": "autopaused",
"msg.autopaused": "automatisch gepauzeerd",
"msg.autopaused.text.en": "Auto paused! Click '▶' (Play) to continue.",
"msg.autopaused.text": "Automatisch gepauzeerd! Om door te gaan klik op '▶' (Play).",
"msg.autopaused.tip.en": "WME Validator automatically paused on map drag or window size change",
"msg.autopaused.tip": "WME Validator is automatisch onderbroken wegen het verschuiven van de kaart of door een aanpassing van de venstergrootte",
"msg.finished.text.en": "Click <b>'Show report'</b> to review map issues",
"msg.finished.text": "Klik <b>'Toon rapport'</b> om kaart problemen te beoordelen",
"msg.finished.tip.en": "Click '✉' (Share) button to post report on a\nforum or in a private message",
"msg.finished.tip": "Klik op '✉' (Delen) om het rapport op een\nforum of privebericht te plaatsen",
"msg.noissues.text.en": "Finished! No issues found!",
"msg.noissues.text": "Klaar! Geen problemen gevonden!",
"msg.noissues.tip.en": "Try to uncheck some filter options or start WME Validator over another map area!",
"msg.noissues.tip": "Probeer een aantal filteropties uit te vinken of start WME Validator over een ander gebied op de kaart!",
"msg.scanning.text.en": "Scanning! Finishing in ~ ${n} min",
"msg.scanning.text": "Scannen! Klaar over ~ ${n} min",
"msg.scanning.text.soon.en": "Scanning! Finishing in a minute!",
"msg.scanning.text.soon": "Scannen! Klaar binnen een minuut!",
"msg.scanning.tip.en": "Click 'Pause' button to pause or '■' (Stop) to stop",
"msg.scanning.tip": "Klik op 'pauze' knop om te pauzeren of '■' (Stop) om te stoppen",
"msg.starting.text.en": "Starting! Layers are off to scan faster!",
"msg.starting.text": "Begonnen! Layers zijn uitgeschakeld om sneller te scannen!",
"msg.starting.tip.en": "Use 'Pause' button to pause or '■' button to stop",
"msg.starting.tip": "Gebruik de 'Pause' knop om te pauzeren of '■' knop om te stoppen",
"msg.paused.text.en": "On pause! Click '▶' (Play) button to continue.",
"msg.paused.text": "Gepauzeerd! Klik op '▶' (Play) knop om door te gaan.",
"msg.paused.tip.en": "To view the report click 'Show report' button (if available)",
"msg.paused.tip": "Om het rapport te bekijken klik je op de 'Toon rapport' knop (indien beschikbaar)",
"msg.continuing.text.en": "Continuing!",
"msg.continuing.text": "Doorgaan!",
"msg.continuing.tip.en": "WME Validator will continue from the location it was paused",
"msg.continuing.tip": "WME Validator zal doorgaan van de locatie waar het werd onderbroken",
"msg.settings.text.en": "Click <b>'Back'</b> to return to main view",
"msg.settings.text": "Klik <b>'Terug'</b> om terug te keren naar hoofdweergave",
"msg.settings.tip.en": "Click 'Reset defaults' button to reset all settings in one click!",
"msg.settings.tip": "Klik op 'Herstel standaardinstellingen' knop om alle instellingen in één klik resetten!",
"msg.reset.text.en": "All filter options and settings have been reset to their defaults",
"msg.reset.text": "Alle filter opties en instellingen zijn terug gezet naar de standaardwaarden",
"msg.reset.tip.en": "Click 'Back' button to return to main view",
"msg.reset.tip": "Klik <b>'Terug'</b> om terug te keren naar de hoofdweergave",
"msg.textarea.pack.en": "This is a Greasemonkey/Tampermonkey script. You can copy and paste the text below into a <b>new .user.js file</b><br>or <b>paste it directly</b> into the Greasemonkey/Tampermonkey",
"msg.textarea.pack": "Dit is een Greasemonkey/Tampermonkey script. Je kunt onderstaande tekst kopieren en plakken in een <b>nieuw .user.js</b>of <b>plak het direct</b> in Greasemonkey/Tampermonkey",
"msg.textarea.en": "Please copy the text below and then paste it into your forum post or private message",
"msg.textarea": "Kopieer de onderstaande tekst en plak deze in je forum post of privebericht",
"noaccess.text.en": "<b>Sorry,</b><br>You cannot use WME Validator over here.<br>Please check <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>the forum thread</a><br>for more information.",
"noaccess.text": "<b>Sorry,</b><br>Hier kan je de WME Validator niet gebruiken.<brMeer informatie vind je <a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">deze forum thread</a><br>.",
"noaccess.tip.en": "Please check the forum thread for more information!",
"noaccess.tip": "Controleer de forum thread voor meer informatie!",
"tab.switch.tip.on.en": "Click to switch highlighting on (Alt+V)",
"tab.switch.tip.on": "Klik om het markeren aan te schakelen (Alt + V)",
"tab.switch.tip.off.en": "Click to switch highlighting off (Alt+V)",
"tab.switch.tip.off": "Klik om het markeren uit te schakelen (Alt+V)",
"tab.filter.text.en": "filter",
"tab.filter.text": "filter",
"tab.filter.tip.en": "Options to filter the report and highlighted segments",
"tab.filter.tip": "Opties om het rapport te filteren en gemarkeerd segmenten",
"tab.search.text.en": "search",
"tab.search.text": "zoeken",
"tab.search.tip.en": "Advanced filter options to include only specific segments",
"tab.search.tip": "Geavanceerde filteropties om alleen specifieke segmenten op te nemen",
"tab.help.text.en": "help",
"tab.help.text": "help",
"tab.help.tip.en": "Need help?",
"tab.help.tip": "Hulp nodig?",
"filter.noneditables.text.en": "Exclude <b>non-editable</b> segments",
"filter.noneditables.text": "Negeer <b>niet-bewerkbare</b> segmenten",
"filter.noneditables.tip.en": "Do not report locked segments or\nsegments outside of your editable areas",
"filter.noneditables.tip": "Rapporteer geen beveiligde segmenten of\nsegmenten buiten het gebied waar je mag bewerken",
"filter.duplicates.text.en": "Exclude <b>duplicate</b> segments",
"filter.duplicates.text": "<b>Dubbele</b> segmenten uitsluiten",
"filter.duplicates.tip.en": "Do not show the same segment in different\nparts of report\n* Note: this option DOES NOT affect highlighting",
"filter.duplicates.tip": "Toon hetzelfde segment niet in verschillende\ndelen van het rapport\n* Opmerking: deze optie HEEFT GEEN invloed op het markeren",
"filter.streets.text.en": "Exclude <b>Streets and Service Roads</b>",
"filter.streets.text": "Negeer <b>wegen en dienstwegen</b>",
"filter.streets.tip.en": "Do not report Streets and Service Roads",
"filter.streets.tip": "Neem wegen en dienstwegen niet op in het rapport",
"filter.other.text.en": "Exclude <b>Other drivable and Non-drivable</b>",
"filter.other.text": "Negeer <b>Andere berijdbare en niet-berijdbare</b> segmenten",
"filter.other.tip.en": "Do not report Dirt, Parking Lot, Private Roads\nand non-drivable segments",
"filter.other.tip": "Niet melden van onverharde, parkeerplaats, privéwegen\n en niet-berijdbare segmenten",
"filter.notes.text.en": "Exclude <b>notes</b>",
"filter.notes.text": "Negeer <b>opmerkingen</b>",
"filter.notes.tip.en": "Report only warnings and errors",
"filter.notes.tip": "Rapporteer alleen waarschuwingen en fouten",
"search.youredits.text.en": "Include <b>only your edits</b>",
"search.youredits.text": "Toon <b>enkel eigen aanpassingen</b>",
"search.youredits.tip.en": "Include only segments edited by you",
"search.youredits.tip": "Omvat slechts segmenten bewerkt door u",
"search.updatedby.text.en": "<b>Updated by*:</b>",
"search.updatedby.text": "<b>Aangepast door*:</b>",
"search.updatedby.tip.en": "Include only segments updated by the specified editor\n* Note: this option is available for country managers only\nThis field supports:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Note: you may use 'me' to match yourself",
"search.updatedby.tip": "Omvat slechts segmenten bijgewerkt door de opgegeven editor\n * Opmerking: deze optie is alleen beschikbaar voor country managers\n Dit veld ondersteunt:\n - lijsten: me, otherEditor\n - wildcards: wereld *\n - negatie:! Me, *\n * Opmerking: je kunt gebruik maken van 'me' om jezelf te vinden",
"search.updatedby.example.en": "Example: me",
"search.updatedby.example": "Voorbeeld: me",
"search.updatedsince.text.en": "<b>Updated since:</b>",
"search.updatedsince.text": "<b>Aangepast sinds:</b>",
"search.updatedsince.tip.en": "Include only segments edited since the date specified\nFirefox date format: YYYY-MM-DD",
"search.updatedsince.tip": "Toon enkel de segmenten die zijn gewijzigd sinds de opgegeven datum\nFirefox datum formaat: YYYY-MM-DD",
"search.updatedsince.example.en": "YYYY-MM-DD",
"search.updatedsince.example": "YYYY-MM-DD",
"search.city.text.en": "<b>City name:</b>",
"search.city.text": "<b>plaatsnaam:</b>",
"search.city.tip.en": "Include only segments with specified city name\nThis field supports:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
"search.city.tip": "Neem alleen segmenten op met opgegeven plaatsnaam\nDit veld ondersteunt:\n - lijsten: Amsterdam, Potsdam\n - wildcards: Den * \n - Negation: !Amsterdam, *",
"search.city.example.en": "Example: !Paris, *",
"search.city.example": "Voorbeeld: !Amsterdam, *",
"search.checks.text.en": "<b>Reported as:</b>",
"search.checks.text": "<b>Rapporteer als:</b>",
"search.checks.tip.en": "Include only segments reported as specified\nThis field matches:\n - severities: errors\n - check names: New road\n - check IDs: 200\nThis field supports:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
"search.checks.tip": "Inclusief enkel de segmenten gerapporteerd als\nDit veld kom overeen met:\n - Foutmelding-rubriek: Fout\n - naam controle: Nieuwe straat\n - ID-Check: 200\nDit veld ondersteunt:\n - lijsten: 36, 37\n - wildcards: *rotonde*\n - negatie: !Soft-Turn*, *",
"search.checks.example.en": "Example: reverse*",
"search.checks.example": "Voorbeeld: autoweg*",
"help.text.en": "<b>Help Topics:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Ask your question on the forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">How to adjust Validator for your country</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">About the \"Might be Incorrect City Name\"</a>",
"help.text": "<b>Hulp onderwerpen:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Stel je vraag op het forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Hoe Validator aan te passen voor uw land</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Over de \"Eventuele verkeerde plaatsnaam\"</a>",
"help.tip.en": "Open in a new browser tab",
"help.tip": "Open in een nieuw tabblad",
"button.scan.tip.en": "Start scanning current map area\n* Note: this might take few minutes",
"button.scan.tip": "Start het scannen van het huidige gebied op de kaart\n* Opmerking: dit kan een aantal minuten duren",
"button.scan.tip.NA.en": "Zoom out to start scanning current map area",
"button.scan.tip.NA": "Zoom uit om te beginnen met het scannen van het huidige gebied op de kaart",
"button.pause.tip.en": "Pause scanning",
"button.pause.tip": "Scannen pauzeren",
"button.continue.tip.en": "Continue scanning the map area",
"button.continue.tip": "Doorgaan met scannen van het gebied op de kaart",
"button.stop.tip.en": "Stop scanning and return to the start position",
"button.stop.tip": "Stop het scannen en keer terug naar de beginpositie",
"button.clear.tip.en": "Clear report and segment cache",
"button.clear.tip": "Wissen rapport en segment cache",
"button.clear.tip.red.en": "There are too many reported segments:\n 1. Click 'Show report' to generate the report.\n 2. Click this button to clear the report and start over.",
"button.clear.tip.red": "Er zijn te veel gerapporteerde segmenten:\n 1. Klik op 'Toon rapport' om het rapport te genereren.\n 2. Klik op deze knop om het rapport te wissen en opnieuw te beginnen.",
"button.report.text.en": "Show report",
"button.report.text": "Toon rapport",
"button.report.tip.en": "Apply the filter and generate HTML report in a new tab",
"button.report.tip": "Pas het filter toe en genereer het HTML-rapport in een nieuw tabblad",
"button.BBreport.tip.en": "Share the report on Waze forum or in a private message",
"button.BBreport.tip": "Deel het rapport op het Waze forum of in een privé-bericht",
"button.settings.tip.en": "Configure settings",
"button.settings.tip": "Instellingen aanpassen",
"tab.custom.text.en": "custom",
"tab.custom.text": "eigen instelling",
"tab.custom.tip.en": "User-defined custom checks settings",
"tab.custom.tip": "Door gebruiker aangepaste controle instellingen",
"tab.settings.text.en": "Settings",
"tab.settings.text": "Instellingen",
"tab.scanner.text.en": "scanner",
"tab.scanner.text": "scanner",
"tab.scanner.tip.en": "Map scanner settings",
"tab.scanner.tip": "Instellingen Kaartscanner",
"tab.about.text.en": "about</span>",
"tab.about.text": "over</span>",
"tab.about.tip.en": "About WME Validator",
"tab.about.tip": "Over WME Validator",
"scanner.sounds.text.en": "Enable sounds",
"scanner.sounds.text": "Gebruik geluiden",
"scanner.sounds.tip.en": "Bleeps and the bloops while scanning",
"scanner.sounds.tip": "Activeer de geluiden tijden het scannen",
"scanner.sounds.NA.en": "Your browser does not support AudioContext",
"scanner.sounds.NA": "Je browser ondersteunt geen AudioContext",
"scanner.highlight.text.en": "Highlight issues on the map",
"scanner.highlight.text": "Markeer problemen op de kaart",
"scanner.highlight.tip.en": "Highlight reported issues on the map",
"scanner.highlight.tip": "Markeer gevonden problemen op de kaart",
"scanner.slow.text.en": "Enable \"slow\" checks",
"scanner.slow.text": "\"Langzame\" controles activeren",
"scanner.slow.tip.en": "Enables deep map analysis\n* Note: this option might slow down the scanning process",
"scanner.slow.tip": "Activeert diepe kaartanalyse\n* Opmerking: deze optie zou het scanproces kunnen vertragen",
"scanner.ext.text.en": "Report external highlights",
"scanner.ext.text": "Meld externe markeringen",
"scanner.ext.tip.en": "Report segments highlighted by WME Toolbox or WME Color Highlights",
"scanner.ext.tip": "Rapporteer segmenten gemarkeerd door WME Toolbox of WME Color Highlights",
"advanced.twoway.text.en": "WME: Two-way segments by default",
"advanced.twoway.text": "WME: Nieuwe segmenten tweerichtingsverkeer standaard",
"advanced.twoway.tip.en": "Newly created streets in WME are bidirectional by default",
"advanced.twoway.tip": "Nieuwe segmenten zijn standaard tweerichtingsverkeer",
"custom.template.text.en": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Custom template</a>",
"custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Aangepast sjabloon</a>",
"custom.template.tip.en": "User-defined custom check expandable template.\n\nYou may use the following expandable variables:\nAddress:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nSegment properties:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nHelpers:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nConnectivity:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.tip": "Door de gebruiker gedefinieerde aangepaste controle uitbreidbaar sjabloon.\n\nDe volgende variabelen zijn te gebruiken:\n${country}, ${state}, ${city}, ${street},\n${altCity[Index of onderscheidingsteken]}, ${altStreet[Index of onderscheidingsteken]}\nSegment-Eigenschaften:\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nHelpers:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns}\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nVerbindungen:\n  ${segmentsA}, ${inA}, ${outB}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.example.en": "Example: ${street}",
"custom.template.example": "Voorbeeld: ${street}",
"custom.regexp.text.en": "Custom <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
"custom.regexp.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Eigen RegExp</a>",
"custom.regexp.tip.en": "User-defined custom check regular expression to match the template.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
"custom.regexp.tip": "Door de gebruiker gedefinieerde RegExp die overeenkomen met het template.\n\nNiet hoofdlettergevoelig match: /regexp/i\nNegatie van een uitdrukking: !/regexp/\nLog debug informatie op de console: D/regexp/",
"custom.regexp.example.en": "Example: !/.+/",
"custom.regexp.example": "Voorbeeld: !/.+/",
"about.tip.en": "Open link in a new tab",
"about.tip": "Link in nieuw tabblad openen",
"button.reset.text.en": "Reset defaults",
"button.reset.text": "Herstel standaardinstellingen",
"button.reset.tip.en": "Revert filter options and settings to their defaults",
"button.reset.tip": "Filter opties en instellingen herstellen naar de standaardwaarden",
"button.list.text.en": "Available checks...",
"button.list.text": "Beschikbare controles...",
"button.list.tip.en": "Show a list of checks available in WME Validator",
"button.list.tip": "Toon een lijst met beschikbare controles in WME Validator",
"button.wizard.tip.en": "Create localization package",
"button.wizard.tip": "Maak lokalisatie pakket aan",
"button.back.text.en": "Back",
"button.back.text": "Terug",
"button.back.tip.en": "Close settings and return to main view",
"button.back.tip": "Sluit de instellingen en keer terug naar de hoofdweergave",
"1.title.en": "WME Toolbox: Roundabout which may cause issues",
"1.title": "WME Toolbox: Rotonde die problemen kan veroorzaken (rotonde verkeer problematisch)",
"1.problem.en": "Junction IDs of the roundabout segments are not consecutive",
"1.problem": "Knooppunt-ID's van de rotonde segmenten zijn niet opeenvolgend",
"1.solution.en": "Redo the roundabout",
"1.solution": "Rotonde opnieuw doen",
"2.title.en": "WME Toolbox: Simple segment",
"2.title": "WME Toolbox: Moeilijk segment (Te veel geometrie knooppunten)",
"2.problem.en": "The segment has unneeded geometry nodes",
"2.problem": "Het segment heeft onnodige geometrie knooppunten",
"2.solution.en": "Simplify segment geometry by hovering mouse pointer and pressing \"d\" key",
"2.solution": "Vereenvoudig segment geometrie door de muisaanwijzing boven het punt te brengen en de \"d\" toets in te drukken",
"3.title.en": "WME Toolbox: Lvl 2 lock",
"3.title": "WME Toolbox: Lvl 2 Lock",
"3.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"3.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"4.title.en": "WME Toolbox: Lvl 3 lock",
"4.title": "WME Toolbox: Lvl 3 Lock",
"4.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"4.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem.",
"5.title.en": "WME Toolbox: Lvl 4 lock",
"5.title": "WME Toolbox: Lvl 4 Lock",
"5.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"5.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"6.title.en": "WME Toolbox: Lvl 5 lock",
"6.title": "WME Toolbox: Lvl 5 Lock",
"6.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"6.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"7.title.en": "WME Toolbox: Lvl 6 lock",
"7.title": "WME Toolbox: Lvl 6 Lock",
"7.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"7.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"8.title.en": "WME Toolbox: House numbers",
"8.title": "WME Toolbox: Huisnummers",
"8.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"8.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"9.title.en": "WME Toolbox: Segment with time restrictions",
"9.title": "WME Toolbox: Segment met tijdsrestricties",
"9.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
"9.problem": "Het segment wordt gemarkeerd door WME Toolbox. Het is geen probleem",
"13.title.en": "WME Color Highlights: Editor lock",
"13.title": "WME Color Highlights: Editor lock",
"13.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"13.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"14.title.en": "WME Color Highlights: Toll road / One way road",
"14.title": "WME Color Highlights: Toll road / One way road (Tol- / Eenrichtings-straat)",
"14.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"14.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"15.title.en": "WME Color Highlights: Recently edited",
"15.title": "WME Color Highlights: Recently edited (Kürzlich editiert)",
"15.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"15.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"16.title.en": "WME Color Highlights: Road rank",
"16.title": "WME Color Highlights: Road type",
"16.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"16.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"17.title.en": "WME Color Highlights: No city",
"17.title": "WME Color Highlights: No city (Keine Stadt)",
"17.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"17.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"18.title.en": "WME Color Highlights: Time restriction / Highlighted road type",
"18.title": "WME Color Highlights: Time restriction / Highlighted road type",
"18.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"18.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"19.title.en": "WME Color Highlights: No name",
"19.title": "WME Color Highlights: No name (Kein Straßenname)",
"19.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"19.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"20.title.en": "WME Color Highlights: Filter by city",
"20.title": "WME Color Highlights: Filter by city (Stadt-Filter)",
"20.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"20.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"21.title.en": "WME Color Highlights: Filter by city (alt. city)",
"21.title": "WME Color Highlights: Filter by city (alt. city)",
"21.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"21.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"22.title.en": "WME Color Highlights: Filter by editor",
"22.title": "WME Color Highlights: Filter by editor (Editor-Filter)",
"22.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
"22.problem": "Het segment wordt gemarkeerd door WME Color Highlights. Het is geen probleem",
"23.title.en": "Unconfirmed road",
"23.title": "Onbevestigde straat",
"23.problem.en": "Each segment must minimally have the Country and State information",
"23.problem": "Elk segment moet minimaal informatie hebben over het land en plaats",
"23.solution.en": "Confirm the road by updating its details",
"23.solution": "Bevestig de straat door ofwel de plaats danwel de straatnaam in te voeren.",
"24.title.en": "Might be incorrect city name (only available in the report)",
"24.title": "Eventueel verkeerde plaatsnaam (alleen beschikbaar in het rapport)",
"24.problem.en": "The segment might have incorrect city name",
"24.problem": "Het segment heeft misschien een verkeerde plaatsnaam",
"24.solution.en": "Consider suggested city name and use this form to rename the city",
"24.solution": "Overweeg de voorgestelde plaatsnaam en gebruik dit formulier om de naam te wijzigen",
"25.title.en": "Unknown direction of drivable road",
"25.title": "Onbekende rijrichting van berijdbare weg",
"25.problem.en": "'Unknown' road direction will not prevent routing on the road",
"25.problem": "'Onbekende' rijrichting zal niet voorkomen dat er genavigeerd wordt over de weg",
"25.solution.en": "Set the road direction",
"25.solution": "Stel de rijrichting in",
"28.title.en": "Street name on two-way Ramp",
"28.title": "Straatnaam op tweebaans voegstrook",
"28.problem.en": "If Ramp is unnamed, the name of a subsequent road will propagate backwards",
"28.problem": "Als de op/afrit geen naam heeft, zal de naam van de volgende straat worden overgenomen",
"28.solution.en": "In the address properties check the 'None' box next to the street name and then click 'Apply'",
"28.solution": "In de adreseigenschappen vink 'Geen' aan naast de straatnaam en klik op 'Toepassen'",
"29.title.en": "Street name on roundabout",
"29.title": "Straatnaam op rotonde",
"29.problem.en": "In Waze, we do not name roundabout segments",
"29.problem": "In Waze geven we rotondes geen straatnamen",
"29.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout",
"29.solution": "In de adreseigenschappen vink 'Geen' aan naast de straatnaam en klik op 'Toepassen' en voeg eventueel een 'Kruispunt/Knooppunt' toe met de naam van de rotonde",
"33.enabled": false,
"34.title.en": "Empty alternate street",
"34.title": "Lege alternatieve straatnaam",
"34.problem.en": "Alternate street name is empty",
"34.problem": "De alternatieve straatnaam is leeg",
"34.solution.en": "Remove empty alternate street name",
"34.solution": "Verwijder de lege alternatieve straatnaam",
"35.title.en": "Unterminated drivable road",
"35.title": "Geen eindnode op berijdbare weg",
"35.problem.en": "Waze will not route from the unterminated segment",
"35.problem": "Waze zal niet routeren vanaf segmenten zonder eindnode",
"35.solution.en": "Move the segment a bit so the terminating node will be added automatically",
"35.solution": "Verplaats het segment een beetje zodat de eindnode automatisch zal worden toegevoegd",
"36.enabled": true,
"36.title.en": "Node A: Unneeded (slow)",
"36.title": "Node A: Onnodig (langzaam)",
"36.problem.en": "Adjacent segments at node A are identical",
"36.problem": "De segmenten naast node A zijn identiek",
"36.solution.en": "Select node A and press Delete key to join the segments",
"36.solution": "Selecteer node A en druk op Delete om de segmenten samen te voegen",
"37.enabled": true,
"37.title.en": "Node B: Unneeded (slow)",
"37.title": "Node B: Onnodig (langzaam)",
"37.problem.en": "Adjacent segments at node B are identical",
"37.problem": "De segmenten naast node B zijn identiek",
"37.solution.en": "Select node B and press Delete key to join the segments",
"37.solution": "Selecteer node B en druk op Delete om de segmenten samen te voegen",
"38.title.en": "Expired segment restriction (slow)",
"38.title": "Verlopen segment beperking (langzaam)",
"38.problem.en": "The segment has an expired restriction",
"38.problem": "Het segment heeft een verlopen beperking",
"38.solution.en": "Click 'Edit restrictions' and delete the expired restriction",
"38.solution": "Klik op 'Bewerken restricties' en verwijder de verstreken beperking",
"39.title.en": "Expired turn restriction (slow)",
"39.title": "Verlopen beperking op afslag (langzaam)",
"39.problem.en": "The segment has a turn with an expired restriction",
"39.problem": "Het segment heeft een afslag met een verlopen beperking",
"39.solution.en": "Click clock icon next to the yellow arrow and delete the expired restriction",
"39.solution": "Klik klok pictogram naast de gele pijl en verwijder de verlopen beperking",
"41.title.en": "Node A: Reverse connectivity of drivable road",
"41.title": "Node A: Omgekeerde connectiviteit van berijdbare weg",
"41.problem.en": "There is a turn which goes against the directionality of the segment at node A",
"41.problem": "Er is een afslag die indruist tegen de rijrichting van het segment op knooppunt A",
"41.solution.en": "Make the segment 'Two-way', restrict all the turns at node A and then make the segment 'One way (A→B)' again",
"41.solution": "Verander het segment in twee-richting, verbied de afslag bij node A en verander het segment weer in '1-richting', of verander het segment weer in 'One way (A→B)'",
"42.title.en": "Node B: Reverse connectivity of drivable road",
"42.title": "Node B: Omgekeerde connectiviteit van berijdbare weg",
"42.problem.en": "There is a turn which goes against the directionality of the segment at node B",
"42.problem": "Er is een afslag die indruist tegen de rijrichting van het segment op knooppunt B",
"42.solution.en": "Make the segment 'Two-way', restrict all the turns at node B and then make the segment 'One way (B→A)' again",
"42.solution": "Verander het segment in twee-richting, verbied de afslag bij node B en verander het segment weer in '1-richting', Of verander het segment weer in 'One way (B→A)'",
//"43.enabled": false,
"43.title.en": "Self connectivity",
"43.title": "Zelf verbinding",
"43.problem.en": "The segment is connected back to itself",
"43.problem": "Het segment is met zichzelf verbonden",
"43.solution.en": "Split the segment into THREE pieces",
"43.solution": "Verdeel het segment in DRIE stukken",
"44.title.en": "No outward connectivity",
"44.title": "Geen verbinding naar buiten",
"44.problem.en": "The drivable segment has no single outward turn enabled",
"44.problem": "Het berijdbare segment heeft geen enkele verbinding naar buiten",
"44.solution.en": "Enable at least one outward turn from the segment",
"44.solution": "Verbind het segment minstens eenmaal met het verkeersnet",
"45.title.en": "No inward connectivity",
"45.title": "Geen verbinding naar binnen",
"45.problem.en": "The drivable non-private segment has no single inward turn enabled",
"45.problem": "Het berijdbare niet-privé segment heeft geen enkele verbinding naar het segment toe",
"45.solution.en": "Select an adjacent segment and enable at least one turn to the segment",
"45.solution": "Selecteer het segment en sta minstens één inwaartse verbinding toe",
"46.title.en": "Node A: No inward connectivity of drivable road (slow)",
"46.title": "Node A: Geen naar binnen connectiviteit van berijdbare weg (langzaam)",
"46.problem.en": "The drivable non-private segment has no single inward turn enabled at node A",
"46.problem": "De berijdbare niet-particuliere segment heeft geen enkele naar binnen wijzende verbinding ingeschakeld op knooppunt A",
"46.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node A",
"46.solution": "Selecteer een aangrenzend segment en stel tenminste één verbinding naar segment bij knooppunt A in",
"47.title.en": "Node B: No inward connectivity of drivable road (slow)",
"47.title": "Node B: Het berijdbare segment heeft geen enkele verbinding naar het segment toe (langzaam)",
"47.problem.en": "The drivable non-private segment has no single inward turn enabled at node B",
"47.problem": "Het berijdbare (niet prive) segment heeft geen enkele verbinding naar het segment toe bij node B",
"47.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node B",
"47.solution": "Selecteer een aangrenzend segment en stel tenminste één verbinding naar segment bij node B",
"48.title.en": "Two-way drivable roundabout segment",
"48.title": "Berijdbare rotonde segment is niet eenrichtingsverkeer",
"48.problem.en": "The drivable roundabout segment is bidirectional",
"48.problem": "Berijdbare rotonde segment is niet eenrichtingsverkeer",
"48.solution.en": "Redo the roundabout",
"48.solution": "Maak de rotonde opnieuw",
"71.enabled": true,
"71.problemLink": "W:Benelux/Major_Highway",
"71.title.en": "Must be a Major Highway",
"71.title": "Moet een Major Highway zijn",
"71.problem.en": "This segment must be a Major Highway",
"71.problem": "Dit segment moet een Major Highway zijn",
"71.solution.en": "Set the road type to Major Highway or change the road name",
"71.solution": "Stel het wegtype in op Major Highway of verander de straatnaam",
"72.enabled": true,
"72.problemLink": "W:Benelux/Minor_Highway",
"72.title.en": "Must be a Minor Highway",
"72.title": "Dit moet een Minor Highway zijn",
"72.problem.en": "This segment must be a Minor Highway",
"72.problem": "Dit segment moet een Minor Highway zijn",
"72.solution.en": "Set the road type to Minor Highway or change the road name",
"72.solution": "Stel het wegtype in op Minor Highway of verander de straatnaam",
"78.title.en": "Same endpoints drivable segments (slow)",
"78.title": "Dezelfde eindpunten voor berijdbare segmenten (langzaam)",
"78.problem.en": "Two drivable segments share the same two endpoints",
"78.problem": "Twee berijdbare segmenten delen dezelfde twee eindpunten",
"78.solution.en": "Split the segment. You might also remove one of the segments if they are identical",
"78.solution": "Splits het segment. Je zou ook een segment kunnen verwijderen als ze identiek zijn",
"87.title.en": "Node A: Multiple outgoing segments at roundabout",
"87.title": "Node A: Meerdere uitgaande segmenten voor rotonde",
"87.problem.en": "The drivable roundabout node A has more than one outgoing segment connected",
"87.problem": "De berijdbare rotonde knooppunt A heeft meerdere uitgaande segmenten verbonden",
"87.solution.en": "Redo the roundabout",
"87.solution": "Maak de rotonde opnieuw",
"99.title.en": "U-turn at roundabout entrance (slow)",
"99.title": "U-bocht op rotonde (langzaam)",
"99.problem.en": "The roundabout entrance segment has a U-turn enabled",
"99.problem": "De berijdbare rotondenode heeft een U-bocht toegestaan",
"99.solution.en": "Disable U-turn",
"99.solution": "Zet de U-bocht uit",
"101.title.en": "Closed road (only available in the report)",
"101.title": "Afgesloten weg (enkel beschikbaar in het rapport)",
"101.problem.en": "The segment is marked as closed",
"101.problem": "Het segment is gemarkeerd als afgesloten",
"101.solution.en": "If the construction is done, restore the segment connectivity and remove the suffix",
"101.solution": "Als de wegwerkzaamheden klaar zijn, herstel dan de verbinding van het segment en verwijder de aanvulling",
"102.title.en": "Node A: No outward connectivity of drivable road (slow)",
"102.title": "Node A: Geen uitgaande verbinding van berijdbare weg (langzaam)",
"102.problem.en": "The drivable segment has no single outward turn enabled at node A",
"102.problem": "Het berijdbare segment heeft geen enkele uitgaande verbinding aan staan bij node A",
"102.solution.en": "Enable at least one outward turn from the segment at node A",
"102.solution": "Zet minstens 1 uitgaande verbinding aan bij node A",
"103.title.en": "Node B: No outward connectivity of drivable road (slow)",
"103.title": "Node B: Geen uitgaande verbinding van berijdbare weg (langzaam)",
"103.problem.en": "The drivable segment has no single outward turn enabled at node B",
"103.problem": "Het berijdbare segment heeft geen enkele uitgaande verbinding aan staan bij node B",
"103.solution.en": "Enable at least one outward turn from the segment at node B",
"103.solution": "Zet minstens 1 uitgaande verbinding aan bij node B",
"104.title.en": "Railroad used for comments",
"104.title": "Spoorweg gebruikt als commentaar",
"104.problem.en": "The Railroad segment is probably used as a map comment",
"104.problem": "Het spoorweg segment wordt waarschijnelijk gebruikt als kaartopmerking",
"104.solution.en": "Remove the comment as Railroads will be added to the client display",
"104.solution": "Verwijder het commentaar, spoorwegen worden weergegeven in de client",
"107.title.en": "Node A: No connection (slow)",
"107.title": "Node A: Geen verbinding (langzaam)",
"107.problem.en": "The node A of the drivable segment is within 5m from another drivable segment but not connected by a junction",
"107.problem": "De node A van een berijdbaar segment is binnen 5 meter van een ander berijdbaar segment, maar is niet verbonden via een kruising",
"107.solution.en": "Drag the node A to the nearby segment so that it touches or move it a bit further away",
"107.solution": "Sleep de node A naar het dichtbij gelegen segment zodat deze verbonden worden, of sleep de node iets verder weg van het andere segment",
"108.title.en": "Node B: No connection (slow)",
"108.title": "Node B: Geen verbinding (langzaam)",
"108.problem.en": "The node B of the drivable segment is within 5m from another drivable segment but not connected by a junction",
"108.problem": "De node B van een berijdbaar segment is binnen 5 meter van een ander berijdbaar segment, maar is niet verbonden via een kruising",
"108.solution.en": "Drag the node B to the nearby segment so that it touches or move it a bit further away",
"108.solution": "Sleep de node B naar het dichtbij gelegen segment zodat deze verbonden worden, of sleep de node iets verder weg van het andere segment",
"109.title.en": "Too short segment",
"109.title": "Te kort segment",
"109.problem.en": "The drivable non-terminal segment is less than ${n}m long so it is hard to see it on the map and it can cause routing problems",
"109.problem": "Het berijdbaar, niet doodlopend, segment is korter dan ${n}m, dit is moeilijk te zien op de kaart en kan voor routerings problemen zorgen",
"109.solution.en": "Increase the length, or remove the segment, or join it with one of the adjacent segments",
"109.solution": "Verleng het segment, of verwijder het segment, of voeg het segment samen met een van de omliggende segmenten",
"112.title.en": "Too long Ramp name",
"112.title": "Op/afrit naam te lang",
"112.problem.en": "The Ramp name is more than ${n} letters long",
"112.problem": "Op/afrit naam is langer dan ${n} tekens lang",
"112.solution.en": "Shorten the Ramp name",
"112.solution": "Verkort de naam",
"114.enabled": false,
"114.title.en": "Node A: Non-drivable connected to drivable (slow)",
"114.title": "Node A: Niet-berijdbaar verbonden met berijdbaar (langzaam)",
"114.problem.en": "The non-drivable segment makes a junction with a drivable at node A",
"114.problem": "Het niet-berijdbare segment maakt verbinding met een berijdbaar segment bij node A",
"114.solution.en": "Disconnect node A from all of the drivable segments",
"114.solution": "Verbreek de vervinding van alle berijdbare segmenten bij node A",
"115.enabled": false,
"115.title.en": "Node B: Non-drivable connected to drivable (slow)",
"115.title": "Node B: Niet-berijdbaar verbonden met berijdbaar (langzaam)",
"115.problem.en": "The non-drivable segment makes a junction with a drivable at node B",
"115.problem": "Het niet-berijdbare segment maakt verbinding met een berijdbaar segment bij node B",
"115.solution.en": "Disconnect node B from all of the drivable segments",
"115.solution": "Verbreek de vervinding van alle berijdbare segmenten bij node B",
"116.title.en": "Out of range elevation",
"116.title": "Hoogte buiten bereik",
"116.problem.en": "The segment elevation is out of range",
"116.problem": "De elevatie van het segment is buiten bereik",
"116.solution.en": "Correct the elevation",
"116.solution": "Corrigeer de hoogte",
"117.title.en": "Obsolete CONST ZN marker",
"117.title": "CONST ZN markering verouderd",
"117.problem.en": "The segment is marked with obsolete CONST ZN suffix",
"117.problem": "Het segment is gemarkeerd met een verouderde CONST ZN toevoeging",
"117.solution.en": "Change CONST ZN to (closed)",
"117.solution": "Verander CONST ZN naar (afgesloten)",
"118.title.en": "Node A: Overlapping segments (slow)",
"118.title": "Node A: Overlappende segmenten (langzaam)",
"118.problem.en": "The segment is overlapping with the adjacent segment at node A",
"118.problem": "Het segment overlapt het aangrenzende segment bij node A",
"118.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node A",
"118.solution": "Verdeel de segmenten bij 2° of verwijder overbodige geometriepunt of verwijder het duplicaat-segment bij node A",
"119.title.en": "Node B: Overlapping segments (slow)",
"119.title": "Node B: Overlappende segmenten (langzaam)",
"119.problem.en": "The segment is overlapping with the adjacent segment at node B",
"119.problem": "Het segment overlapt het aangrenzende segment bij node B",
"119.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node B",
"119.solution": "Verdeel de segmenten bij 2° of verwijder overbodige geometriepunt of verwijder het duplicaat-segment bij node B",
"120.title.en": "Node A: Too sharp turn (slow)",
"120.title": "Node A: Te scherpe bocht (langzaam)",
"120.problem.en": "The drivable segment has a very acute turn at node A",
"120.problem": "Het berijdbare segment heeft een zeer scherpe bocht bij node A",
"120.solution.en": "Disable the sharp turn at node A or spread the segments at 30°",
"120.solution": "Sta de scherpe bocht bij node A niet toe of maak de hoek groter dan 30°",
"121.title.en": "Node B: Too sharp turn (slow)",
"121.title": "Node B: Te scherpe bocht (langzaam)",
"121.problem.en": "The drivable segment has a very acute turn at node B",
"121.problem": "Het berijdbare segment heeft een zeer scherpe bocht bij B",
"121.solution.en": "Disable the sharp turn at node B or spread the segments at 30°",
"121.solution": "Sta de scherpe bocht bij node B niet toe of maak de hoek groter dan 30°",
"128.title.en": "User-defined custom check (green)",
"128.title": "Door de gebruiker gedefinieerde aangepaste controle (groen)",
"128.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
"128.problem": "Sommige segmenteigenschappen komen overeen met door gebruiker gedefinieerde opgave (zie Instellingen→Aangepast)",
"128.solution.en": "Solve the issue",
"128.solution": "Los het probleem op",
"129.title.en": "User-defined custom check (blue)",
"129.title": "Door de gebruiker gedefinieerde aangepaste controle (blauw)",
"129.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
"129.problem": "Sommige segmenteigenschappen komen overeen met door gebruiker gedefinieerde opgave (zie Instellingen→Aangepast)",
"129.solution.en": "Solve the issue",
"129.solution": "Los het probleem op",
"150.enabled": true,
"150.problemLink": "W:Benelux/Freeway",
"150.title.en": "No lock on Freeway",
"150.title": "Geen lock op snelweg",
"150.problem.en": "The Freeway segment should be locked at least to Lvl ${n}",
"150.problem": "De snelweg moet op tenminste Lvl ${n} gelockt zijn",
"150.solution.en": "Lock the segment",
"150.solution": "Lock het segment",
"151.enabled": true,
"151.problemLink": "W:Benelux/Major_Highway",
"151.title.en": "No lock on Major Highway",
"151.title": "Geen lock op Major Highway",
"151.problem.en": "The Major Highway segment should be locked at least to Lvl ${n}",
"151.problem": "Het Major Highway segment moet gelockt zijn op Lvl ${n}",
"151.solution.en": "Lock the segment",
"151.solution": "Lock het segment",
"152.enabled": true,
"152.problemLink": "W:Benelux/Minor_Highway",
"152.title.en": "No lock on Minor Highway",
"152.title": "Geen lock op Minor Highway",
"152.problem.en": "The Minor Highway segment should be locked at least to Lvl ${n}",
"152.problem": "Het Minor Highway segment moet gelockt zijn op Lvl ${n}",
"152.solution.en": "Lock the segment",
"152.solution": "Lock het segment",
"154.enabled": true,
"154.problemLink": "W:Benelux/Primary_Street",
"154.title.en": "No lock on Primary Street",
"154.title": "Geen lock op hoofdweg",
"154.problem.en": "The Primary Street segment should be locked at least to Lvl ${n}",
"154.problem": "De hoofdweg zou minimaal gelockt moeten zijn op Lvl ${n}",
"154.solution.en": "Lock the segment",
"154.solution": "Lock het segment",
"160.enabled": false,
"161.enabled": true,
"161.params": {
"solutionEN": "Rename the Major Highway to 'Nnum[ - Nnum]' or 'Nnum - streetname' or 'Nnum ri Dir1 / Dir2'",
"regexp": "!/^N([0-9]|[0-9][0-9]|[123][0-9][0-9])( - [NS][0-9]+)?(( ri [^\\/]+( \\/ [^\\/]+)*)|( - .+))?$/"
},
"161.problemLink": "W:Benelux/Major_Highway",
"161.title.en": "Incorrect Major Highway name",
"161.title": "Verkeerde  Major Highway naam",
"161.problem.en": "The Major Highway segment has incorrect street name",
"161.problem": "Het Major Highway segment heeft een verkeerde  straatnaam",
"161.solution.en": "Rename the segment in accordance with the guidelines",
"161.solution": "Hernoem het segment volgens de richtlijnen",
"162.enabled": true,
"162.params": {
"solutionEN": "Rename the Minor Highway to 'Nnum[ - Nnum]' or 'Nnum - streetname' or 'Nnum ri Dir1 / Dir2'",
"regexp": "!/^(N[4-9][0-9][0-9]|[SU][0-9]+)( - [NS][0-9]+)?(( ri [^\\/]+( \\/ [^\\/]+)*)|( - .+))?$/"
},
"162.problemLink": "W:Benelux/Minor_Highway",
"162.title.en": "Incorrect Minor Highway name",
"162.title": "Verkeerde Minor Highway naam",
"162.problem.en": "The Minor Highway segment has incorrect street name",
"162.problem": "Het Minor Highway segment heeft een verkeerde straatnaam",
"162.solution.en": "Rename the segment in accordance with the guidelines",
"162.solution": "Hernoem het segment volgens de richtlijnen. LET OP! Er zijn uitzonderingen voor bepaalde belangrijke regionale wegen. In geval van twijfel, eerst overleggen!",
"172.title.en": "Unneeded spaces in street name",
"172.title": "Onnodige spaties in de straatnaam",
"172.problem.en": "Leading/trailing/double space in the street name",
"172.problem": "Overbodige spaties voor/achter/in de straatnaam",
"172.solution.en": "Remove unneeded spaces from the street name",
"172.solution": "Verwijder de overbodige spaties in de straatnaam",
"173.title.en": "No space before/after street abbreviation",
"173.title": "Geen spatie voor/achter de straat afkorting",
"173.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the street name",
"173.problem": "Geen spatie voor ('1943r.') of achter ('st.Jan') een afkorting in de straatnaam",
"173.solution.en": "Add a space before/after the abbreviation",
"173.solution": "Voeg een spatie voor/achter de afkorting toe",
"175.title.en": "Empty street name",
"175.title": "Lege straatnaam",
"175.problem.en": "The street name has only space characters or a dot",
"175.problem": "De straatnaam heeft alleen spaties of punt(en)",
"175.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' OR set a proper street name",
"175.solution": "In de adreseigenschappen vink de 'Geen' optie aan naast de straatnaam, klik op 'Toepassen' OF vul de juiste straatnaam in",
"190.title.en": "Lowercase city name",
"190.title": "Plaatsnaam in kleine letters",
"190.problem.en": "The city name starts with a lowercase letter",
"190.problem": "De plaatsnaam begint met een kleine letter",
"190.solution.en": "Use this form to rename the city",
"190.solution": "Gebruik dit formulier om de plaatsnaam te hernoemen",
"192.title.en": "Unneeded spaces in city name",
"192.title": "Onnodige spaties in de plaatsnaam",
"192.problem.en": "Leading/trailing/double space in the city name",
"192.problem": "Overbodige spaties voor/achter/in de plaatsnaam",
"192.solution.en": "Use this form to rename the city",
"192.solution": "Gebruik dit formulier om de plaatsnaam te hernoemen",
"193.title.en": "No space before/after city abbreviation",
"193.title": "Geen spatie voor/achter de afkorting in de plaatsnaam",
"193.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the city name",
"193.problem": "Geen spatie voor ('1943r.') of achter ('st.Jan') een afkorting in de plaatsnaam",
"193.solution.en": "Use this form to rename the city",
"193.solution": "Gebruik dit formulier om de plaatsnaam te hernoemen",
"200.title.en": "Node A: Unconfirmed turn on minor road",
"200.title": "Node A: Onbevestigde verbinding op weg",
"200.problem.en": "The minor drivable segment has an unconfirmed (soft) turn at node A",
"200.problem": "Het berijdbare segment heeft een onbevestigd (zachte) bocht op node A",
"200.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
"200.solution": "Klik op de aangegeven verbinding met een paarse vraagteken om het te bevestigen. Opmerking: het kan nodig zijn om het segment 2-richtingen te maken om die verbindingen te zien",
"201.title.en": "Node A: Unconfirmed turn on primary road",
"201.title": "Node A: Onbevestigde verbinding op hoofdweg",
"201.problem.en": "The primary segment has an unconfirmed (soft) turn at node A",
"201.problem": "Het hoofdweg segment heeft een onbevestigde (zachte) verbinding bij node A",
"201.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
"201.solution": "Klik op de aangegeven verbinding met een paarse vraagteken om het te bevestigen. Opmerking: het kan nodig zijn om het segment 2-richtingen te maken om die verbindingen te zien",
"202.title.en": "BETA: No public connection for public segment (slow)",
"202.title": "BETA: Routeerbaar segment lijkt geisoleerd (langzaam)",
"202.problem.en": "The public segement is not connected to any other public segment",
"202.problem": "Het segment lijkt een publiek toegankelijk segment in het midden van niet publieke segmenten te zijn",
"202.solution.en": "Verify if the segment is meant to be a public accessible segment, or it should be changed to a private segment",
"202.solution": "Controleer of dit segment wel publiek toegankelijk moet zijn, of van type moet wijzigen",
"214.params": {
    "regexp": "/^5|15|25|.+0$/", // match 5, 15, 25 or other limit with '0' at the end
},
"215.params": {
    "regexp": "/^5|15|25|.+0$/", // match 5, 15, 25 or other limit with '0' at the end
},