".country": "Poland",
".author": "Zniwek",
".updated": "2014-10-01",
".lng": "PL",

"city.consider": "rozważ tę nazwę miasta:",
"city.1": "nazwa miasta jest za krótka",
"city.2": "rozwiń skrót",
"city.3": "uzupełnij skróconą nazwę",
"city.4": "uzupełnij nazwę miasta",
"city.5": "popraw wielkość liter",
"city.6": "sprawdź kolejność słów",
"city.7": "sprawdź skróty",
"city.8a": "dodaj nazwę państwa",
"city.8r": "usuń nazwę państwa",
"city.9": "sprawdź nazwę państwa",
"city.10a": "dodaj słowo",
"city.10r": "usuń słowo",
"city.11": "dodaj kod państwa",
"city.12": "identyczne nazwy, ale inne ID miasta",
"city.13a": "dodaj spację",
"city.13r": "usuń spację",
"city.14": "sprawdź numer",
"props.skipped.title": "Segment nie jest sprawdzony",
"props.skipped.problem": "Segment jest zmodyfikowany po 2014-05-01 I zablokowany dla Ciebie, więc Validator go nie sprawdził",
"err.regexp": "Błąd podczas parsowania opcji dla sprawdzenia #${n}:",
"props.disabled": "WME Validator jest wyłączony",
"props.limit.title": "Zgłoszono zbyt wiele problemów",
"props.limit.problem": "Zgłoszono zbyt wiele problemów, więc niektóre z nich mogą nie być pokazane",
"props.limit.solution": "Odznacz segment i zatrzymaj skanowanie. Następnie kliknij czerwony '✘', przycisk (Wyczyść raport)",
"props.reports": "raporty",
"props.noneditable": "Nie możesz edytować tego segmentu",
"report.save": "Zapisz ten raport",
"report.list.andUp": "i wyższe",
"report.list.severity": "Ważność:",
"report.list.reportOnly": "tylko w raporcie",
"report.list.forEditors": "Dla edytorów poziomu:",
"report.list.forCountries": "Dla państw:",
"report.list.forStates": "Dla stanów:",
"report.list.forCities": "Dla miast:",
"report.list.params": "Parametry do skonfigurowania w paczce językowej:",
"report.list.params.set": "Aktualna konfiguracja dla ${country}:",
"report.list.enabled": "${n} sprawdzenia włączone dla",
"report.list.disabled": "${n} sprawdzenia wyłączone dla",
"report.list.total": "There are ${n} sprawdzenia dostępne",
"report.list.title": "Pełna lista Sprawdzeń dla",
"report.list.see": "Zobacz",
"report.list.checks": "Ustawienia->O->Dostępne sprawdzenia",
"report.list.fallback": "Zasady Cofnięcia Lokalizacji:",
"report.and": "i",
"report.segments": "Liczba sprawdzonych segmentów:",
"report.customs": "Własne zaznaczone sprawdzenia (zielone/niebieskie):",
"report.reported": "Zaraportowane",
"report.errors": "błędy",
"report.warnings": "ostrzeżenia",
"report.notes": "notki",
"report.contents": "Zawartość:",
"report.summary": "Podsumowanie",
"report.title": "WME Validator - Raport",
"report.share": "by się Podzielić",
"report.generated.by": "wygenerowane przez",
"report.generated.on": "na",
"report.source": "Źródło raportu:",
"report.filter.duplicate": "duplikowane segmenty",
"report.filter.streets": "Ulice i Drogi Serwisowe",
"report.filter.other": "Pozostałe przejezdne/nieprzejezdne",
"report.filter.noneditable": "segmenty bez możliwości edycji",
"report.filter.notes": "notki",
"report.filter.title": "Filtruj:",
"report.filter.excluded": "są wyłączone z tego raportu.",
"report.search.updated.by": "zaktualizowane przez",
"report.search.updated.since": "zaktualizowane od",
"report.search.city": "z",
"report.search.reported": "zaraportowane jako",
"report.search.title": "Szukaj:",
"report.search.only": "tylko segmenty",
"report.search.included": "są zawarte w tym raporcie.",
"report.beta.warning": "Ostrzeżenie WME Beta!",
"report.beta.text": "Ten raport jest wygenerowany w wersji beta WME z permalinkami beta.",
"report.beta.share": "Proszę, nie dziel się raportem z tymi permalinkami!",
"report.size.warning": "<b>Uwaga!</b><br>Ten raport ma ${n} znaków, więc <b>nie zmieści się</b> w jeden post na forum lub wiadomość prywatną.\n<br>Proszę dodaj <b>więcej filtrów</b>, żeby zmniejszyć długość raportu.",
"report.note.limit": "* Info: było zbyt wiele zgłoszonych problemów, więc niektóre z nich nie są policzone w podsumowaniu.",
"report.forum": "Żeby zmotywować mnie do pracy nad skrpytem, zostaw komentarz w",
"report.thanks": "Dziękuję za używanie WME Validator!",
"msg.limit.segments": "Zbyt wiele segmentów.\n\nKliknij 'Pokaż raport' żeby go przejrzeć, a potem\n",
"msg.limit.segments.continue": "kliknij '▶' (Start) by kontynuować.",
"msg.limit.segments.clear": "kliknij '✘' (Wyczyść) by wyczyścić raport.",
"msg.pan.text": "Przesuwaj mapę, by ją sprawdzić",
"msg.zoomout.text": "Oddal widok, by uruchomić WME Validator",
"msg.click.text": "Kliknij '▶' (Start), by sprawdzić widoczny obszar mapy",
"msg.autopaused": "autopauza",
"msg.autopaused.text": "Spauzowano automatycznie! Kliknij '▶' (Start) by kontynuować.",
"msg.autopaused.tip": "WME Validator wstrzymany automatycznie przy przesunięciu mapy lub skalowaniu okna",
"msg.finished.text": "Kliknij <b>'Pokaż raport'</b> by przejrzeć błędy",
"msg.finished.tip": "Kliknij przycisk '✉' (Podziel się), żeby umieścić raport na\nforum lub w prywatnej wiadomości",
"msg.noissues.text": "Ukończono! Nie znaleziono błędów!",
"msg.noissues.tip": "Spróbuj odznaczyć niektóre opcje filtrowania lub odpal WME Validator na innym obszarze!",
"msg.scanning.text": "Skanowanie! Koniec za ~ ${n} min",
"msg.scanning.text.soon": "Skanowanie! Koniec w ciągu minuty!",
"msg.scanning.tip": "Kliknij przycisk 'Pauza' by wstrzymać lub '■' (Stop) by zatrzymać",
"msg.starting.text": "Start! Warstwy są wyłączone, by skanować szybciej!",
"msg.starting.tip": "Użyj przycisku 'Pauza' by wstrzymać lub przycisku '■' by zatrzymać",
"msg.paused.text": "Wstrzymane! Kliknij przycisk '▶' (Start) by kontynuować.",
"msg.paused.tip": "Żeby zobaczyć raport, kliknij przycisk 'Pokaż raport' (jeżeli dostępne)",
"msg.continuing.text": "Kontynuowanie!",
"msg.continuing.tip": "WME Validator zacznie ponownie z miejsca, gdzie włączono pauzę",
"msg.settings.text": "Kliknij <b>'Wstecz'</b>, by powrócić do głównego widoku",
"msg.settings.tip": "Kliknij przycisk 'Resetuj domyślne' aby zresetować wszystkie ustawienia za jednym zamachem!",
"msg.reset.text": "Wszystkie opcje filtrowania i ustawienia zostały zresetowane do domyślnych",
"msg.reset.tip": "Kliknij przycisk 'Wstecz', by powrócić do głównego widoku",
"msg.textarea.pack": "To jest skrypt Greasemonkey/Tampermonkey. Tekst poniżej możesz skopiować i wkleić do <b>nowego pliku .user.js</b><br>lub <b>wkleić bezpośrednio</b> do Greasemonkey/Tampermonkey",
"msg.textarea": "Skopiuj proszę tekst poniżej, a następnie wklej do posta lub wiadomości prywatnej",
"noaccess.text": "<b>Sorki,</b><br>Nie możesz tutaj użyć WME Validatora.<br>Sprawdź proszę <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>wątek na forum</a><br> po więcej informacji.",
"noaccess.tip": "Sprawdź proszę wątek na forum po więcej informacji!",
"tab.switch.tip.on": "Kliknij by włączyć podświetlanie (Alt+V)",
"tab.switch.tip.off": "Kliknij by wyłączyć podświetlanie (Alt+V)",
"tab.filter.text": "filtruj",
"tab.filter.tip": "Opcje filtrowania raportu i podświetlonych segmentów",
"tab.search.text": "szukaj",
"tab.search.tip": "Zaawansowane opcje filtrowania, żeby załączyć tylko specyficzne segmenty",
"tab.help.text": "pomoc",
"tab.help.tip": "Potrzebujesz pomocy?",
"filter.noneditables.text": "Wyklucz <b>nieedytowalne</b> segmenty",
"filter.noneditables.tip": "Nie raportuj zablokowanych segmentów lub\nsegmentów poza Twoim obszarem edycji",
"filter.duplicates.text": "Wyklucz <b>duplikowane</b> segmenty",
"filter.duplicates.tip": "Nie pokazuj tego samego segmentu w różnych\nczęściach raportu\n* Info: ta opcja NIE WPŁYWA na podświetlanie",
"filter.streets.text": "Wyklucz <b>Ulice i Drogi Serwisowe</b>",
"filter.streets.tip": "Nie raportuj Ulic i Dróg Serwisowych",
"filter.other.text": "Wyklucz <b>Pozostałe przejezdne i nieprzejezdne</b>",
"filter.other.tip": "Nie raportuj Gruntowych, Wewnętrznych, Prywatnych Dróg\ni nieprzejezdnych segmentów",
"filter.notes.text": "Wyklucz <b>notki</b>",
"filter.notes.tip": "Raportuj tylko ostrzeżenia i błędy",
"search.youredits.text": "Załącz <b>tylko Twoje edycje</b>",
"search.youredits.tip": "Załącz tylko segmenty edytowane przez Ciebie",
"search.updatedby.text": "<b>Zaktualizowane przez*:</b>",
"search.updatedby.tip": "Załącz tylko segmenty edytowane przez ustalonego edytora\n* Info: ta opcja jest dostępna tylko dla CM\nTo pole wspiera:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Info: możesz użyć 'me' dla siebie samego",
"search.updatedby.example": "Przykład: me",
"search.updatedsince.text": "<b>Zaktualizowane od:</b>",
"search.updatedsince.tip": "Załącz tylko segmenty edytowane od ustalonej daty\nformat daty Firefox: RRRR-MM-DD",
"search.updatedsince.example": "RRRR-MM-DD",
"search.city.text": "<b>Nazwa miasta:</b>",
"search.city.tip": "Załącz tylko segmenty z ustaloną nazwą miasta\nTo pole wspiera:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
"search.city.example": "Przykład: !Paris, *",
"search.checks.text": "<b>Zaraportowane jako:</b>",
"search.checks.tip": "Załącz tylko segmenty zgłoszone jako ustalone\nTo pole zawiera:\n - severities: errors\n - check names: New road\n - check IDs: 200\nTo pole wspiera:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
"search.checks.example": "Przykład: reverse*",
"help.text": "<b>Tematy Pomocy:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Zadaj swoje pytanie na forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">Jak dopasować Validator pod swoje państwo</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">Więcej o \"Prawdopodobnie błędna nazwa miasta\"</a>",
"help.tip": "Otwórz w nowej karcie przeglądarki",
"button.scan.tip": "Zacznij skanowanie aktualnego obszaru\n* Info: to może zająć kilka minut",
"button.scan.tip.NA": "Oddal widok by zacząć skanować aktualny obszar",
"button.pause.tip": "Wstrzymaj skanowanie",
"button.continue.tip": "Kontynuuj skanowanie obszaru mapy",
"button.stop.tip": "Zatrzymaj skanowanie i powróć do pozycji startowej",
"button.clear.tip": "Wyczyść raport i cache segmentu",
"button.clear.tip.red": "Zbyt wiele zgłoszonych segmentów:\n 1. Kliknij 'Pokaż raport' by go wygenerować.\n 2. Kliknij ten przycisk by wyczyścić raport i zacząć od nowa.",
"button.report.text": "Pokaż raport",
"button.report.tip": "Zatwierdź filtr i wygeneruj raport HTML w nowej karcie",
"button.BBreport.tip": "Podziel się raportem na forum Waze lub w prywatnej wiadomości",
"button.settings.tip": "Konfiguruj ustawienia",
"tab.custom.text": "własne",
"tab.custom.tip": "Ustawienia sprawdzeń zdefiniowanych przez użytkownika",
"tab.settings.text": "Ustawienia",
"tab.scanner.text": "skaner",
"tab.scanner.tip": "Ustawienia skanera mapy",
"tab.about.text": "o</span>",
"tab.about.tip": "Info o WME Validator",
"scanner.sounds.text": "Włącz dźwięki",
"scanner.sounds.tip": "Pikanie podczas skanowania",
"scanner.sounds.NA": "Twoja przeglądarka nie wspiera AudioContext",
"scanner.highlight.text": "Podświetl błędy na mapie",
"scanner.highlight.tip": "Podświetl zaraportowane błędy na mapie",
"scanner.slow.text": "Włącz sprawdzenia \"slow\"",
"scanner.slow.tip": "Włącza głęboką analizę mapy\n* Info: ta opcja może spowolnić proces skanowania",
"scanner.ext.text": "Raportuj zewnętrzne podświetlenia",
"scanner.ext.tip": "Raportuj segmenty podświetlone przez WME Toolbox lub WME Color Highlights",
"custom.template.text": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Własny szablon</a>",
"custom.template.tip": "Rozszerzalny szablon zdefiniowanych sprawdzeń użytkownika.\n\nMożesz użyć następujących zmiennych:\nAdres:\n ${country}, ${state}, ${city}, ${street},\n ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nWłasności segmentu:\n ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n     ${length}, ${ID}\nPomocniki:\n        ${drivable}, ${roundabout}, ${hasHNs},\n        ${Uturn}, ${deadEnd}, ${softTurns},\n     ${deadEndA}, ${partialA},\n ${deadEndB}, ${partialB}\nŁączność:\n     ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
"custom.template.example": "Przykład ${street}",
"custom.regexp.text": "Własne <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
"custom.regexp.tip": "Wyrażenie regularne zdefiniowane przez użytkownika, by pasowało do szablonu.\n\nNiewrażliwe na wielkość liter: /regexp/i\nNegacja (nie pasujące): !/regexp/\nZapisz informacje debugowania w konsoli: D/regexp/",
"custom.regexp.example": "Przykład: !/.+/",
"about.tip": "Otwórz link w nowej karcie",
"button.reset.text": "Resetuj domyślne",
"button.reset.tip": "Przywróć opcje filtrowania i ustawienia na domyślne",
"button.list.text": "Dostępne sprawdzenia...",
"button.list.tip": "Wyświetl listę sprawdzeń dostępnych w WME Validatorze",
"button.wizard.tip": "Stwórz paczkę językową",
"button.back.text": "Powrót",
"button.back.tip": "Zamknij ustawienia i wróć do głównego widoku",
"1.title": "WME Toolbox: Rondo może powodować problemy",
"1.problem": "ID węzłów ronda nie są w kolejności",
"1.solution": "Stwórz rondo na nowo",
"2.title": "WME Toolbox: Pojedynczy segment",
"2.problem": "Segment ma niepotrzebne węzły",
"2.solution": "Uprość geometrię segmentu przez najechanie myszką i naciśnięcie przycisku \"d\"",
"3.title": "WME Toolbox: Blokada na 2 poziom",
"3.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"4.title": "WME Toolbox: Blokada na 3 poziom",
"4.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"5.title": "WME Toolbox: Blokada na 4 poziom",
"5.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"6.title": "WME Toolbox: Blokada na 5 poziom",
"6.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"7.title": "WME Toolbox: Blokada na 6 poziom",
"7.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"8.title": "WME Toolbox: Numery domów",
"8.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"9.title": "WME Toolbox: Segment z ograniczeniami czasowymi",
"9.problem": "Segment jest podświetlony przez WME Toolbox. To nie jest problem",
"13.title": "WME Color Highlights: Blokada edytora",
"13.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"14.title": "WME Color Highlights: Płatna / Jednokierunkowa",
"14.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"15.title": "WME Color Highlights: Ostatnio edytowane",
"15.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"16.title": "WME Color Highlights: Ranga drogi",
"16.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"17.title": "WME Color Highlights: Brak miasta",
"17.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"18.title": "WME Color Highlights: Ograniczenie czasowe / Podświetlony typ drogi",
"18.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"19.title": "WME Color Highlights: Brak nazwy",
"19.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"20.title": "WME Color Highlights: Filtruj po mieście",
"20.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"21.title": "WME Color Highlights: Filtruj po mieście (alt. miasto)",
"21.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"22.title": "WME Color Highlights: Filtruj po edytorzer",
"22.problem": "Segment jest podświetlony przez WME Color Highlights. To nie jest problem",
"23.solutionLink": "W:Drogi",
"23.title": "Niepotwierdzona droga",
"23.problem": "Każdy segment musi mieć przynajmniej Państwo i Stan",
"23.solution": "Potwierdź drogę, aktualizując jej szczegóły",
"24.title": "Prawdopodobnie błędna nazwa miasta (tylko w raporcie)",
"24.problem": "Segment może zawierać błędną nazwę miasta",
"24.solution": "Rozważ zaproponowaną nazwę i użyj tego formularza do zmiany nazwy miasta",
"25.title": "Nieznana kierunkowość przejezdnej drogi",
"25.problem": "'Nieznana' kierunkowość drogi, nie zapobiegnie wyznaczaniu tędy trasy",
"25.solution": "Ustaw kierunkowość drogi",
"27.enabled": true,
"27.problemLink": "W:Drogi#Tory.2C_szyny",
"27.title": "Nazwa miasta na Torach",
"27.problem": "Nazwa miasta na Torach, szynach",
"27.solution": "Zaznacz pole 'brak' przy nazwie miasta",
"28.problemLink": "W:Drogi#Wjazd.2Fzjazd_bezkolizyjny",
"28.title": "Nazwa ulicy na dwukierunkowym zjeździe",
"28.problem": "Jeśli zjazd jest nienazwany, wyświetli się nazwa docelowej drogi",
"28.solution": "Zmień nazwę ulicy na 'brak'",
"29.problemLink": "W:Drogi#Rondo",
"29.title": "Nazwa ulicy na rondzie",
"29.problem": "W Waze nie nazywamy segmentów ronda",
"29.solution": "Zmień nazwę ulicy na 'brak', a następnie dodaj punkt orientacyjny 'Węzeł drogowy', żeby nazwać rondo",
"34.title": "Pusta nazwa alternatywna",
"34.problem": "Alternatywna nazwa ulicy jest pusta",
"34.solution": "Usuń pustą nazwę alternatywną ulicy",
"35.title": "Niezakończona droga",
"35.problem": "Waze nie poprowadzi z niezakończonego segmentu",
"35.solution": "Przesuń trochę segment, żeby pojawił się kończący węzeł",
"36.title": "Węzeł A: Niepotrzebny (slow)",
"36.problem": "Segmenty spotykające się w węźle A są identyczne",
"36.solution": "Wybierz węzeł A i naciśnij przycisk Delete, by połączyć segmenty",
"37.title": "Węzeł B: Niepotrzebny (slow)",
"37.problem": "Segmenty spotykające się w węźle B są identyczne",
"37.solution": "Wybierz węzeł B i naciśnij przycisk Delete, by połączyć segmenty",
"38.title": "Upłynął czas ograniczenia segmentu (slow)",
"38.problem": "Segment zawiera wygasłe ograniczenie",
"38.solution": "Kliknij 'Edytuj ograniczenia' i usuń wygasłe ograniczenie",
"39.title": "Wygasłe ograniczenie skrętu (slow)",
"39.problem": "Segment ma skręt z wygasłym ograniczeniem",
"39.solution": "Kliknij ikonę zegara obok żółtej strzałki i usuń wygasłe ograniczenie",
"41.title": "Węzeł A: Odwrócona łączność przejezdnej drogi",
"41.problem": "Jeden ze skrętów prowadzi naprzeciw kierunkowi segmentu, w węźle A",
"41.solution": "Ustaw segment 'Dwukierunkowy', zablokuj wszystkie skręty w węźle A i ponownie ustaw 'Jednokierunkowa (A→B)'",
"42.title": "Węzeł B: Odwrócona łączność przejezdnej drogi",
"42.problem": "Jeden ze skrętów prowadzi naprzeciw kierunkowi segmentu, w węźle B",
"42.solution": "Ustaw segment 'Dwukierunkowy', zablokuj wszystkie skręty w węźle A i ponownie ustaw 'Jednokierunkowa (B→A)'",
"43.title": "Połączenie ze sobą",
"43.problem": "Segment łączy się sam ze sobą",
"43.solution": "Podziel segment na TRZY części",
"46.title": "SLOW: Brak wjazdu na węźle A",
"46.problem": "Przejezdny segment nie ma wjazdu na węźle A",
"46.solution": "Rozważ możliwość wjazdu na węźle A",
"47.title": "SLOW: Brak wjazdu na węźle B",
"47.problem": "Przejezdny segment nie ma wjazdu na węźle A",
"47.solution": "Rozważ możliwość wjazdu na węźle A",
"48.solutionLink": "W:Ronda#Poprawianie_rond_naniesionych_r.C4.99cznie",
"48.title": "Dwukierunkowy segment ronda",
"48.problem": "Segment ronda jest dwukierunkowy",
"48.solution": "Stwórz rondo od nowa",
"50.solutionLink": "W:Ronda#Poprawianie_rond_naniesionych_r.C4.99cznie",
"52.enabled": true,
"52.solutionLink": "W:Tabela_skrótów",
"52.title": "Za długa nazwa ulicy",
"52.problem": "Nazwa przejezdnego segmentu jest dłuższa niż ${n} liter i nie jest Rampą",
"52.solution": "Consider an abbreviation for the street name according to this table",
"52.params": {
    "n": 35,
},
"57.enabled": true,
"57.problemLink": "W:Drogi#Wjazd.2Fzjazd_bezkolizyjny",
"57.title": "Nazwa miasta na nazwanym zjeździe",
"57.problem": "Nazwa miasta na nazwanym zjeździe może wpłynąć na wyniki wyszukiwania",
"57.solution": "Zmień nazwę miasta na 'brak'",
"59.enabled": true,
"59.problemLink": "W:Drogi#Autostrada_.2F_Droga_ekspresowa",
"59.title": "Nazwa miasta na Autostradzie",
"59.problem": "Nazwa miasta na Autostradzie, może spowodować że obszar miasta się rozciągnie",
"59.solution": "W danych adresowych ustaw 'Brak' obok nazwy miasta i kliknij 'Zatwierdź'",
"73.enabled": true,
"73.title": "Za krótka nazwa ulicy",
"73.problem": "Nazwa ulicy jest krótsza niż ${n} liter i nie jest autostradą",
"73.solution": "Popraw nazwę ulicy",
"74.solutionLink": "W:Ronda#Poprawianie_rond_naniesionych_r.C4.99cznie",
"78.title": "SLOW: Takie same punkty końcowe segmentów",
"78.problem": "Dwa przejezdne segmenty mają takie same punkty końcowe",
"78.solution": "Podziel segment. Możesz także usunąć segment, jeśli są identyczne",
"79.problemLink": "W:Skrzyżowania#Najlepsze_praktyki_dla_r.C3.B3.C5.BCnych_typ.C3.B3w_skrzy.C5.BCowa.C5.84",
"87.problemLink": "W:Drogi#Rondo",
"87.solutionLink": "W:Ronda#Poprawianie_rond_naniesionych_r.C4.99cznie",
"87.title": "Więcej niż jeden segment wychodzący z węzła A na rondzie",
"87.problem": "Węzeł A na rondzie ma podłączony więcej niż jeden segment wychodzący",
"87.solution": "Utwórz rondo ponownie",
"99.title": "Nawrót na wjeździe na rondo (slow)",
"99.problem": "Segment wjazdu na rondo ma włączoną możliwość zawracania",
"99.solution": "Wyłącz nawrót",
"101.params": {
    "regexp": "/(^|\\b)remont(\\b|$)/i"
},
"101.title": "Droga zamknięta (dostępne tylko w raporcie)",
"101.problem": "Segment jest oznaczony jako zamknięty",
"101.solution": "Gdy remont się skończy, przywróć połączenia segmentu i usuń przyrostek",
"102.title": "SLOW: Brak wyjazdu na węźle A",
"102.problem": "Przejezdny segment nie ma wyjazdu na węźle A",
"102.solution": "Rozważ możliwość wyjazdu na węźle A",
"103.title": "SLOW: Brak wyjazdu na węźle B",
"103.problem": "Przejezdny segment nie ma wyjazdu na węźle B",
"103.solution": "Rozważ możliwość wyjazdu na węźle B",
"104.title": "Tory użyte dla komentarzy",
"104.problem": "Tory są prawdopodobnie użyte do komentarzy na mapie",
"104.solution": "Usuń komentarze, ponieważ Tory będą wyświetlane w aplikacji",
"105.enabled": true,
"105.title": "Ścieżka zamiast Torów",
"105.problem": "Ścieżka o wysokości -5 jest zapewne użyta zamiast Torów",
"105.solution": "Zmień typ drogi na Tory, by wyświetliły się w aplikacji",
"107.title": "SLOW: Brak połączenia w węźle A",
"107.problem": "Węzeł A segmentu jest w odległości od innego, również przejezdnego segmentu, ale nie są połączone skrzyżowaniem",
"107.solution": "Przeciągnij węzeł A na najbliższy segment, by się dotykały, lub odsuń go dalej",
"108.title": "SLOW: Brak połączenia w węźle B",
"108.problem": "Węzeł B segmentu jest w odległości od innego, również przejezdnego segmentu, ale nie są połączone skrzyżowaniem",
"108.solution": "Przeciągnij węzeł B na najbliższy segment, by się dotykały, lub odsuń go dalej",
"109.title": "Za krótki segment",
"109.problem": "Przejezdny, niekońcowy segment jest krótszy niż ${n}m, więc ciężko zobaczyć go na mapie i może powodować problemy z routingiem",
"109.solution": "Zwiększ długość, usuń segment lub połącz go z jednym z przyległych segmentów",
"112.title": "Za długa nazwa Rampy",
"112.problem": "Nazwa Rampy jest dłuższa niż ${n} liter",
"112.solution": "Skróć nazwę Rampy",
"114.title": "Węzeł A: Nieprzejezdna połączona z przejezdną (slow)",
"114.problem": "Nieprzejezdny segment tworzy skrzyżowanie z przejezdnym na węźle A",
"114.solution": "Odłącz węzeł A od wszystkich przejezdnych segmentów",
"115.title": "Węzeł B: Nieprzejezdna połączona z przejezdną (slow)",
"115.problem": "Nieprzejezdny segment tworzy skrzyżowanie z przejezdnym na węźle B",
"115.solution": "Odłącz węzeł B od wszystkich przejezdnych segmentów",
"116.title": "Poza skalą poziomu/wysokości",
"116.problem": "Poziom/wysokość segmentu są poza skalą",
"116.solution": "Popraw poziom/wysokość",
"117.title": "Przestarzały znacznik CONST ZN",
"117.problem": "Segmeny jest oznaczony przestarzałym przyrostkiem CONST ZN",
"117.solution": "Zmień CONST ZN na (zamknięte)",
"118.title": "Węzeł A: Nakładające się segmenty (slow)",
"118.problem": "Segment pokrywa się z sąsiadującym, w węźle A",
"118.solution": "Rozszerz segmenty do 2°, usuń niepotrzebny punkt geometrii lub cały podwójny segment w węźle A",
"119.title": "Węzeł B: Nakładające się segmenty (slow)",
"119.problem": "Segment pokrywa się z sąsiadującym, w węźle B",
"119.solution": "Rozszerz segmenty do 2°, usuń niepotrzebny punkt geometrii lub cały podwójny segment w węźle B",
"120.title": "Węzeł A: Za ostry skręt (slow)",
"120.problem": "Przejezdny segment ma bardzo ostry skręt na węźle A",
"120.solution": "Wyłącz ostry skręt na węźle A lub rozszerz segmenty do 30°",
"121.title": "Węzeł B: Za ostry skręt (slow)",
"121.problem": "Przejezdny segment ma bardzo ostry skręt na węźle B",
"121.solution": "Wyłącz ostry skręt na węźle B lub rozszerz segmenty do 30°",
"128.title": "Własne sprawdzenie (zielone)",
"128.problem": "Niektóre właściwości segmentu są przeciwko ustawionemu przez użytkownika wyrażeniu regularnemu (Ustawienia→Własne)",
"128.solution": "Rozwiąż ten problem",
"129.title": "Własne sprawdzenie (niebieskie)",
"129.problem": "Niektóre właściwości segmentu są przeciwko ustawionemu przez użytkownika wyrażeniu regularnemu (Ustawienia→Własne)",
"129.solution": "Rozwiąż ten problem",
"161.enabled": true,
"161.params": {
    "titleEN": "DKnum in street name",
    "problemEN": "The street name contains DKnum",
    "solutionEN": "Remove the DK prefix from the street name",
    "regexp": "/DK\\-?[0-9]+/i"
},
"161.problemLink": "W:Drogi#Droga_krajowa",
"161.title": "Numer DK w nazwie ulicy",
"161.problem": "Nazwa ulicy zawiera numer DK",
"161.solution": "Usuń przedrostek z nazwy ulicy",
"162.enabled": true,
"162.params": {
    "titleEN": "DWnum in street name",
    "problemEN": "The street name contains DWnum",
    "solutionEN": "Remove the DW prefix from the street name",
    "regexp": "/DW\\-?[0-9]+/i"
},
"162.problemLink": "W:Drogi#Droga_wojew.C3.B3dzka",
"162.title": "Numer DW w nazwie ulicy",
"162.problem": "Nazwa ulicy zawiera numer DW",
"162.solution": "Usuń przedrostek z nazwy ulicy",
"163.enabled": true,
"163.params": {
    "titleEN": "'Węzel' in Ramp name",
    "problemEN": "The Ramp name contains word 'węzel'",
    "solutionEN": "Rename the Ramp in accordance with the guidelines",
    "regexp": "/węze[lł]/i"
},
"163.solutionLink": "W:Drogi#Wjazd.2Fzjazd_bezkolizyjny",
"163.title": "'Węzel' w nazwie zjazdu",
"163.problem": "Zjazd zawiera w nazwie słowo 'węzel'",
"163.solution": "Zmień nazwę zjazdu zgodnie z wytycznymi",
"167.enabled": true,
"167.params": {
    "titleEN": "Incorrect Railroad name",
    "problemEN": "The Railroad name is not 'PKP', 'SKM' or 'MPK'",
    "solutionEN": "In the address properties set the street name to 'PKP', 'SKM' or 'MPK', check the 'None' box next to the city name and then click 'Apply'",
    "regexp": "!/^(PKP|MPK|SKM|Tramwaje Śląskie)$/"
},
"167.solutionLink": "W:Drogi#Tory.2C_szyny",
"167.title": "Nieprawidłowa nazwa Torów",
"167.problem": "Segment Torów ma nieprawidłową nazwę",
"167.solution": "Zmień nazwę segmentu zgodnie z wytycznymi",
"169.enabled": true,
"169.params": {
    "titleEN": "'Rondo' or 'ulica' in street name",
    "problemEN": "The street name contains word 'rondo' or 'ulica'",
    "solutionEN": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout or remove word 'ulica'",
    "regexp": "/rondo |ulica/i"
},
"169.solutionLink": "W:Drogi#Rondo",
"169.title": "'Rondo' lub 'ulica' w nazwie ulicy",
"169.problem": "Nazwa ulicy zawiera słowo 'rondo' lub 'ulica'",
"169.solution": "Zmień nazwę ulicy na 'Brak', a następnie dodaj punkt orientacyjny 'Węzeł drogowy', żeby nazwać rondo lub usuń słowo 'ulica' z nazwy ulicy",
"171.enabled": true,
"171.params": {
    "regexp": "/(^| )(?!(adm|abp|bp|bł|dr|gen|bryg|pil|dyw|hetm|hr|im|inż|kard|ks|kmr|kadm|mjr|marsz|o|os|pl|ppor|ppłk|por|pn|pd|prof|płk|rtm|św|śwj|śś|wsch|zach)\\. |r\\.)[^ ]+\\./"
},
"171.solutionLink": "W:Tabela_skrótów",
"171.title": "Nieprawidłowy skrót w nazwie ulicy",
"171.problem": "Nazwa ulicy zawiera nieprawidłowy skrót",
"171.solution": "Sprawdź wielkie/małe litery, przerwę przed/po skrócie i zgodność z tą tabelą",
"172.title": "Niepotrzebne spacje w nazwie ulicy",
"172.problem": "Spacja na początku, końcu lub podwójna w nazwie ulicy",
"172.solution": "Usuń niepotrzebne spacje z nazwy ulicy",
"173.title": "Nazwa ulicy bez spacji przed lub po skrócie",
"173.problem": "Brak spacji przed ('1943r.') lub po ('st.Jan') skrócie w nazwie ulicy",
"173.solution": "Dodaj spację przed/po skrócie",
"175.title": "Nazwa ulicy złożona z samych spacji",
"175.problem": "Nazwa ulicy zawiera tylko spacje",
"175.solution": "Zmień nazwę ulicy na 'Brak' lub nazwij odpowiednio ulicę",
"190.title": "Nazwa miasta małą literą",
"190.problem": "Nazwa miasta zaczyna się od małej litery",
"190.solution": "Użyj tego formularza, by zmienić nazwę miasta",
"192.title": "Niepotrzebne spacje w nazwie miasta",
"192.problem": "Spacja na początku, końcu lub podwójna w nazwie miasta",
"192.solution": "Użyj tego formularza, by zmienić nazwę miasta",
"193.title": "Brak spacji przed/po skrócie miasta",
"193.problem": "Brak spacji przed ('1943r.') lub po ('st.Jan') skrócie w nazwie miasta",
"193.solution": "Użyj tej formy, by zmienić nazwę miasta",
"200.problemLink": "W:Skrzyżowania#Ograniczenia_skr.C4.99t.C3.B3w",
"200.title": "Węzeł A: Wstępnie dopuszczony lub zakazany skręt na przejezdnej drodze",
"200.problem": "Segment ma niepotwierdzony skręt na węźle A",
"200.solution": "Kliknij na strzałkę z purpurowym znakiem zapytania, by potwierdzić skręt. Zauważ: być może będziesz musiał zmienić segment na dwukierunkowy by dostrzec te",
"201.title": "Węzeł A: Niepotwierdzony skręt na głównej drodze",
"201.problem": "Segment drogi głównej ma niepotwierdzony skręt na węźle A",
"201.solution": "Kliknij skręt z fioletowym znakiem zapytania by go zatwierdzić. Info: możliwe, że będziesz musiał ustawić 'Dwukierunkowy' żeby zobaczyć te skręty"
